export const data = {
	"food-grown-ksm-66-ashwagandha-plus": [
		"Hormonal health",
		"Soothes anxiety",
		"Optimised mood",
		"Reduces stress",
		"Muscle recovery",
		"Healthy libido",
	],
	"food-grown-fertility": [
		"Healthy ovulation",
		"Menstrual support",
		"Optimised mood",
		"Mental resilience",
		"Thyroid balance",
		"Hormone stabilize",
	],
	"food-grown-pregnancy": [
		"Healthy foetal development",
		"Optimised energy",
		"Hormonal balance",
		"Reduced nausea",
		"Combats fatigue",
		"Essential vitamins",
	],
	"food-grown-magnesium": [
		"Deeper sleep",
		"Optimised energy",
		"Muscle recovery",
		"Healthy bones",
		"Improved mood",
		"Mental clarity",
	],
	"food-grown-daily-multi-nutrient-womens": [
		"Boosts immunity",
		"Hormonal support",
		"Optimised energy",
		"Mental resilience",
		"Muscle recovery",
		"Fatigue reduction",
	],
	"hyaluronic-acid": [
		"Skin hydration",
		"Joint pain relief",
		"Collagen formation",
		"Acne repair",
		"Skin elasticity",
		"Wound healing",
	],
	"botanical-menopause-complex": [
		"Hormonal balance",
		"Musculoskeletal support",
		"Optimised energy",
		"Boosts immunity",
		"Healthy bones",
		"Healthy muscles",
	],
	"food-grown-daily-multi-nutrient-45-womens": [
		"Healthy appetite",
		"Metabolism",
		"Healthy bones",
		"Optimised mood",
		"Boosts immunity",
		"Hormone health",
	],
	"food-grown-daily-multi-nutrient-mens": [
		"Immune support",
		"Mental resilience",
		"Optimised energy",
		"Detoxification",
		"Muscle recovery",
		"Testosterone boost",
	],
	"food-grown-daily-multi-nutrient-45-mens": [
		"Exercise recovery",
		"Mental resilience",
		"Immune support",
		"Digestive health",
		"Optimised energy",
		"Testosterone boost",
	],
	"food-grown-breast-feeding-complex": [
		"Healing & recovery",
		"Milk flow & quality",
		"Mood & nerves",
		"Optimised energy",
	],
	"food-grown-fertility-men": [
		"Sperm health",
		"Healthy libido",
		"Immune support",
		"Improved mood",
		"Optimised energy",
		"Testosterone boost",
	],
	"food-grown-daily-multi-nutrient-teengirl": [
		"Cognitive function",
		"Improved mood",
		"Optimised energy",
		"Healthy bones",
		"Hormonal balance",
		"Strong teeth",
	],
	"food-grown-daily-multi-nutrient-child": [
		"Brain development",
		"Immunity boost",
		"Optimised energy",
		"Strong bones",
		"Better focus",
		"Healthy teeth",
	],
	"food-grown-daily-multi-nutrient-teenboy": [
		"Cognitive function",
		"Improved mood",
		"Optimised energy",
		"Healthy bones",
		"Hormonal balance",
		"Strong teeth",
	],
	"food-grown-vitamin-d-child": [
		"Boosts immunity",
		"Healthy bones",
		"Muscle recovery",
		"Deeper sleep",
		"Optimised mood",
		"Strong teeth",
	],
	"multi-strain-biotic-child": [
		"Child microbiomes",
		"Bug defence",
		"Use after antibiotics",
	],
	"food-grown-immune-support": [
		"Optimised energy",
		"Boosts immunity",
		"Antioxidant support",
		"Fights bugs",
		"Anti-inflammatory",
		"Repair & healing",
	],
	"food-grown-vitamin-d": [
		"Boosts immunity",
		"Healthy bones",
		"Muscle recovery",
		"Deeper sleep",
		"Optimised mood",
		"Strong teeth",
	],
	"pure-strength-omega-3": [
		"Improved mood",
		"Optimised vision",
		"Hormone balance",
		"Heart health",
		"Reduced joint pain",
		"Brain function",
	],
	"multi-strain-biotic": [
		"Repair & healing",
		"Immunity boost",
		"Digestive balance",
		"Mental wellbeing",
		"Healthy microbiome",
		"Hormone balance",
	],
	"turmaforte-full-spectrum-turmeric": [
		"For modern living",
		"Improved wellbeing",
		"Antioxidant formula",
	],
	"food-grown-vitamin-c-bioflavonoids": [
		"Exercise recovery",
		"Immune boost",
		"Optimised energy",
		"Strong teeth",
		"Antioxidant support",
		"Health skin",
	],
	"food-grown-iron-plus": [
		"Immunity boost",
		"Brain function",
		"Optimised energy",
		"Reduced fatigue",
		"Health iron levels",
		"Healthy thyroid",
	],
	"food-grown-bone-complex": [
		"For healthy bones",
		"Supports joints ",
		"Bone density",
		"Healthy teeth",
	],
	"food-grown-zinc-plus": [
		"Boosts immunity",
		"Muscle recovery",
		"Optimised fertility",
		"Balanced mood",
		"Antioxidant support",
		"Hair & skin health",
	],
	"food-grown-digestive-enzyme-complex": [
		"Digestive health",
		"Fat breakdown",
		"Protein metabolism",
		"Bowel support",
		"Bloating reduction",
		"Healthy appetite",
	],
	"food-grown-vitamin-b12-plus": [
		"Promotes energy ",
		"Soothes nerves",
		"Cognitive function",
		"Ideal for vegans",
	],
	"vegan-vitamin-d": [
		"Boosts immunity",
		"Healthy bones",
		"Muscle recovery",
		"Deeper sleep",
		"Optimised mood",
		"Strong teeth",
	],
	"food-grown-premenstrual-complex": [
		"Hormone balance",
		"Mental resilience",
		"Stabalised cycle",
		"Improved mood",
		"Optimised energy",
		"Immune support",
	],
	"food-grown-endo-complex": [
		"Menstrual support",
		"Immunity boost",
		"Hormone balance",
		"Detoxification",
		"Optimised energy",
		"Healthy mood",
	],
	"food-grown-b-complex-plus": [
		"Physical resilience",
		"Repair & healing",
		"Antioxidant support",
		"Immune boost",
		"Mental performance",
		"Optimised energy",
	],
	"food-grown-antioxidant-boost": [
		"Muscle recovery",
		"Immune support",
		"Hair & skin health",
		"Detoxification",
		"Hormone balance",
		"Repair & healing",
	],
	"food-grown-balance-multi-nutrient": [
		"Optimised energy",
		"Fatigue recovery",
		"Menstrual support",
		"Immune boost",
		"Healthy metabolism",
		"Balanced mood",
	],
	"food-grown-total-cleanse-complex": [
		"Hormone balance",
		"Detoxification",
		"Digestive support",
		"Immune boost",
		"Optimised energy",
		"Liver health",
	],
	"food-grown-vitamin-b6": [
		"Mental wellbeing",
		"Supports energy",
		"Hormone health",
		"Pregnancy support",
	],
	"your-pregnancy-nutrition-guide": [
		"Delicious recipes",
		"Symptom management",
		"Supplement advice ",
		"Key nutrients ",
	],
	"take-control-of-your-endometriosis": [
		"Menstrual support",
		"Immune support",
		"Hormone balance",
		"Detoxification",
	],
	"childs-strength-omega-3": [
		"Brain development",
		"Healthy vision",
		"Improves mood",
		"Better focus",
		"Cognitive function",
		"Heart health",
	],
	"food-grown-vitamin-c-zinc": [
		"Supports immunity",
		"Growth and energy",
		"Healthy mood ",
		"Cognitive function",
	],
	"food-grown-skin-hair-nails": [
		"Acne support",
		"Hair hydration",
		"Collagen formation",
		"UV protection",
		"Healthy complexion",
		"Nail strength",
	],
	"daily-essentials-for-men": [
		"Daily 360 support",
		"Mental performance",
		"Promotes energy",
		"Optimises immunity",
		"Healthy heart",
		"100% recyclable",
	],
	"daily-essentials-for-women": [
		"Daily 360 support",
		"Healthy hormones",
		"Promotes energy",
		"Optimises immunity",
		"Healthy heart",
		"100% recyclable",
	],
	"natural-glow": [
		"Deeper tan",
		"Longer lasting",
		"Boosts collagen",
		"Firmer skin",
		"Radiant skin",
		"Protects from UV damage",
	],
	"stress-support-duo": [
		"Focus and memory",
		"Manage anxiety",
		"Mood-stabilising",
		"Healthy heart",
	],
	"pregnancy-support-duo": [
		"Foetal development",
		"Optimised energy",
		"Hormonal balance",
		"Nausea management",
		"Healthy heart",
	],
	"gut-health-duo": [
		"Infection defence ",
		"Promotes energy",
		"Microbiome support",
	],
	"natural-energy-duo": [
		"Optimises energy",
		"Immune support",
		"Mood support ",
		"Helps you wind down",
	],
	"menopause-support-duo": [
		"Optimises energy",
		"Mental resilience",
		"Hormone support",
		"Joint health",
		"Blood sugar balance",
	],
	"menopause-support-trio": [
		"Immune support",
		"Hormone regulation",
		"Fatigue recovery",
		"Healthy bones",
		"Joint health",
	],
	"perimenopause-support-trio": [
		"Brain function",
		"Optimised energy",
		"Hormone balance",
		"Joint health",
		"Nervous system",
	],
	"perimenopause-menopause-energy-duo": [
		"Optimised energy",
		"Reduced fatigue",
		"Hormone balance",
		"Repair & healing",
		"Immune boost",
	],
	"ocean-bottle": [
		"Dual opening design",
		"Dishwasher safe",
		"Vacuum insulation",
		"Integrated cup",
	],
	"vegan-protein": [
		"Earth-grown energy",
		"Clear your mind",
		"Strengthen resilience",
		"All-natural endurance",
	],
	"vegan-protein-ocean-bottle": [
		"Supports resilience",
		"Powers your day",
		"Energy support ",
		"Insulated bottle ",
	],
	"cleanse-duo": [
		"Immune support",
		"Supports the liver",
		"Tiredness + fatigue",
		"All-day energy",
	],
	"immune-support-balance-multi-duo": [
		"Optimises energy",
		"Infection defence ",
		"Promotes healing",
		"Relief from fatigue",
	],
	"womens-general-wellness-duo": [
		"Healthy hormones",
		"Mood and mind ",
		"Immune support",
		"Relief from fatigue",
	],
	"mens-general-wellness-duo": [
		"Optimises energy",
		"Supports testosterone",
		"Mental resilience",
		"Muscle recovery",
	],
	"sleep-duo": [
		"Helps you wind down",
		"Nervous system ",
		"Relaxes muscles ",
		"Soothes anxiety",
	],
	"exercise-recovery-duo": [
		"All-day energy",
		"Immune support",
		"Promotes recovery ",
		"Combats fatigue",
	],
	"womens-fertility-duo": [
		"Healthy ovulation",
		"Thyroid and hormones",
		"Stores Omega 3",
		"Supports your cycle",
		"Optimise fertility",
	],
	"mens-fertility-duo": [
		"Optimises fertility",
		"Supports testosterone",
		"Libido and energy",
		"Heart health",
	],
	"endometriosis-support-bundle": [
		"Balanced hormones",
		"Inflammation support",
		"Tiredness + fatigue",
		"Immune support",
	],
	"teen-girl-wellness-duo": [
		"Supports the cycle",
		"Promotes focus",
		"Energy support",
		"Healthy bones + teeth",
	],
	"food-grown-iodine": [
		"Healthier skin & hair",
		"Detoxification",
		"Hormonal balance",
		"Weight management",
		"Optimise focus",
		"Optimise memory",
	],
	"premenstrual-cycle-support-duo": [
		"Hormone support",
		"PCOS support",
		"Optimises energy",
		"Supports mood",
		"Fertility foundation",
	],
	"skin-health-supplements-duo": [
		"Collagen formation",
		"Hair, nails and skin ",
		"Natural, rosy glow",
		"Contains antioxidants",
		"Rich in Zinc",
		"Contains Ashwagandha",
	],
};
