export default function() {

    const numberofproducts = '30';
    const deviceoptions = 'hair removal products';
    const mia_price = parseFloat(((document.querySelector('.CL-MIA2') || {}).dataset || {})['price']).toFixed(2);
    const aria_price = parseFloat(((document.querySelector('.menu_a_1') || {}).dataset || {})['price']).toFixed(2);
    const pedi_price = parseFloat(((document.querySelector('.Clarisonic Pedi') || {}).dataset || {})['price']).toFixed(2);
    const fit_price = parseFloat(((document.querySelector('.CL-MIAF') || {}).dataset || {})['price']).toFixed(2);
    const alpha_price = parseFloat(((document.querySelector('.CL-ALF-GRY') || {}).dataset || {})['price']).toFixed(2);
    const smart_price = parseFloat(((document.querySelector('.CL-SMART') || {}).dataset || {})['price']).toFixed(2);
    const luna_price = parseFloat(((document.querySelector('.FO-LUNA2-F5968-NO') || {}).dataset || {})['price']).toFixed(2);
    const luna_mini_price = parseFloat(((document.querySelector('.FO-MN-LUNA2') || {}).dataset || {})['price']).toFixed(2);
    const luna_men_price = parseFloat(((document.querySelector('.FO-LUNA2-F5999-MEN') || {}).dataset || {})['price']).toFixed(2);
    const bareface_price = parseFloat(((document.querySelector('.RN-ML02P') || {}).dataset || {})['price']).toFixed(2);
    const monty_price = parseFloat(((document.querySelector('.RN-MP03') || {}).dataset || {})['price']).toFixed(2);
    const sweep_price = parseFloat(((document.querySelector('.RN-MAG-SWEEP') || {}).dataset || {})['price']).toFixed(2);
    const pmd_pers_price = parseFloat(((document.querySelector('.PM-INT') || {}).dataset || {})['price']).toFixed(2);
    const pmd_men_price = parseFloat(((document.querySelector('.PM-INT-1004-UK-BLA') || {}).dataset || {})['price']).toFixed(2);
    const tria_4x_price = parseFloat(((document.querySelector('.menu_b_1') || {}).dataset || {})['price']).toFixed(2);
    const tria_price = parseFloat(((document.querySelector('.TR-HRLP') || {}).dataset || {})['price']).toFixed(2);
    const touch_price = parseFloat(((document.querySelector('.IL-TOUCH-FG70701UK') || {}).dataset || {})['price']).toFixed(2);
    const precise_price = parseFloat(((document.querySelector('.IL-HU-FG01171UK') || {}).dataset || {})['price']).toFixed(2);
    const bare_price = parseFloat(((document.querySelector('.CD-CA001194-SSBARE-CONFIG') || {}).dataset || {})['price']).toFixed(2);
    const gold_price = parseFloat(((document.querySelector('.CD-CA00') || {}).dataset || {})['price']).toFixed(2);
    const glide_price = parseFloat(((document.querySelector('.SN-GLU2PE1001-UNI') || {}).dataset || {})['price']).toFixed(2);
    const glide_xpress_price = parseFloat(((document.querySelector('.SN-GLIDE-EX') || {}).dataset || {})['price']).toFixed(2);
    const infinity_price = parseFloat(((document.querySelector('.SN-INF1PE1001') || {}).dataset || {})['price']).toFixed(2);
    const jewel_price = parseFloat(((document.querySelector('.SN-JW1PE1001') || {}).dataset || {})['price']).toFixed(2);
    const iluminage_price = parseFloat(((document.querySelector('.IL-HU-FG00691UK') || {}).dataset || {})['price']).toFixed(2);

    return {
        '1,1,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '1,1,2': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/t/r/tria-4x-group-2.jpg',
            recommendedProduct1Title: 'TRIA HAIR REMOVAL LASER 4X',
            recommendedProduct1Tagline: 'Say Farewell to Unwanted Hair, Permanently',
            recommendedProduct1Link: 'http://www.currentbody.com/tria-hair-removal-laser-4x.html', 
            recommendedProduct1Price: '£' + tria_4x_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '1,1,3': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '1,2,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '1,2,2': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '1,2,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '1,3,1': {
            productName: 'ME CHIC COMPACT',
            productPrice: '£199.00',
            productDesc:'Compact Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/m/e/me-chic-4.jpg',
            productLink: 'http://www.currentbody.com/me-chic-compact-permanent-hair-reduction-device.html'
          },
          '1,3,2': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '1,3,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '2,1,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '2,1,2': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '2,1,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '2,2,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + ''
          },
          '2,2,2': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '2,2,3': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '2,3,1': {
            productName: 'ME CHIC COMPACT',
            productPrice: '£199.00',
            productDesc:'Compact Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/m/e/me-chic-4.jpg',
            productLink: 'http://www.currentbody.com/me-chic-compact-permanent-hair-reduction-device.html'
          },
          '2,3,2': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
          /*  productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html'*/
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '2,3,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '3,1,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
          },
          '3,1,2': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '3,1,3': {
           productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '3,2,1': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
          },
          '3,2,2': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '3,2,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
           /* productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct1Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct1Tagline: 'The gold standard in hair removal',
            recommendedProduct1Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html', 
            recommendedProduct1Price: '£' + infinity_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/s/m/smoothskin-bare-products.jpg',
            recommendedProduct2Title: 'SMOOTHSKIN BARE IPL HAIR REMOVAL DEVICE',
            recommendedProduct2Tagline: 'Say goodbye to razors and wax strips',
            recommendedProduct2Link: 'http://www.currentbody.com/smoothskin-bare-ipl-hair-removal-device.html',
            recommendedProduct2Price: '£' + bare_price + ''
          },
          '3,3,1': {
            productName: 'ME CHIC COMPACT',
            productPrice: '£199.00',
            productDesc:'Compact Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/m/e/me-chic-4.jpg',
            productLink: 'http://www.currentbody.com/me-chic-compact-permanent-hair-reduction-device.html', 
          },
          '3,3,2': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          },
          '3,3,3': {
            productName: 'ILUMINAGE PRECISE TOUCH PERMANENT HAIR REMOVER',
            productPrice: '£' + precise_price + '',
            productDesc:'Convenient Permanent Hair Reduction',
            productImage: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/i/l/iluminage_touch_mini.jpg',
            productLink: 'http://www.currentbody.com/iluminage-precise-touch-permanent-hair-remover.html', 
            /*productName2: 'Silk\'n Infinity 400,000',
            productPrice2: '£159.00',
            productDesc2:'The gold standard in hair removal',
            productImage2: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            productLink2: 'http://www.currentbody.com/silk-n-infinity-400-000.html',  */
            recommendedProduct1Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/716x/9df78eab33525d08d6e5fb8d27136e95/1/0/10190722.jpg',
            recommendedProduct1Title: 'ILUMINAGE TOUCH',
            recommendedProduct1Tagline: 'A Total Revolution in At-Home Hair Removal',
            recommendedProduct1Link: 'http://www.currentbody.com/iluminagetouch.html', 
            recommendedProduct1Price: '£' + touch_price + '',
            recommendedProduct2Image: 'http://www.currentbody.com/media/catalog/product/cache/1/thumbnail/358x/9df78eab33525d08d6e5fb8d27136e95/_/s/_sn-inf1pe1001.jpg',
            recommendedProduct2Title: 'SILK\'N INFINITY 400,000',
            recommendedProduct2Tagline: 'The gold standard in hair removal',
            recommendedProduct2Link: 'http://www.currentbody.com/silk-n-infinity-400-000.html',
            recommendedProduct2Price: '£' + infinity_price + ''
          }
    };
};
