export const topCategoryData = [
  {
    thumbImage: '${category1 thumbnail}',
    url: '${category1 url}',
    heroImage: '${category1 heroImage}',
    title: '${category1 title}',
    bannerTextLine1: '${category1 subtitle line 1}',
    bannerTextLine2: '${category1 subtitle line 2}',
    strategyId: '${category1 strategy ID}',
  },
  {
    thumbImage: '${category2 thumbnail}',
    url: '${category2 url}',
    heroImage: '${category2 heroImage}',
    title: '${category2 title}',
    bannerTextLine1: '${category2 subtitle line 1}',
    bannerTextLine2: '${category2 subtitle line 2}',
    strategyId: '${category2 strategy ID}',
  },
  {
    thumbImage: '${category3 thumbnail}',
    url: '${category3 url}',
    heroImage: '${category3 heroImage}',
    title: '${category3 title}',
    bannerTextLine1: '${category3 subtitle line 1}',
    bannerTextLine2: '${category3 subtitle line 2}',
    strategyId: '${category3 strategy ID}',
  },
  {
    thumbImage: '${category4 thumbnail}',
    url: '${category4 url}',
    heroImage: '${category4 heroImage}',
    title: '${category4 title}',
    bannerTextLine1: '${category4 subtitle line 1}',
    bannerTextLine2: '${category4 subtitle line 2}',
    strategyId: '${category4 strategy ID}',
  },
  {
    thumbImage: '${category5 thumbnail}',
    url: '${category5 url}',
    heroImage: '${category5 heroImage}',
    title: '${category5 title}',
    bannerTextLine1: '${category5 subtitle line 1}',
    bannerTextLine2: '${category5 subtitle line 2}',
    strategyId: '${category5 strategy ID}',
  },
  {
    thumbImage: '${category6 thumbnail}',
    url: '${category6 url}',
    heroImage: '${category6 heroImage}',
    title: '${category6 title}',
    bannerTextLine1: '${category6 subtitle line 1}',
    bannerTextLine2: '${category6 subtitle line 2}',
    strategyId: '${category6 strategy ID}',
  },
];
