const config = {
  strings: {
    '/gb/contacts': {
      it: '/it/contacts',
      es: '/es/contacts',
      de: '',
      fr: '/fr/contacts',
      us: '/gb/contacts',
      ru: '',
    },
    '/gb/mywellness': {
      it: '/it/mywellness',
      es: '/es/mywellness',
      de: '',
      fr: '/fr/mywellness',
      us: '/gb/mywellness',
      ru: '',
    },
    'A fraction of a second, one more rep.  Details make the difference. Details make athletes.': {
      it: 'Ogni dettaglio atletico è importante, così come ogni ripetizione conta o una frazione di secondo può fare la differenza.',
      es: 'Cada detalle atlético cuenta tanto como cada repetición o la más mínima fracción de segundo, que marca la diferencia.',
      de: '',
      fr: "En effet, chaque détail de l'athlétisme compte autant que chaque répétition, une fraction de seconde, aussi infime soit-elle, peut faire la différence.",
      us: 'A fraction of a second, one more rep.  Details make the difference. Details make athletes.',
      ru: '',
    },
    'A perfect synthesis of style, cutting-edge technology, exclusive materials and extraordinary craftsmanship.': {
      it: "Una sintesi perfetta di dettagli e di stile, l'esperienza multisensoriale di un allenamento completo.",
      es: 'Una síntesis perfecta entre estilo, tecnología a la última y materiales exclusivos de calidad artesanal extraordinaria.',
      de: '',
      fr: 'Une synthèse parfaite avec des détails, du style pour une expérience multi sensorielle et un entraînement complet.',
      us: 'A perfect synthesis of style, cutting-edge technology, exclusive materials and extraordinary craftsmanship.',
      ru: '',
    },
    'ARKE': {
      it: 'ARKE',
      es: 'ARKE',
      de: 'ARKE',
      fr: 'ARKE',
      us: 'ARKE',
      ru: '',
    },
    'ARTIS': {
      it: 'ARTIS',
      es: 'ARTIS',
      de: 'ARTIS',
      fr: 'ARTIS',
      us: 'ARTIS',
      ru: '',
    },
    'Accessories': {
      it: 'Accessori',
      es: 'Accesorios',
      de: '',
      fr: 'Accessoires',
      us: 'Accessories',
      ru: '',
    },
    'Benches &amp; Racks': {
      it: 'Panche e Rastrelliere',
      es: 'Bancos de pesas y musculación',
      de: '',
      fr: 'Bancs & Râteliers',
      us: 'Benches &amp; Racks',
      ru: '',
    },
    'Biocircuit': {
      it: 'Biocircuit',
      es: 'Biocircuit',
      de: 'Biocircuit',
      fr: 'Biocircuit',
      us: 'Biocircuit',
      ru: '',
    },
    'Browse the Kit': {
      it: 'Scopri il Kit',
      es: 'Explora el Kit',
      de: '',
      fr: 'Parcourez les produits du Kit',
      us: 'Browse the Kit',
      ru: '',
    },
    'Cable Stations': {
      it: 'Cable Stations',
      es: 'Cable Stations',
      de: 'Cable Stations',
      fr: 'Cable Stations',
      us: 'Cable Stations',
      ru: '',
    },
    'Cardio': {
      it: 'Cardio',
      es: 'Cardio',
      de: 'Cardio',
      fr: 'Cardio',
      us: 'Cardio',
      ru: '',
    },
    'Contact us': {
      it: 'Contattaci',
      es: 'Contáctanos',
      de: '',
      fr: 'Contactez-nous',
      us: 'Contact us',
      ru: '',
    },
    'Discover How': {
      it: 'Scopri come',
      es: 'Descubre como',
      de: '',
      fr: 'En savoir plus',
      us: 'Discover How',
      ru: '',
    },
    'Discover The Line': {
      it: 'Scopri la linea di prodotto',
      es: 'Descubre la Línea',
      de: '',
      fr: 'Découvrez la ligne de produits',
      us: 'Discover The Line',
      ru: '',
    },
    'Element+': {
      it: 'Element+',
      es: 'Element+',
      de: 'Element+',
      fr: 'Element+',
      us: 'Element+',
      ru: '',
    },
    'Elliptical Cross Trainers': {
      it: 'Cross Trainer ellittici',
      es: 'Elípticas',
      de: '',
      fr: 'Elliptiques Cross Trainers',
      us: 'Elliptical Cross Trainers',
      ru: '',
    },
    'Excite': {
      it: 'EXCITE',
      es: 'EXCITE',
      de: 'EXCITE',
      fr: 'EXCITE',
      us: 'Excite',
      ru: '',
    },
    'Exercise bikes': {
      it: 'Bike',
      es: 'Bicicletas estáticas',
      de: '',
      fr: "Vélos d'entraînement",
      us: 'Exercise bikes',
      ru: '',
    },
    'FLEXability': {
      it: 'FLEXability',
      es: 'FLEXability',
      de: 'FLEXability',
      fr: 'FLEXability',
      us: 'FLEXability',
      ru: '',
    },
    'For Your Business': {
      it: 'Per il tuo business',
      es: 'Para tu negocio',
      de: '',
      fr: 'Pour votre entreprise',
      us: 'For Your Business',
      ru: '',
    },
    'For Your Home': {
      it: 'Per la tua casa',
      es: 'Para tu casa',
      de: '',
      fr: 'Pour votre maison',
      us: 'For Your Home',
      ru: '',
    },
    'Forma': {
      it: 'FORMA',
      es: 'FORMA',
      de: 'FORMA',
      fr: 'FORMA',
      us: 'Forma',
      ru: '',
    },
    'Free Weights': {
      it: 'Pesi liberi',
      es: 'Pesos libres',
      de: '',
      fr: 'Poids Libres',
      us: 'Free Weights',
      ru: '',
    },
    'Functional / Flexibility': {
      it: "FUNZIONALE E FLESSIBILITA'",
      es: 'MOVIMIENTO FUNCIONAL',
      de: '',
      fr: 'ENTRAÎNEMENT FONCTIONNEL',
      us: 'Functional / Flexibility',
      ru: '',
    },
    'Functional training equipment': {
      it: "Attrezzi per l'allenamento funzionale",
      es: 'Equipo de entrenamiento funcional',
      de: '',
      fr: 'Equipements Entraînement Fonctionnel',
      us: 'Functional training equipment',
      ru: '',
    },
    'Group Cycle': {
      it: 'Group Cycle',
      es: 'Group Cycle',
      de: 'Group Cycle',
      fr: 'Group Cycle',
      us: 'Group Cycle',
      ru: '',
    },
    'Group Cycling': {
      it: 'Group Cycling',
      es: 'Group Cycling',
      de: 'Group Cycling',
      fr: 'Group Cycling',
      us: 'Group Cycling',
      ru: '',
    },
    'Kinesis': {
      it: 'Kinesis',
      es: 'Kinesis',
      de: 'Kinesis',
      fr: 'Kinesis',
      us: 'Kinesis',
      ru: '',
    },
    'Multigyms and cable stations': {
      it: 'Multigym e Cable Stations',
      es: 'Equipos de gimnasio multifunción y Cable Stations',
      de: '',
      fr: 'Multifonction et station à câbles',
      us: 'Multigyms and cable stations',
      ru: '',
    },
    'My Wellness': {
      it: 'My Wellness',
      es: 'My Wellness',
      de: 'My Wellness',
      fr: 'My Wellness',
      us: 'My Wellness',
      ru: '',
    },
    'Need advice choosing the perfect fitness equipment? Contact us': {
      it: 'Hai bisogno di aiuto per scegliere il prodotto che fa per te? Contattaci',
      es: '¿Necesitas asesoramiento para elegir el perfecto equipo de fitness? Contáctanos',
      de: '',
      fr: 'Vous avez besoin de conseils pour choisir le meilleur équipement fitness ? Contactez-nous',
      us: 'Need advice choosing the perfect fitness equipment? Contact us',
      ru: '',
    },
    'Need help': {
      it: 'Bisogno di aiuto',
      es: 'Necesitas ayuda',
      de: '',
      fr: 'Aide',
      us: 'Need help',
      ru: '',
    },
    'Newsroom': {
      it: 'Newsroom',
      es: 'Newsroom',
      de: 'Newsroom',
      fr: 'Newsroom',
      us: 'Newsroom',
      ru: '',
    },
    'OMNIA': {
      it: 'OMNIA',
      es: 'OMNIA',
      de: 'OMNIA',
      fr: 'OMNIA',
      us: 'OMNIA',
      ru: '',
    },
    'Our Most Popular Products': {
      it: 'I nostri prodotti più visti',
      es: 'Nuestros productos más vistos',
      de: '',
      fr: 'Nos produits les plus regardés',
      us: 'Our Most Popular Products',
      ru: '',
    },
    'Personal': {
      it: 'Personal',
      es: 'Personal',
      de: 'Personal',
      fr: 'Personal',
      us: 'Personal',
      ru: '',
    },
    'Personal Line': {
      it: 'Personal Line',
      es: 'Personal Line',
      de: 'Personal Line',
      fr: 'La ligne Personal',
      us: 'Personal Line',
      ru: '',
    },
    'Plate Loaded': {
      it: 'Attrezzi a carico libero',
      es: 'Pesos libres',
      de: '',
      fr: 'Poids Libres',
      us: 'Plate Loaded',
      ru: '',
    },
    'Plurima': {
      it: 'Plurima',
      es: 'Plurima',
      de: 'Plurima',
      fr: 'Plurima',
      us: 'Plurima',
      ru: '',
    },
    'Product Categories': {
      it: 'Categorie di prodotto',
      es: 'Categorías de productos',
      de: '',
      fr: 'Catégories de produits',
      us: 'Product Categories',
      ru: '',
    },
    'Product Ranges': {
      it: 'Linee di prodotto',
      es: 'Líneas de producto',
      de: '',
      fr: 'Lignes de produits',
      us: 'Product Ranges',
      ru: '',
    },
    'Pure Strength': {
      it: 'Pure Strength',
      es: 'Pure Strength',
      de: 'Pure Strength',
      fr: 'Pure Strength',
      us: 'Pure Strength',
      ru: '',
    },
    'Read more': {
      it: 'Scopri di più',
      es: 'Descubre más',
      de: '',
      fr: 'En savoir plus',
      us: 'Read more',
      ru: '',
    },
    'Rowers': {
      it: 'Rowers',
      es: 'Rowers',
      de: 'Rowers',
      fr: 'Rowers',
      us: 'Rowers',
      ru: '',
    },
    'Selection Pro': {
      it: 'Selection Pro',
      es: 'Selection Pro',
      de: 'Selection Pro',
      fr: 'Selection Pro',
      us: 'Selection Pro',
      ru: '',
    },
    'Selectorised': {
      it: 'Attrezzi isotonici',
      es: 'Selectorizados',
      de: '',
      fr: 'Charges Guidées',
      us: 'Selectorised',
      ru: '',
    },
    'Skilltools': {
      it: 'Skilltools',
      es: 'Skilltools',
      de: 'Skilltools',
      fr: 'Skilltools',
      us: 'Skilltools',
      ru: '',
    },
    'Stair Climbers': {
      it: 'Stair Climbers',
      es: 'Stair Climbers',
      de: 'Stair Climbers',
      fr: 'Stair Climbers',
      us: 'Stair Climbers',
      ru: '',
    },
    'Strength': {
      it: 'Forza',
      es: 'Fuerza',
      de: '',
      fr: 'Musculation',
      us: 'Strength',
      ru: '',
    },
    'Stretching': {
      it: 'Stretching',
      es: 'Stretching',
      de: 'Stretching',
      fr: 'Stretching',
      us: 'Stretching',
      ru: '',
    },
    'The ground-breaking workout that adapts to your own body, fitness goals and time.': {
      it: 'Il rivoluzionario allenamento che si adatta al tuo corpo, ai tuoi obiettivi di fitness e al tuo tempo.',
      es: "L'entraînement révolutionnaire qui s'adapte à votre corps, à vos objectifs de fitness et à votre temps.",
      de: '',
      fr: 'El entrenamiento innovador que se adapta a tu propio cuerpo, objetivos de ejercicio y tiempo.',
      us: 'The ground-breaking workout that adapts to your own body, fitness goals and time.',
      ru: '',
    },
    'Treadmills': {
      it: 'Tapis roulant',
      es: 'Cintas de correr',
      de: '',
      fr: 'Tapis de course',
      us: 'Treadmills',
      ru: '',
    },
    'Upper Body trainers': {
      it: 'Attrezzi per la parte superiore',
      es: 'Entrenamiento del tren superior',
      de: '',
      fr: 'Membres Supérieurs',
      us: 'Upper Body trainers',
      ru: '',
    },
    'View all products': {
      it: 'Tutti i Prodotti',
      es: 'Todos los productos',
      de: '',
      fr: 'Tous les produits',
      us: 'View all products',
      ru: '',
    },
    'Wellness Tools': {
      it: 'Wellness Tools',
      es: 'Wellness Tools',
      de: 'Wellness Tools',
      fr: 'Wellness Tools',
      us: 'Wellness Tools',
      ru: '',
    },
    'here': {
      it: 'qui',
      es: 'aquí',
      de: '',
      fr: 'ici',
      us: 'here',
      ru: '',
    },
    'https://www.technogym.com/gb/biocircuit/': {
      it: 'https://www.technogym.com/it/biocircuit/',
      es: 'https://www.technogym.com/es/biocircuit/',
      de: '',
      fr: 'https://www.technogym.com/fr/biocircuit/',
      us: 'https://www.technogym.com/gb/biocircuit/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/artis/': {
      it: 'https://www.technogym.com/it/line/linea-artis/',
      es: 'https://www.technogym.com/es/line/la-gama-artis/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-artis/',
      us: 'https://www.technogym.com/gb/line/artis/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/cable-stations-range/': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-multigym_e_cable_stations.html',
      es: 'https://www.technogym.com/es/line/la-gama-cable-stations/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-cable-stations/',
      us: 'https://www.technogym.com/gb/line/cable-stations-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/excite-range/': {
      it: 'https://www.technogym.com/it/line/excite-range/',
      es: 'https://www.technogym.com/es/line/excite-range/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/excite-range/',
      us: 'https://www.technogym.com/gb/line/excite-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/formanew-release/': {
      it: 'https://www.technogym.com/it/line/formanew-release/',
      es: 'https://www.technogym.com/es/line/formanew-release/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/formanew-release/',
      us: 'https://www.technogym.com/gb/line/formanew-release/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/selection-pro/': {
      it: 'https://www.technogym.com/it/line/selection/',
      es: 'https://www.technogym.com/es/line/selection/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/selection',
      us: 'https://www.technogym.com/gb/line/selection-pro/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-arke-range/': {
      it: 'https://www.technogym.com/it/line/linea-arke/',
      es: 'https://www.technogym.com/es/line/la-gama-arke/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-arke/',
      us: 'https://www.technogym.com/gb/line/the-arke-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-element-range/': {
      it: 'https://www.technogym.com/it/line/linea-element/',
      es: 'https://www.technogym.com/es/line/la-gama-element/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-element/',
      us: 'https://www.technogym.com/gb/line/the-element-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-flexability-range/': {
      it: 'https://www.technogym.com/it/line/linea-flexability/',
      es: 'https://www.technogym.com/es/line/la-gama-flexability/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-flexability/',
      us: 'https://www.technogym.com/gb/line/the-flexability-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-group-cycle-range/': {
      it: 'https://www.technogym.com/it/line/linea-group-cycle/',
      es: 'https://www.technogym.com/es/line/la-gama-group-cycle/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-group-cycle/',
      us: 'https://www.technogym.com/gb/line/the-group-cycle-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-kinesis-stations-range/': {
      it: 'https://www.technogym.com/it/line/linea-kinesis/',
      es: 'https://www.technogym.com/es/line/la-gama-kinesis/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-kinesis/',
      us: 'https://www.technogym.com/gb/line/the-kinesis-stations-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-omnia-range/': {
      it: 'https://www.technogym.com/it/line/linea-omnia/',
      es: 'https://www.technogym.com/es/line/la-gama-omnia/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-omnia/',
      us: 'https://www.technogym.com/gb/line/the-omnia-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-personal-range/': {
      it: 'https://www.technogym.com/it/line/linea-personal/',
      es: 'https://www.technogym.com/es/line/la-gama-personal/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-personal/',
      us: 'https://www.technogym.com/gb/line/the-personal-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-plurima-range/': {
      it: 'https://www.technogym.com/it/line/linea-plurima/',
      es: 'https://www.technogym.com/es/line/la-gama-plurima',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-plurima/',
      us: 'https://www.technogym.com/gb/line/the-plurima-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-pure-strength-range/': {
      it: 'https://www.technogym.com/it/line/linea-pure/',
      es: 'https://www.technogym.com/es/line/la-gama-pure/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-pure/',
      us: 'https://www.technogym.com/gb/line/the-pure-strength-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/line/the-wellness-tools-range/': {
      it: 'https://www.technogym.com/it/line/linea-wellness-tools/',
      es: 'https://www.technogym.com/es/line/la-gama-wellness-tools/',
      de: '',
      fr: 'https://www.technogym.com/fr/line/la-gamme-wellness-tools/',
      us: 'https://www.technogym.com/gb/line/the-wellness-tools-range/',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-accessories.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-accessori.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-accesorios.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-accessoires.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-accessories.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-benches_racks.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-panche_e_rastrelliere.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-bancos_de_pesas_y_musculacion.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-bancs_rateliers.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-benches_racks.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-elliptical_cross_trainers.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-cross_trainer_ellittici.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-elipticas.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-elliptiques_cross_trainers.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-elliptical_cross_trainers.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-exercise_bikes.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-bike.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-bicicletas_estaticas.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-velos_d_entrainement.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-exercise_bikes.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-free_weights.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-pesi_liberi.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-pesos_libres.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-poids_libres.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-free_weights.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-functional_training_equipment.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-attrezzi_per_l_allenamento_funzionale.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-equipo_de_entrenamiento_funcional.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-equipements_entrainement_fonctionnel.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-functional_training_equipment.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-group_cycling.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-group_cycling.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-group_cycling.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-group_cycling.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-group_cycling.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-multigyms_and_cable_stations.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-multigym_e_cable_stations.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-equipos_de_gimnasio_multifuncion_y_cable_stations.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-multifonction_et_station_a_cables.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-multigyms_and_cable_stations.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-plate_loaded.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-attrezzi_a_carico_libero.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-palanca.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-charges_libres.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-plate_loaded.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-rowers.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-rowers.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-rowers.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-rowers.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-rowers.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-selectorised.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-attrezzi_isotonici.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-selectorizados.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-charges_guidees.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-selectorised.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-stair_climbers.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-stair_climbers.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-stair_climbers.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-stair_climbers.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-stair_climbers.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-stretching.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-stretching.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-estiramiento.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-stretching.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-stretching.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-treadmills.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-tapis_roulant.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-cintas_de_correr.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-tapis_de_course.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-treadmills.html',
      ru: '',
    },
    'https://www.technogym.com/gb/products/shopby/product_type-upper_body_trainers.html': {
      it: 'https://www.technogym.com/it/products/shopby/product_type-attrezzi_per_la_parte_superiore.html',
      es: 'https://www.technogym.com/es/products/shopby/product_type-entrenamiento_del_tren_superior.html',
      de: '',
      fr: 'https://www.technogym.com/fr/products/shopby/product_type-membres_superieurs.html',
      us: 'https://www.technogym.com/gb/products/shopby/product_type-upper_body_trainers.html',
      ru: '',
    },
    'https://www.technogym.com/gb/skilltools-kit.html': {
      it: 'https://www.technogym.com/it/skilltools-kit.html',
      es: 'https://www.technogym.com/es/skilltools-kit.html',
      de: '',
      fr: 'https://www.technogym.com/fr/skilltools-kit.html',
      us: 'https://www.technogym.com/gb/skilltools-kit.html',
      ru: '',
    },
    'or advice?': {
      it: 'o di consiglio?',
      es: 'o asesoramiento?',
      de: '',
      fr: 'Conseils/Assistance?',
      us: 'or advice?',
      ru: '',
    },
  },
  popular: {
    'home': {
      'gb': [
          {
              title: 'MYRUN',
              link: 'https://www.technogym.com/gb/treadmill-myrun.html',
              price: '£3,250.00',
              img: '//cdn.optimizely.com/img/8355110909/b3874915f219488691e101d5c9c491b0.jpg'
          },
          {
              title: 'RUN PERSONAL',
              link: 'https://www.technogym.com/gb/run-personal.html',
              img: '//cdn.optimizely.com/img/8355110909/10730fc3d9d9486f98df868674865eb8.jpg',
              price: '£13,000.00'
          },
          {
              title: 'MYCYCLING',
              link: 'https://www.technogym.com/gb/mycycling.html',
              img: "//cdn.optimizely.com/img/8355110909/e0da501678674e87b36774a0125d0037.jpg",
              price: '£1,590.00'
          },
          {
              title: 'RECLINE PERSONAL',
              img: "//cdn.optimizely.com/img/8355110909/4b203e12892b4fc38848b5a79454c0ca.jpg",
              link: 'https://www.technogym.com/gb/recline-personal.html',
              price: '£9,250.00'
          },
          {
              title: 'CROSS PERSONAL',
              img: '//cdn.optimizely.com/img/8355110909/533ce87b30f445588d1819e0a0300a9c.jpg',
              link: 'https://www.technogym.com/gb/cross-personal.html',
              price: '£12,000.00'
          },
          {
              title: 'SKILLROW™',
              img: "//cdn.optimizely.com/img/8355110909/631e94aebef04844a81ca73f693ae000.jpg",
              link: 'https://www.technogym.com/gb/skillrow.html',
              price: '£3,490.00'
          },
      ],
      'it': [
          {
              title: 'MYRUN',
              link: 'https://www.technogym.com/it/tapis-roulant-myrun.html',
              price: '€ 3.250,00',
              img: '//cdn.optimizely.com/img/8355110909/b3874915f219488691e101d5c9c491b0.jpg'
          },
          {
              title: 'RUN PERSONAL',
              link: 'https://www.technogym.com/it/run-personal.html',
              img: '//cdn.optimizely.com/img/8355110909/10730fc3d9d9486f98df868674865eb8.jpg',
              price: '€ 13.500,00'
          },
          {
              title: 'MYCYCLING',
              link: 'https://www.technogym.com/it/mycycling.html',
              img: "//cdn.optimizely.com/img/8355110909/e0da501678674e87b36774a0125d0037.jpg",
              price: '€ 1.790,00'
          },
          {
              title: 'RECLINE PERSONAL',
              img: "//cdn.optimizely.com/img/8355110909/4b203e12892b4fc38848b5a79454c0ca.jpg",
              link: 'https://www.technogym.com/it/recline-personal.html',
              price: '€ 9.750,00'
          },
          {
              title: 'CROSS PERSONAL',
              img: '//cdn.optimizely.com/img/8355110909/533ce87b30f445588d1819e0a0300a9c.jpg',
              link: 'https://www.technogym.com/it/cross-personal.html',
              price: '€ 12.500,00'
          },
          {
              title: 'SKILLROW™',
              img: "//cdn.optimizely.com/img/8355110909/631e94aebef04844a81ca73f693ae000.jpg",
              link: 'https://www.technogym.com/it/skillrow.html',
              price: '€ 3.490,00'
          },
      ],
      'es': [
          {
              title: 'MYRUN',
              link: 'https://www.technogym.com/es/cinta-de-correr-myrun.html',
              price: '€ 3.250,00',
              img: '//cdn.optimizely.com/img/8355110909/b3874915f219488691e101d5c9c491b0.jpg'
          },
          {
              title: 'RUN PERSONAL',
              link: 'https://www.technogym.com/es/run-personal.html',
              img: '//cdn.optimizely.com/img/8355110909/10730fc3d9d9486f98df868674865eb8.jpg',
              price: '€ 13.500,00'
          },
          {
              title: 'MYCYCLING',
              link: 'https://www.technogym.com/es/mycycling.html',
              img: "//cdn.optimizely.com/img/8355110909/e0da501678674e87b36774a0125d0037.jpg",
              price: '€ 1.790,00'
          },
          {
              title: 'RECLINE PERSONAL',
              img: "//cdn.optimizely.com/img/8355110909/4b203e12892b4fc38848b5a79454c0ca.jpg",
              link: 'https://www.technogym.com/es/recline-personal.html',
              price: '€ 9.750,00'
          },
          {
              title: 'CROSS PERSONAL',
              img: '//cdn.optimizely.com/img/8355110909/533ce87b30f445588d1819e0a0300a9c.jpg',
              link: 'https://www.technogym.com/es/cross-personal.html',
              price: '€ 12.500,00'
          },
          {
              title: 'SKILLROW™',
              img: "//cdn.optimizely.com/img/8355110909/631e94aebef04844a81ca73f693ae000.jpg",
              link: 'https://www.technogym.com/es/skillrow.html',
              price: '€ 3.490,00'
          },
      ],
      'fr': [
          {
              title: 'MYRUN',
              link: 'https://www.technogym.com/fr/treadmill-myrun.html',
              price: '3 250,00 €',
              img: '//cdn.optimizely.com/img/8355110909/b3874915f219488691e101d5c9c491b0.jpg'
          },
          {
              title: 'RUN PERSONAL',
              link: 'https://www.technogym.com/fr/run-personal.html',
              img: '//cdn.optimizely.com/img/8355110909/10730fc3d9d9486f98df868674865eb8.jpg',
              price: '13 500,00 €'
          },
          {
              title: 'MYCYCLING',
              link: 'https://www.technogym.com/fr/mycycling.html',
              img: "//cdn.optimizely.com/img/8355110909/e0da501678674e87b36774a0125d0037.jpg",
              price: '1 790,00 €'
          },
          {
              title: 'RECLINE PERSONAL',
              img: "//cdn.optimizely.com/img/8355110909/4b203e12892b4fc38848b5a79454c0ca.jpg",
              link: 'https://www.technogym.com/fr/recline-personal.html',
              price: '9 750,00 €'
          },
          {
              title: 'CROSS PERSONAL',
              img: '//cdn.optimizely.com/img/8355110909/533ce87b30f445588d1819e0a0300a9c.jpg',
              link: 'https://www.technogym.com/fr/cross-personal.html',
              price: '12 500,00 €'
          },
          {
              title: 'SKILLROW™',
              img: "//cdn.optimizely.com/img/8355110909/631e94aebef04844a81ca73f693ae000.jpg",
              link: 'https://www.technogym.com/fr/skillrow.html',
              price: '3 490,00 €'
          },
      ]
    },
    'business': {
      'gb': [
          {
              title: 'SKILLRUN',
              img: '//cdn.optimizely.com/img/8355110909/0b54260e2fad4080add5dc4bb50548e5.jpg',
              link: 'https://www.technogym.com/gb/skillrun.html',
              price: ''
          },
          {
              title: 'SKILLTOOLS',
              img: '//cdn.optimizely.com/img/8355110909/4b078625736e4aa98a0d0f515645aa1d.jpg',
              link: 'https://www.technogym.com/gb/skilltools-kit.html',
              price: ''
          },
          {
              title: 'SKILLMILL CONNECT',
              img: '//cdn.optimizely.com/img/8355110909/f6bae37f21a64c74aeb2ee0cf88a0267.jpg',
              link: 'https://www.technogym.com/gb/skillmill-connect.html',
              price: ''
          },
          {
              title: 'ARTIS RUN',
              img: '//cdn.optimizely.com/img/8355110909/0f7721f793af4ad88a044075c565e490.jpg',
              link: 'https://www.technogym.com/gb/treadmill-artis-run-standard.html',
              price: ''
          },
          {
              title: 'ARTIS RECLINE',
              img: '//cdn.optimizely.com/img/8355110909/05e12788b9694250a32f24a724cf1d6b.jpg',
              link: 'https://www.technogym.com/gb/artis-recline-standard.html',
              price: ''
          },
          {
              title: 'ARTIS SYNCHRO',
              img: '//cdn.optimizely.com/img/8355110909/a0f8d4d7cc424d0c89c212fe7e8334dc.jpg',
              link: 'https://www.technogym.com/gb/artis-synchro-standard.html',
              price: ''
          },
      ],
      'it': [
          {
              title: 'SKILLRUN',
              img: '//cdn.optimizely.com/img/8355110909/0b54260e2fad4080add5dc4bb50548e5.jpg',
              link: 'https://www.technogym.com/it/skillrun.html',
              price: ''
          },
          {
              title: 'SKILLTOOLS',
              img: '//cdn.optimizely.com/img/8355110909/4b078625736e4aa98a0d0f515645aa1d.jpg',
              link: 'https://www.technogym.com/it/skilltools-kit.html',
              price: ''
          },
          {
              title: 'SKILLMILL CONNECT',
              img: '//cdn.optimizely.com/img/8355110909/f6bae37f21a64c74aeb2ee0cf88a0267.jpg',
              link: 'https://www.technogym.com/it/skillmill-connect-technogym.html',
              price: ''
          },
          {
              title: 'ARTIS RUN',
              img: '//cdn.optimizely.com/img/8355110909/0f7721f793af4ad88a044075c565e490.jpg',
              link: 'https://www.technogym.com/it/treadmill-artis-run-standard.html',
              price: ''
          },
          {
              title: 'ARTIS RECLINE',
              img: '//cdn.optimizely.com/img/8355110909/05e12788b9694250a32f24a724cf1d6b.jpg',
              link: 'https://www.technogym.com/it/artis-recline-standard.html',
              price: ''
          },
          {
              title: 'ARTIS SYNCHRO',
              img: '//cdn.optimizely.com/img/8355110909/a0f8d4d7cc424d0c89c212fe7e8334dc.jpg',
              link: 'https://www.technogym.com/it/artis-synchro-standard.html',
              price: ''
          },
      ],
      'es': [
          {
              title: 'SKILLRUN',
              img: '//cdn.optimizely.com/img/8355110909/0b54260e2fad4080add5dc4bb50548e5.jpg',
              link: 'https://www.technogym.com/es/skillrun.html',
              price: ''
          },
          {
              title: 'SKILLTOOLS',
              img: '//cdn.optimizely.com/img/8355110909/4b078625736e4aa98a0d0f515645aa1d.jpg',
              link: 'https://www.technogym.com/es/skilltools-kit.html',
              price: ''
          },
          {
              title: 'SKILLMILL CONNECT',
              img: '//cdn.optimizely.com/img/8355110909/f6bae37f21a64c74aeb2ee0cf88a0267.jpg',
              link: 'https://www.technogym.com/es/skillmill-connect-technogym.html',
              price: ''
          },
          {
              title: 'ARTIS RUN',
              img: '//cdn.optimizely.com/img/8355110909/0f7721f793af4ad88a044075c565e490.jpg',
              link: 'https://www.technogym.com/es/treadmill-artis-run-standard.html',
              price: ''
          },
          {
              title: 'ARTIS RECLINE',
              img: '//cdn.optimizely.com/img/8355110909/05e12788b9694250a32f24a724cf1d6b.jpg',
              link: 'https://www.technogym.com/es/artis-recline-standard.html',
              price: ''
          },
          {
              title: 'ARTIS SYNCHRO',
              img: '//cdn.optimizely.com/img/8355110909/a0f8d4d7cc424d0c89c212fe7e8334dc.jpg',
              link: 'https://www.technogym.com/es/artis-synchro-standard.html',
              price: ''
          },
      ],
      'fr': [
          {
              title: 'SKILLRUN',
              img: '//cdn.optimizely.com/img/8355110909/0b54260e2fad4080add5dc4bb50548e5.jpg',
              link: 'https://www.technogym.com/fr/skillrun.html',
              price: ''
          },
          {
              title: 'SKILLTOOLS',
              img: '//cdn.optimizely.com/img/8355110909/4b078625736e4aa98a0d0f515645aa1d.jpg',
              link: 'https://www.technogym.com/fr/skilltools-kit.html',
              price: ''
          },
          {
              title: 'SKILLMILL CONNECT',
              img: '//cdn.optimizely.com/img/8355110909/f6bae37f21a64c74aeb2ee0cf88a0267.jpg',
              link: 'https://www.technogym.com/fr/skillmill-connect-technogym.html',
              price: ''
          },
          {
              title: 'ARTIS RUN',
              img: '//cdn.optimizely.com/img/8355110909/0f7721f793af4ad88a044075c565e490.jpg',
              link: 'https://www.technogym.com/fr/treadmill-artis-run-standard.html',
              price: ''
          },
          {
              title: 'ARTIS RECLINE',
              img: '//cdn.optimizely.com/img/8355110909/05e12788b9694250a32f24a724cf1d6b.jpg',
              link: 'https://www.technogym.com/fr/artis-recline-standard.html',
              price: ''
          },
          {
              title: 'ARTIS SYNCHRO',
              img: '//cdn.optimizely.com/img/8355110909/a0f8d4d7cc424d0c89c212fe7e8334dc.jpg',
              link: 'https://www.technogym.com/fr/artis-synchro-standard.html',
              price: ''
          },
      ],
    },
  },
};

export default config;
