export const ctaConfigV1 = [
  {
    pathFactory: 'finance',
    landingUrl: '/g/dont-stop-now-finance/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-finance/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/de-de/g/ihr-unternehmen-waechst-sooo-schnell/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-finance-de/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Jetzt anschauen',
    supportingCopy: 'Lernen Sie Ihr Unternehmen mit dem Cloud Native-Ansatz zu skalieren.',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/fr-fr/g/ne-vous-arretez-pas-en-si-bon-chemin-finance/',
    ctaLink:
      'https://content.gocardless.com/cloud-natives-finance-fr/la-digitalisation-des-paiements-un-atout-pour-les-entreprises-temoignage-doctolib',
    ctaCopy: 'Regardez maintenant',
    supportingCopy: 'Découvrez comment Doctolib soigne sa trésorerie grâce à la digitalisation des paiements.',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-us/g/dont-stop-now-finance/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-finance-na/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-au/g/dont-stop-now-finance/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-au/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-nz/g/dont-stop-now-finance/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-finance-nz/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/es-es/g/creciendo-tan-rapido/',
    ctaLink: 'https://content.gocardless.com/esp-born-digital-finance/dominio-de-los-pagos',
    ctaCopy: 'Ver a pedido',
    supportingCopy: 'Aprenda a ampliar su negocio como un nativo en la nuebe en 30 minutos',
  },
  {
    pathFactory: 'product',
    landingUrl: '/g/growing-sooo-fast-product/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-product/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'product',
    landingUrl: '/de-de/g/de-ihr-unternehmen-waechst-sooo-schnell/',
    ctaLink: 'https://content.gocardless.com/cloud-native-de/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Jetzt anschauen',
    supportingCopy: 'Lernen Sie Ihr Unternehmen mit dem Cloud Native-Ansatz zu skalieren.',
  },
  {
    pathFactory: 'product',
    landingUrl: '/fr-fr/g/vous-grandissez-si-vite-produit/',
    ctaLink:
      'https://content.gocardless.com/cloud-native-product-fr/la-digitalisation-des-paiements-un-atout-pour-les-entreprises-temoignage-doctolib',
    ctaCopy: 'Regardez maintenant',
    supportingCopy: 'Découvrez comment Doctolib soigne sa trésorerie grâce à la digitalisation des paiements.',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-us/g/growing-sooo-fast-product/',
    ctaLink: 'https://content.gocardless.com/cloud-native-product-na/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-au/g/growing-sooo-fast-product/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-product-au/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-nz/g/growing-sooo-fast-product/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-product-nz/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'product',
    landingUrl: '/es-es/g/ustedesta-creciendo-tan-rapido/',
    ctaLink: 'https://content.gocardless.com/cloud-native-es/dominio-de-los-pagos',
    ctaCopy: 'Ver a pedido',
    supportingCopy: 'Aprenda a ampliar su negocio como un nativo en la nuebe en 30 minutos',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/g/dont-stop-now-c-suite/',
    ctaLink: 'https://content.gocardless.com/cloud-natives/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/de-de/g/hoeren-sie-jetzt-nicht-auf-c-suite/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-de/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Jetzt anschauen',
    supportingCopy: 'Lernen Sie Ihr Unternehmen mit dem Cloud Native-Ansatz zu skalieren.',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/fr-fr/g/e-vous-arretez-pas-en-si-bon-chemin-csuite/',
    ctaLink:
      'https://content.gocardless.com/cloud-natives-fr/la-digitalisation-des-paiements-un-atout-pour-les-entreprises-temoignage-doctolib',
    ctaCopy: 'Regardez maintenant',
    supportingCopy: 'Découvrez comment Doctolib soigne sa trésorerie grâce à la digitalisation des paiements.',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-us/g/dont-stop-now-c-suite/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-na/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-au/g/dont-stop-now-c-suite/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-au/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-nz/g/dont-stop-now-c-suite/',
    ctaLink: 'https://content.gocardless.com/cloud-natives-nz/cloud-native-mastering-payments-webinar',
    ctaCopy: 'Watch On-Demand',
    supportingCopy: 'Learn how to scale your business like a Cloud Native in 30 minutes',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/es-es/g/no-pare-ahora/',
    ctaLink: 'https://content.gocardless.com/esp-born-digital-c-suite/dominio-de-los-pagos',
    ctaCopy: 'Ver a pedido',
    supportingCopy: 'Aprenda a ampliar su negocio como un nativo en la nuebe en 30 minutos',
  },
];

export const ctaConfigV2 = [
  {
    pathFactory: 'finance',
    landingUrl: '/g/dont-stop-now-finance/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-29/2bsw9z',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/de-de/g/ihr-unternehmen-waechst-sooo-schnell/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj4z',
    ctaCopy: 'Kontaktieren Sie uns',
    supportingCopy: 'Bereit Ihre Zahlungen mit GoCardless zu verbessern?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/fr-fr/g/ne-vous-arretez-pas-en-si-bon-chemin-finance/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj68',
    ctaCopy: 'Parlons-en',
    supportingCopy: 'Prêt à améliorer vos paiements avec GoCardless?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-us/g/dont-stop-now-finance/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj6xSource_c=Contact%20Sales',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-au/g/dont-stop-now-finance/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/en-nz/g/dont-stop-now-finance/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'finance',
    landingUrl: '/es-es/g/creciendo-tan-rapido/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2022-01-10/2wfx2p',
    ctaCopy: 'Estamos a la espera',
    supportingCopy: '¿Está listo para mejorar sus pagos con GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/es-es/g/ustedesta-creciendo-tan-rapido/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2022-01-10/2wfx2p',
    ctaCopy: 'Estamos a la espera',
    supportingCopy: '¿Está listo para mejorar sus pagos con GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/g/growing-sooo-fast-product/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-29/2bsw9z',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/de-de/g/de-ihr-unternehmen-waechst-sooo-schnell/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj4z',
    ctaCopy: 'Kontaktieren Sie uns',
    supportingCopy: 'Bereit Ihre Zahlungen mit GoCardless zu verbessern?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/fr-fr/g/vous-grandissez-si-vite-produit/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj68',
    ctaCopy: 'Parlons-en',
    supportingCopy: 'Prêt à améliorer vos paiements avec GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-us/g/growing-sooo-fast-product/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj6xSource_c=Contact%20Sales',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-au/g/growing-sooo-fast-product/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'product',
    landingUrl: '/en-nz/g/growing-sooo-fast-product/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/g/dont-stop-now-c-suite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-29/2bsw9z',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/de-de/g/hoeren-sie-jetzt-nicht-auf-c-suite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj4z',
    ctaCopy: 'Kontaktieren Sie uns',
    supportingCopy: 'Bereit Ihre Zahlungen mit GoCardless zu verbessern?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/fr-fr/g/e-vous-arretez-pas-en-si-bon-chemin-csuite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj68',
    ctaCopy: 'Parlons-en',
    supportingCopy: 'Prêt à améliorer vos paiements avec GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-us/g/dont-stop-now-c-suite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj6xSource_c=Contact%20Sales',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-au/g/dont-stop-now-c-suite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/en-nz/g/dont-stop-now-c-suite/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2021-09-30/2bxj72',
    ctaCopy: "We're standing by",
    supportingCopy: 'Ready to improve your payments with GoCardless?',
  },
  {
    pathFactory: 'cSuite',
    landingUrl: '/es-es/g/no-pare-ahora/',
    ctaLink: 'https://forms.gocardless.com/l/305971/2022-01-10/2wfx2p',
    ctaCopy: 'Estamos a la espera',
    supportingCopy: '¿Está listo para mejorar sus pagos con GoCardless?',
  },
];
