const urls = {
  '/en-gb/atlas-convertible-cot-toddler-bed-3-in-1-oak-effect/p/cbat65100': 'cotbed',
  '/en-gb/atlas-convertible-cot-toddler-bed-3-in-1-nimbus-white-wood/p/cbatay600': 'cotbed',
  '/en-gb/lawson-convertible-cot-toddler-bed-natural-white/p/cblwc6000': 'cotbed',
  '/en-gb/shipley-classic-convertible-cot-toddler-bed-white/p/cbsp98600': 'cotbed',
  '/en-gb/mia-classic-cot-package-with-storage-and-changer-top-pebble-grey-pine/p/pcmc46800': 'cotbed',
  '/en-gb/mia-classic-cot-package-with-storage-and-changer-top-ivory-pine/p/pcmc03300': 'cotbed',
  '/en-gb/mia-sleigh-cot-package-with-storage-and-changer-top-ivory-pine/p/pcms03300': 'cotbed',
  '/en-gb/mia-classic-convertible-cot-toddler-bed-ivory-wood/p/cbmc03300': 'cotbed',
  '/en-gb/franklin-convertible-cot-toddler-bed-3-in-1-grey-wash/p/cbfrx6600': 'cotbed',
  '/en-gb/brooke-pine-toddler-bed-ivory/p/tdwh02700': 'cotbed',
  '/en-gb/breeze-wooden-swinging-crib-for-baby-to-6-months-white-pine/p/crbz02700': 'cotbed',
  '/en-gb/finch-cottoddler-bed/p/cbfiu4800': 'cotbed',
  '/en-gb/mia-classic-wooden-adjustable-cot-ivory-pine/p/ctmc03300': 'cotbed',
  '/en-gb/petite-super-compact-cot-pebble-grey/p/ctpe46800': 'cotbed',
  '/en-gb/rocking-crib-ivory/p/crro03300': 'cotbed',
  '/en-gb/mia-sleigh-cot-to-toddler-bed-package-with-storage-and-changer-top-ivory-pine/p/pkms03300': 'cotbed',
  '/en-gb/mia-sleigh-cot-package-with-storage-and-changer-top-pebble-grey-pine/p/pcms46800': 'cotbed',
  '/en-gb/mia-sleigh-convertible-cot-toddler-bed-pebble-grey/p/cbms46800': 'cotbed',
  '/en-gb/oxford-wooden-cot-toddler-bed-with-storage-white/p/cbox02721': 'cotbed',
  '/en-gb/oxford-wooden-cot-toddler-bed-with-storage-grey/p/cbox46820': 'cotbed',
  '/en-gb/petite-compact-cot-for-baby-to-1-year-white-pine/p/ctpe02700': 'cotbed',
  '/en-gb/breeze-wooden-swinging-crib-for-baby-to-6-months-pebble-grey/p/crbz46800': 'cotbed',
  '/en-gb/mia-classic-cot-bed-package-with-storage-and-changer-top-pebble-grey/p/pkmc46800': 'cotbed',
  '/en-gb/mia-classic-convertible-cot-toddler-bed-pebble-grey/p/cbmc46800': 'cotbed',
  '/en-gb/mia-classic-wooden-adjustable-cot-pebble-grey-pine/p/ctmc46800': 'cotbed',
  '/en-gb/mia-sleigh-convertible-cot-ivory/p/cbms03300': 'cotbed',
  '/en-gb/mia-sleigh-adjustable-height-cot-ivory-pine/p/ctms03300': 'cotbed',
  '/en-gb/mia-sleigh-adjustable-height-cot-pebble-grey-pine/p/ctms46800': 'cotbed',
  '/en-gb/mia-sleigh-cot-to-toddler-bed-package-with-storage-and-changer-top-pebble-grey-pine/p/pkms46800': 'cotbed',
  '/en-gb/mia-sleigh-espresso-convertible-cot-dark-brown/p/cbmsd3300': 'cotbed',
  '/en-gb/heaton-cottoddler-bed/p/cbhe46800': 'cotbed',
  '/en-gb/pocket-sprung-dual-sided-cotbed-mattress/p/ppdumcb00': 'mattress',
  '/en-gb/anti-allergy-pocket-sprung-cotbed-mattress-with-temperature-control/p/ppatmcb00': 'mattress',
  '/en-gb/sprung-anti-allergy-and-temperature-regulating-cotbed-mattress/p/dsatmcb00': 'mattress',
  '/en-gb/essential-foam-support-baby-crib-mattress-with-cover/p/cfbsmcr00': 'mattress',
  '/en-gb/essential-foam-support-carrycot-mattress-with-cover/p/cfbsmcc00': 'mattress',
  '/en-gb/essential-foam-support-baby-moses-basket-mattress-with-cover/p/cfbsmmo00': 'mattress',
  '/en-gb/armadillo-carrycot-foam-quilted-mattress/p/cfbsmac00': 'mattress',
  '/en-gb/welcome-to-the-world-foam-moses-mattress/p/cfbsmwm00': 'mattress',
  '/en-gb/anti-allergy-cotbed-mattress-cover-with-thermo-plus/p/mcaamcb01': 'mattress',
  '/en-gb/silentnight-airstream-anti-allergy-and-temperature-regulating-cotbed-mattress/p/vlaamcb00': 'mattress',
  '/en-gb/basic-foam-support-cotbed-mattress-with-cover/p/bfbsmcb00': 'mattress',
  '/en-gb/basic-mattress-cover-medium-cot/p/mc00mmc00': 'mattress',
  '/en-gb/basic-foam-support-cot-mattress-with-cover/p/bfbsmmc00': 'mattress',
  '/en-gb/essential-foam-support-small-cot-mattress-with-cover/p/cfbsmsc00': 'mattress',
  '/en-gb/essential-sprung-cotbed-mattress/p/dsbsmcb00': 'mattress',
  '/en-gb/essentials-pocket-sprung-waterproof-cotbed-mattress-with-cover/p/ppbsmcb00 ': 'mattress',
}

// console.log(urls[window.location.pathname]);

export default urls;