const inGridContent = {

    // no7 searches
    '?searchTerm=mascara': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1896060/heroteaser_small/600/476/32532640e8ce83621174dd0dde427593/BU/no7-macaras-explained.jpg',
        title: 'No7 mascaras explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-mascaras-explained',
        classType: 'beauty',
    },
    '?searchTerm=no7%20mascara': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1896060/heroteaser_small/600/476/32532640e8ce83621174dd0dde427593/BU/no7-macaras-explained.jpg',
        title: 'No7 mascaras explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-mascaras-explained',
        classType: 'beauty',
    },
    '?searchTerm=No7%20mascara': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1896060/heroteaser_small/600/476/32532640e8ce83621174dd0dde427593/BU/no7-macaras-explained.jpg',
        title: 'No7 mascaras explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-mascaras-explained',
        classType: 'beauty',
    },

    /*'/beauty/makeup/eyes/mascara': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1896060/heroteaser_small/600/476/32532640e8ce83621174dd0dde427593/BU/no7-macaras-explained.jpg',
        title: 'No7 mascaras explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-mascaras-explained',
        classType: 'beauty',
    },*/
    '?searchTerm=serum': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2150590/heroteaser_small/600/476/6e56b0d0cf2ad9a64cfa828829d63258/pL/no7-inspiration-advice-find-your-perfect-no7-serum-hero-1360x502.jpg',
        title: 'Find the right No7 serum for you',
        link: 'https://www.boots.com/no7-inspiration-and-advice/find-your-perfect-no7-serum',
        classType: 'beauty',
    },
    '?searchTerm=no7%20serum': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2150590/heroteaser_small/600/476/6e56b0d0cf2ad9a64cfa828829d63258/pL/no7-inspiration-advice-find-your-perfect-no7-serum-hero-1360x502.jpg',
        title: 'Find the right No7 serum for you',
        link: 'https://www.boots.com/no7-inspiration-and-advice/find-your-perfect-no7-serum',
        classType: 'beauty',
    },
    '?searchTerm=No7%20serum': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2150590/heroteaser_small/600/476/6e56b0d0cf2ad9a64cfa828829d63258/pL/no7-inspiration-advice-find-your-perfect-no7-serum-hero-1360x502.jpg',
        title: 'Find the right No7 serum for you',
        link: 'https://www.boots.com/no7-inspiration-and-advice/find-your-perfect-no7-serum',
        classType: 'beauty',
    },
    /*'/beauty/skincare/facial-skincare/serum-and-treatments': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2150590/heroteaser_small/600/476/6e56b0d0cf2ad9a64cfa828829d63258/pL/no7-inspiration-advice-find-your-perfect-no7-serum-hero-1360x502.jpg',
        title: 'Find the right No7 serum for you',
        link: 'https://www.boots.com/no7-inspiration-and-advice/find-your-perfect-no7-serum',
        classType: 'beauty',
    },*/
    '?searchTerm=foundation': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1968626/heroteaser_small/600/476/e44f758016c7933e25d32688c79dae20/yV/no7-foundations-explained-hero.jpg',
        title: 'Find the right No7 foundation for you ',
        link: 'https://www.boots.com/no7-inspiration-and-advice/when-skincare-meets-makeup-discover-your-perfect-no7-foundation',
        classType: 'beauty',
    },
    '?searchTerm=no7%20foundation': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1968626/heroteaser_small/600/476/e44f758016c7933e25d32688c79dae20/yV/no7-foundations-explained-hero.jpg',
        title: 'Find the right No7 foundation for you ',
        link: 'https://www.boots.com/no7-inspiration-and-advice/when-skincare-meets-makeup-discover-your-perfect-no7-foundation',
        classType: 'beauty',
    },
    '?searchTerm=No7%20foundation': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1968626/heroteaser_small/600/476/e44f758016c7933e25d32688c79dae20/yV/no7-foundations-explained-hero.jpg',
        title: 'Find the right No7 foundation for you ',
        link: 'https://www.boots.com/no7-inspiration-and-advice/when-skincare-meets-makeup-discover-your-perfect-no7-foundation',
        classType: 'beauty',
    },
    /*'/beauty/makeup/face/foundation': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/1968626/heroteaser_small/600/476/e44f758016c7933e25d32688c79dae20/yV/no7-foundations-explained-hero.jpg',
        title: 'Find the right No7 foundation for you ',
        link: 'https://www.boots.com/no7-inspiration-and-advice/when-skincare-meets-makeup-discover-your-perfect-no7-foundation',
        classType: 'beauty',
    },*/
    '?searchTerm=skin%20paste': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2010668/heroteaser_small/600/476/698878d85669ffdafa46228620c122e7/PQ/no7-skinpaste-hero.jpg',
        title: 'No7 skin pastes explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-skin-pastes-explained-the-next-generation-of-face-masks',
        classType: 'beauty',
    },
    '?searchTerm=no7%20skin%20paste': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2010668/heroteaser_small/600/476/698878d85669ffdafa46228620c122e7/PQ/no7-skinpaste-hero.jpg',
        title: 'No7 skin pastes explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-skin-pastes-explained-the-next-generation-of-face-masks',
        classType: 'beauty',
    },
    '?searchTerm=No7%20skin%20paste': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2010668/heroteaser_small/600/476/698878d85669ffdafa46228620c122e7/PQ/no7-skinpaste-hero.jpg',
        title: 'No7 skin pastes explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-skin-pastes-explained-the-next-generation-of-face-masks',
        classType: 'beauty',
    },
    /*'/skincare/facial-skincare/masks/all-face-masks': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2010668/heroteaser_small/600/476/698878d85669ffdafa46228620c122e7/PQ/no7-skinpaste-hero.jpg',
        title: 'No7 skin pastes explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-skin-pastes-explained-the-next-generation-of-face-masks',
        classType: 'beauty',
    },*/
    '?searchTerm=face%20masks': {
        logo: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/2B4783578D0E82C6610500CED9E2DF6501DA87A8A0EDF22A943C9C506D1FE8B4.png?meta=/BO059---In-Grid-Content-Variation/no7.png',
        image: 'https://www.boots.com/resource/image/2010668/heroteaser_small/600/476/698878d85669ffdafa46228620c122e7/PQ/no7-skinpaste-hero.jpg',
        title: 'No7 skin pastes explained',
        link: 'https://www.boots.com/no7-inspiration-and-advice/no7-skin-pastes-explained-the-next-generation-of-face-masks',
        classType: 'beauty',
    },

    // acne clinic
    '?searchTerm=acne': {
        image: 'https://www.boots.com/resource/image/1281620/heroteaser_small/600/476/d2bdff13e162a371b9c99499e123ccd0/BA/inspiration-advice-beauty-skincare-skincare-causes-and-treatments-of-acne-hero-1360x502.jpg',
        title: 'Online Acne Clinic',
        link: 'https://www.boots.com/online/pharmacy-services/acne-online-clinic-service',
        classType: 'skincare',
        secondClass: 'pharmacy',
        subText: 'Get convenient access to prescription-only medicines to help treat acne',
    },
    '?searchTerm=spots': {
        image: 'https://www.boots.com/resource/image/1281620/heroteaser_small/600/476/d2bdff13e162a371b9c99499e123ccd0/BA/inspiration-advice-beauty-skincare-skincare-causes-and-treatments-of-acne-hero-1360x502.jpg',
        title: 'Online Acne Clinic',
        link: 'https://www.boots.com/online/pharmacy-services/acne-online-clinic-service',
        classType: 'skincare',
        secondClass: 'pharmacy',
        subText: 'Get convenient access to prescription-only medicines to help treat acne',
    },
    '?searchTerm=acne%20treatment': {
        image: 'https://www.boots.com/resource/image/1281620/heroteaser_small/600/476/d2bdff13e162a371b9c99499e123ccd0/BA/inspiration-advice-beauty-skincare-skincare-causes-and-treatments-of-acne-hero-1360x502.jpg',
        title: 'Online Acne Clinic',
        link: 'https://www.boots.com/online/pharmacy-services/acne-online-clinic-service',
        classType: 'skincare',
        secondClass: 'pharmacy',
        subText: 'Get convenient access to prescription-only medicines to help treat acne',
    },
    '/beauty/skincare/expert-skincare-/acne-prone-skin': {
        image: 'https://www.boots.com/resource/image/1281620/heroteaser_small/600/476/d2bdff13e162a371b9c99499e123ccd0/BA/inspiration-advice-beauty-skincare-skincare-causes-and-treatments-of-acne-hero-1360x502.jpg',
        title: 'Online Acne Clinic',
        link: 'https://www.boots.com/online/pharmacy-services/acne-online-clinic-service',
        classType: 'skincare',
        secondClass: 'pharmacy',
        subText: 'Get convenient access to prescription-only medicines to help treat acne',
    },

    // ED clinic
    '?searchTerm=sildenafil': {
        image: 'https://www.boots.com/resource/image/1321630/estore_sps_33/540/400/ee2966d41eba0dd9dcf720d1f82f8358/Cn/services-health-mens-health-erectile-dysfunction-online-clinic-onward-journey-50-33-25.jpg',
        title: 'Erectile Dysfunction Online Clinic',
        link: 'https://www.boots.com/online-clinics/erectile-dysfunction-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Discreet & confidential help with your erection problems'
    },
    '?searchTerm=condoms': {
        image: 'https://www.boots.com/resource/image/1321630/estore_sps_33/540/400/ee2966d41eba0dd9dcf720d1f82f8358/Cn/services-health-mens-health-erectile-dysfunction-online-clinic-onward-journey-50-33-25.jpg',
        title: 'Erectile Dysfunction Online Clinic',
        link: 'https://www.boots.com/online-clinics/erectile-dysfunction-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Discreet & confidential help with your erection problems'
    },
    '?searchTerm=lube': {
        image: 'https://www.boots.com/resource/image/1321630/estore_sps_33/540/400/ee2966d41eba0dd9dcf720d1f82f8358/Cn/services-health-mens-health-erectile-dysfunction-online-clinic-onward-journey-50-33-25.jpg',
        title: 'Erectile Dysfunction Online Clinic',
        link: 'https://www.boots.com/online-clinics/erectile-dysfunction-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Discreet & confidential help with your erection problems'
    },
    '?searchTerm=mens%20sexual%20health': {
        image: 'https://www.boots.com/resource/image/1321630/estore_sps_33/540/400/ee2966d41eba0dd9dcf720d1f82f8358/Cn/services-health-mens-health-erectile-dysfunction-online-clinic-onward-journey-50-33-25.jpg',
        title: 'Erectile Dysfunction Online Clinic',
        link: 'https://www.boots.com/online-clinics/erectile-dysfunction-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Discreet & confidential help with your erection problems'
    },
    '?searchTerm=sexual%20health': {
        image: 'https://www.boots.com/resource/image/1321630/estore_sps_33/540/400/ee2966d41eba0dd9dcf720d1f82f8358/Cn/services-health-mens-health-erectile-dysfunction-online-clinic-onward-journey-50-33-25.jpg',
        title: 'Erectile Dysfunction Online Clinic',
        link: 'https://www.boots.com/online-clinics/erectile-dysfunction-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Discreet & confidential help with your erection problems'
    },
    
    // mens hair loss
    '?searchTerm=hair%20loss': {
        image: 'https://www.boots.com/resource/image/387472/estore_sps_33/540/400/7d888549a88b8c8469c1a3c75dd5aa31/Yt/22369-hairlossformen-33-hairlossproducts-istock-1500.jpg',
        title: 'Hair Loss Online Clinic',
        link: 'https://www.boots.com/hairloss/hair-loss-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: `Prescription only hair loss treatment, subject to clinician approval. <span class="small">*for males aged 18 and over.
        </span>`,
    },
    '?searchTerm=hair%20thinning': {
        image: 'https://www.boots.com/resource/image/387472/estore_sps_33/540/400/7d888549a88b8c8469c1a3c75dd5aa31/Yt/22369-hairlossformen-33-hairlossproducts-istock-1500.jpg',
        title: 'Hair Loss Online Clinic',
        link: 'https://www.boots.com/hairloss/hair-loss-online-clinic',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: `Prescription only hair loss treatment, subject to clinician approval. <span class="small">*for males aged 18 and over.
        </span>`,
    },

    // repeat prescriptions
    '?searchTerm=acid%20reflux': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=inhaler': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=blood%20pressure': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=sleeping%20tablets': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=anxiety': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=heartburn': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=constipation': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },

    '?searchTerm=thermometer': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=vitamin%20c': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=digestive%20health': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=paracetamol': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=blood%20pressure%20monitor': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=thermometer%20digital': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=multivitamins': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=dual%20defence': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=sleep': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=eye%20drops': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
    '?searchTerm=gloves': {
        image: 'https://www.boots.com/resource/image/1059370/estore_sp_small/325/325/a5e3455056dc5cd6dbd224715d6a971/gb/health-pain-knee-pain-advice-onward-journey-50-33-25.jpg',
        title: 'Boots Online Prescription Service', 
        link: 'https://www.boots.com/online/pharmacy/',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Free Online NHS Repeat Prescription Service <span class="small">(prescription charges may apply)</span>',
    },
   

    // child vaccination
    '?searchTerm=baby%20child%20meds': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '/health-pharmacy/baby-child-health/skincare-conditions': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=baby%20wipes': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=baby%20food': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=baby%20oil': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=baby%20thermometer': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=baby%20milk': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=nurofen%20children': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=childrens%20multivitamins': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=childrens%20vitamins': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=multivitamins%20for%20kids': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    '?searchTerm=kids%20vitamins': {
        image: 'https://www.boots.com/resource/image/1232764/estore_sp_small/325/325/48e39dfc9033745002279cebfaaf9db8/tB/health-first-aid-first-aid-tips-for-adults-children-travel-onward-journey-50-33-25.jpg',
        title: 'Chickenpox Vaccination Service',
        link: 'https://www.boots.com/health-pharmacy-advice/vaccinations/chickenpox-vaccination-service',
        classType: 'child',
        secondClass: 'pharmacy',
        subText: 'Helping to offer protection against the chickenpox virus',
    },
    
   

    // online gp
    /*'/health-pharmacy/electrical-health-diagnostics/blood-pressure-monitors': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/5EDBE06B3D545A128B9F2F63684681AD8C73FEE53CE00588F99CE1FEC0057708.jpg?meta=/BO059---In-Grid-Content-Variation/livi-image---compressed1.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=yeast%20infection': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/5EDBE06B3D545A128B9F2F63684681AD8C73FEE53CE00588F99CE1FEC0057708.jpg?meta=/BO059---In-Grid-Content-Variation/livi-image---compressed1.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=urinary%20tract%20infection': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/5EDBE06B3D545A128B9F2F63684681AD8C73FEE53CE00588F99CE1FEC0057708.jpg?meta=/BO059---In-Grid-Content-Variation/livi-image---compressed1.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=sleeping%20tablets': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/5EDBE06B3D545A128B9F2F63684681AD8C73FEE53CE00588F99CE1FEC0057708.jpg?meta=/BO059---In-Grid-Content-Variation/livi-image---compressed1.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=stomach%20pain': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/5EDBE06B3D545A128B9F2F63684681AD8C73FEE53CE00588F99CE1FEC0057708.jpg?meta=/BO059---In-Grid-Content-Variation/livi-image---compressed1.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=blood%20pressure%20monitor%20upper%20arm': {
        image: 'https://www.boots.com/resource/image/2410050/heroteaser_small/600/476/55ad881721063a408399bfb496bede42/yu/services-health-and-pharmacy-gp-online-doctor-hero-v4.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=compression': {
        image: 'https://www.boots.com/resource/image/2410050/heroteaser_small/600/476/55ad881721063a408399bfb496bede42/yu/services-health-and-pharmacy-gp-online-doctor-hero-v4.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=muscle%20pain%20relief': {
        image: 'https://www.boots.com/resource/image/2410050/heroteaser_small/600/476/55ad881721063a408399bfb496bede42/yu/services-health-and-pharmacy-gp-online-doctor-hero-v4.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },
    '?searchTerm=back%20pain%20relief': {
        image: 'https://www.boots.com/resource/image/2410050/heroteaser_small/600/476/55ad881721063a408399bfb496bede42/yu/services-health-and-pharmacy-gp-online-doctor-hero-v4.jpg',
        title: 'See a GP by video',
        subText: 'Get an online consultation with Livi for <b>£19</b>',
        link: 'https://www.boots.com/health-pharmacy-advice/video-services/online-gp',
        classType: 'health',
        secondClass: 'pharmacy',
    },*/


    // vitamin D
    '?searchTerm=immunity%20support': {
        image: 'https://www.boots.com/resource/image/2274384/heroteaser_small/600/476/2ff4ab1ca965a773ffbfbe8267ad504d/ld/health-vitamins-and-minerals-vitamin-d-advice-hero-1360x502.jpg',
        title: 'What is vitamin D?',
        link: 'https://www.boots.com/key-vitamins-and-minerals/vitamin-d-advice',
        classType: 'health',
        subText: 'We give you the lowdown on the sunshine vitamin',
    },
    '?searchTerm=immunity%20vitamins': {
        image: 'https://www.boots.com/resource/image/2274384/heroteaser_small/600/476/2ff4ab1ca965a773ffbfbe8267ad504d/ld/health-vitamins-and-minerals-vitamin-d-advice-hero-1360x502.jpg',
        title: 'What is vitamin D?',
        link: 'https://www.boots.com/key-vitamins-and-minerals/vitamin-d-advice',
        classType: 'health',
        subText: 'We give you the lowdown on the sunshine vitamin',
    },
    '?searchTerm=vitamin%20d': {
        image: 'https://www.boots.com/resource/image/2274384/heroteaser_small/600/476/2ff4ab1ca965a773ffbfbe8267ad504d/ld/health-vitamins-and-minerals-vitamin-d-advice-hero-1360x502.jpg',
        title: 'What is vitamin D?',
        link: 'https://www.boots.com/key-vitamins-and-minerals/vitamin-d-advice',
        classType: 'health',
        subText: 'We give you the lowdown on the sunshine vitamin',
    },

    // diet & weight loss
    '?searchTerm=weight%20loss%20tablets': {
        image: 'https://www.boots.com/resource/image/2179548/heroteaser_small/600/476/a345ef496c8ed626ddc407880a38913a/ux/health-diabetes-diabetes-hub-hero-1360x502.jpg',
        title: 'Diabetes online risk assessment',
        link: 'https://www.boots.com/health-pharmacy-advice/health-checks/diabetesrisk',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Find out your risk of developing Type 2 diabetes in the next 10 years',
    },
    '?searchTerm=diet%20tablets': {
        image: 'https://www.boots.com/resource/image/2179548/heroteaser_small/600/476/a345ef496c8ed626ddc407880a38913a/ux/health-diabetes-diabetes-hub-hero-1360x502.jpg',
        title: 'Diabetes online risk assessment',
        link: 'https://www.boots.com/health-pharmacy-advice/health-checks/diabetesrisk',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Find out your risk of developing Type 2 diabetes in the next 10 years',
    },
    '?searchTerm=diet%20shakes': {
        image: 'https://www.boots.com/resource/image/2179548/heroteaser_small/600/476/a345ef496c8ed626ddc407880a38913a/ux/health-diabetes-diabetes-hub-hero-1360x502.jpg',
        title: 'Diabetes online risk assessment',
        link: 'https://www.boots.com/health-pharmacy-advice/health-checks/diabetesrisk',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Find out your risk of developing Type 2 diabetes in the next 10 years',
    },
    '?searchTerm=meal%20replacement': {
        image: 'https://www.boots.com/resource/image/2179548/heroteaser_small/600/476/a345ef496c8ed626ddc407880a38913a/ux/health-diabetes-diabetes-hub-hero-1360x502.jpg',
        title: 'Diabetes online risk assessment',
        link: 'https://www.boots.com/health-pharmacy-advice/health-checks/diabetesrisk',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Find out your risk of developing Type 2 diabetes in the next 10 years',
    },
    '?searchTerm=scholl%20footcare': {
        image: 'https://www.boots.com/resource/image/2179548/heroteaser_small/600/476/a345ef496c8ed626ddc407880a38913a/ux/health-diabetes-diabetes-hub-hero-1360x502.jpg',
        title: 'Diabetes online risk assessment',
        link: 'https://www.boots.com/health-pharmacy-advice/health-checks/diabetesrisk',
        classType: 'health',
        secondClass: 'pharmacy',
        subText: 'Find out your risk of developing Type 2 diabetes in the next 10 years',
    },

    // nail infection
    '?searchTerm=fungal%20nail': {
        image: 'https://www.boots.com/resource/image/1794948/estore_sp_small/325/325/3263752d22d614b4c17bb96c56b90df3/GP/health-footcare-footcare-hub-onward-journey-50-33-25.jpg',
        title: 'Treating fungal nail infection',
        link: 'https://www.boots.com/nail-problems/toenail-fungus',
        classType: 'health',
        subText: "Learn about how it's caused and how it can be treated",
    },
    '?searchTerm=nail%20infection': {
        image: 'https://www.boots.com/resource/image/1794948/estore_sp_small/325/325/3263752d22d614b4c17bb96c56b90df3/GP/health-footcare-footcare-hub-onward-journey-50-33-25.jpg',
        title: 'Treating fungal nail infection',
        link: 'https://www.boots.com/nail-problems/toenail-fungus',
        classType: 'health',
        subText: "Learn about how it's caused and how it can be treated",
    },
    '?searchTerm=nail%20fungus': {
        image: 'https://www.boots.com/resource/image/1794948/estore_sp_small/325/325/3263752d22d614b4c17bb96c56b90df3/GP/health-footcare-footcare-hub-onward-journey-50-33-25.jpg',
        title: 'Treating fungal nail infection',
        link: 'https://www.boots.com/nail-problems/toenail-fungus',
        classType: 'health',
        subText: "Learn about how it's caused and how it can be treated",
    },
    '/health-pharmacy/medicines-treatments/footcare/fungal-nail-infection': {
        image: 'https://www.boots.com/resource/image/1794948/estore_sp_small/325/325/3263752d22d614b4c17bb96c56b90df3/GP/health-footcare-footcare-hub-onward-journey-50-33-25.jpg',
        title: 'Treating fungal nail infection',
        link: 'https://www.boots.com/nail-problems/toenail-fungus',
        classType: 'health',
        subText: "Learn about how it's caused and how it can be treated",
    },

    /*'?searchTerm=rosacea': {
        image: 'https://www.boots.com/resource/image/1939350/heroteaser_small/600/476/4d888c30f846fb562a67f636c73797a8/Rz/health-skincare-skincare-hub-hero-1360x502.jpg',
        title: 'Rosacea advice', 
        link: 'https://www.boots.com/other-skin-conditions/rosacea-advice',
        classType: 'skincare',
        subText: "Helpful advice, information & treatment options for Rosacea",
    },
    '?searchTerm=red%20skin': {
        image: 'https://www.boots.com/resource/image/1939350/heroteaser_small/600/476/4d888c30f846fb562a67f636c73797a8/Rz/health-skincare-skincare-hub-hero-1360x502.jpg',
        title: 'Rosacea advice', 
        link: 'https://www.boots.com/other-skin-conditions/rosacea-advice',
        classType: 'skincare',
        subText: "Helpful advice, information & treatment options for Rosacea",
    },*/
    '?searchTerm=anti%20redness': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/54AE54C6A3486789D4BC41ADC8F1D06ABC7DDA2E751BC5D77F0CBFB163DC5EA3.jpg?meta=/BO059---In-Grid-Content-Variation-Pharma/rosacea.jpg',
        title: 'Rosacea advice', 
        link: 'https://www.boots.com/other-skin-conditions/rosacea-advice',
        classType: 'skincare',
        secondClass: 'redness',
        subText: "Helpful advice, information & treatment options for Rosacea",
    },
    '/health-pharmacy/medicines-treatments/skin-problems/rosacea-treatments': {
        image: 'https://service.maxymiser.net/cm/images-eu/new-boots-com/54AE54C6A3486789D4BC41ADC8F1D06ABC7DDA2E751BC5D77F0CBFB163DC5EA3.jpg?meta=/BO059---In-Grid-Content-Variation-Pharma/rosacea.jpg',
        title: 'Rosacea advice', 
        link: 'https://www.boots.com/other-skin-conditions/rosacea-advice',
        classType: 'skincare',
        secondClass: 'redness',
        subText: "Helpful advice, information & treatment options for Rosacea",
    },

    
}

export default inGridContent;