export default {
  // "/glitterbels-loose-glitter-15g" : {
  //   brand: "<span class='brand'>Glitterbels</span>",
  //   prodName: "Loose Glitter 15g",
  //   prodCat: "In Acrylic Nail Kits",
  // },
  // "/shrine-drop-it-hair-drops-20ml" : {
  //   brand: "<span class='brand'>Shrine</span>",
  //   prodName: "Drop It Hair Drops 20ml",
  //   prodCat: "In Acrylic Nail Kits",
  // },
  // "/schwarzkopf-igora-royal-absolutes-60ml" : {
  //   brand: "<span class='brand'>Schwarzkopf</span>",
  //   prodName: "Igora Royal Absolutes 60ml",
  //   prodCat: "In Acrylic Nail Kits",
  // },


  "/gama-iq-perfetto-hairdryer" : {
    brandName: "Gama iQ",
    catName: "Professional Hair Dryers &amp; Diffusers",
    mainCat: "/hair/electricals/hairdryers-and-diffusers",
    brandCat: "",
    brand: "<span class='brand'>Gama iQ</span>",
    prodName: "Perfetto Hairdryer",
    prodCat: "<a href='/hair/electricals/hairdryers-and-diffusers'>In Professional Hair Dryers & Diffusers</a>",
  },
  "/glitterbels-acrylic-starter-kit" : {
    brandName: "Glitterbels",
    catName: "Nail Extensions",
    mainCat: "/nails/nail-extensions",
    brandCat: "/brands/glitterbels",
    brand: "<span class='brand'><a href='/brands/glitterbels'>Glitterbels</a></span>",
    prodName: "Acrylic Starter Kit",
    prodCat: "<a href='/nails/nail-extensions'>In Nail Extensions</a>",
  },
  "/olaplex-self-care-bundle-deal" : {
    brandName: "Olaplex",
    catName: "Shampoo, Conditioner &amp; Hair Masks",
    mainCat: "/hair/hair-care-perming/shampoo-conditioner-and-masks",
    brandCat: "/brands/olaplex",
    brand: "<span class='brand'><a href='/brands/olaplex'>Olaplex</a></span>",
    prodName: "Self Care Bundle Deal ",
    prodCat: "<a href='/hair/hair-care-perming/shampoo-conditioner-and-masks'>In Shampoo, Conditioner &amp; Hair Masks</a>",
  },
  "/pulp-riot-high-speed-toner-90ml" : {
    brandName: "Pulp Riot",
    catName: "Permanent Hair Colour",
    mainCat: "/hair-colour/permanent-colour",
    brandCat: "/hair-colour/permanent-colour/pulp-riot-faction8",
    brand: "<span class='brand'><a href='/hair-colour/permanent-colour/pulp-riot-faction8'>Pulp Riot</a></span>",
    prodName: "High Speed Toner 90ml",
    prodCat: "<a href='/hair-colour/permanent-colour'>In Permanent Hair Colour</a>",
  },
  "/glitterbels-core-acrylic-powder" : {
    brandName: "Glitterbels",
    catName: "Acrylic Nail Powders",
    mainCat: "/nails/nail-extensions/acrylic-powders",
    brandCat: "/brands/glitterbels",
    brand: "<span class='brand'><a href='/brands/glitterbels'>Glitterbels</a></span>",
    prodName: "Core Acrylic Powder",
    prodCat: "<a href='/nails/nail-extensions/acrylic-powders'>In Acrylic Nail Powders</a>",
  },
  "/redken-shades-eq-gloss-60ml" : {
    brandName: "Redken",
    catName: "Semi Permanent Hair Colour",
    mainCat: "/hair-colour/semi-permanent-colour",
    brandCat: "/brands/redken-eq-shades",
    brand: "<span class='brand'><a href='/brands/redken-eq-shades'>Redken</a></span>",
    prodName: "Shades EQ Gloss 60ml",
    prodCat: "<a href='/hair-colour/semi-permanent-colour'>In Semi Permanent Hair Colour</a>",
  },
  "/glitterbels-coloured-acrylic-powder-28g" : {
    brandName: "Glitterbels",
    catName: "Acrylic Nail Powders",
    mainCat: "/nails/nail-extensions/acrylic-powders",
    brandCat: "/brands/glitterbels",
    brand: "<span class='brand'><a href='/brands/glitterbels'>Glitterbels</a></span>",
    prodName: "Coloured Acrylic Powder 28g",
    prodCat: "<a href='/nails/nail-extensions/acrylic-powders'>In Acrylic Nail Powders</a>",
  },
  "/wella-koleston-perfect-me-60ml" : {
    brandName: "Wella Koleston Perfect",
    catName: "Permanent Hair Colour",
    mainCat: "/hair-colour/permanent-colour",
    brandCat: "/brands/wella-koleston-perfect",
    brand: "<span class='brand'><a href='/brands/wella-koleston-perfect'>Wella Koleston Perfect</a></span>",
    prodName: "Me+ 60ml",
    prodCat: "<a href='/hair-colour/permanent-colour'>In Permanent Hair Colour</a>",
  },
  "/babyliss-pro-cordless-skeleton-trimmer" : {
    brandName: "BaByliss PRO",
    catName: "Shaving Razors",
    mainCat: "/barbering/shaving-razors",
    brandCat: "/barbering/top-brands/babyliss-pro",
    brand: "<span class='brand'><a href='/barbering/top-brands/babyliss-pro'>BaByliss PRO</a></span>",
    prodName: "Cordless Skeleton Trimmer",
    prodCat: "<a href='/barbering/shaving-razors'>In Shaving Razors</a>",
  },
  "/pulp-riot-semi-permanent-hair-color-118ml" : {
    brandName: "Pulp Riot",
    catName: "Semi Permanent Hair Colour",
    mainCat: "/hair-colour/semi-permanent-colour",
    brandCat: "/hair-colour/semi-permanent-colour/pulp-riot",
    brand: "<span class='brand'><a href='/hair-colour/semi-permanent-colour/pulp-riot'>Pulp Riot</a></span>",
    prodName: "Semi-Permanent Hair color 118ml",
    prodCat: "<a href='/hair-colour/semi-permanent-colour'>In Semi Permanent Hair Colour</a>",
  },
  "/glitterbels-pre-mixed-glitter-acrylic-powder-28g" : {
    brandName: "Glitterbels",
    catName: "Acrylic Nail Powders",
    mainCat: "/nails/nail-extensions/acrylic-powders",
    brandCat: "/brands/glitterbels",
    brand: "<span class='brand'><a href='/brands/glitterbels'>Glitterbels</a></span>",
    prodName: "Pre Mixed Glitter Acrylic Powder 28g",
    prodCat: "<a href='/nails/nail-extensions/acrylic-powders'>In Acrylic Nail Powders</a>",
  },
  "/glitterbels-clear-pinched-square-assorted-nail-tips-x-500" : {
    brandName: "Glitterbels",
    catName: "Acrylic Nail Tips",
    mainCat: "/nails/nail-extensions/acrylic-nail-tips",
    brandCat: "/brands/glitterbels",
    brand: "<span class='brand'><a href='/brands/glitterbels'>Glitterbels</a></span>",
    prodName: "Clear Pinched Square Assorted Nail Tips x 500",
    prodCat: "<a href='/nails/nail-extensions/acrylic-nail-tips'>In Acrylic Nail Tips</a>",
  },
  "/l-oreal-majirel-50ml-1" : {
    brandName: "L'Oreal",
    catName: "Permanent Hair Colour",
    mainCat: "/hair-colour/permanent-colour",
    brandCat: "/hair-colour/permanent-colour/l-oreal-majirel",
    brand: "<span class='brand'><a href='/hair-colour/permanent-colour/l-oreal-majirel'>L'Oreal</a></span>",
    prodName: "Majirel 50ml",
    prodCat: "<a href='/hair-colour/permanent-colour'>In Permanent Hair Colour</a>",
  },
  "/wella-blondor-multi-blonde-powder-400g" : {
    brandName: "Wella Blondor",
    catName: "Hair Bleach",
    mainCat: "/hair-colour/bleach-foil/bleach",
    brandCat: "/hair-colour/hair-colour-brands/wella-professionals",
    brand: "<span class='brand'><a href='/hair-colour/hair-colour-brands/wella-professionals'>Wella Blondor</a></span>",
    prodName: "Multi Blonde Powder 400g",
    prodCat: "<a href='/hair-colour/bleach-foil/bleach'>In Hair Bleach</a>",
  },
  "/olaplex-salon-intro-kit" : {
    brandName: "Olaplex",
    catName: "",
    mainCat: "",
    brandCat: "/brands/olaplex",
    brand: "<span class='brand'><a href='/brands/olaplex'>Olaplex</a></span>",
    prodName: "Salon Intro Kit",
    prodCat: "",
  },
  "/wella-color-touch-60ml" : {
    brandName: "Wella",
    catName: "Semi Permanent Hair Colour",
    mainCat: "/hair-colour/semi-permanent-colour",
    brandCat: "/hair-colour/semi-permanent-colour/wella-color-touch-1",
    brand: "<span class='brand'><a href='/hair-colour/semi-permanent-colour/wella-color-touch-1'>Wella</a></span>",
    prodName: "Color Touch 60ml",
    prodCat: "<a href='/hair-colour/semi-permanent-colour'>In Semi Permanent Hair Colour</a>",
  },
  // "" : {
  //   brand: "<span class='brand'><a href=''> </a></span>",
  //   prodName: "",
  //   prodCat: "<a href=''> </a>",
  // },
};