export const brandImgData = [
  {
    title: 'Drilling',
    brandProducts: [
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Bosch.png',
        href: '/c/tools/drilling/cat5920002?brand=bosch',
        frame: 'bosch_frame',
        brandAlt: 'Bosch',
        border: 'bosch_border',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Erbauer.png',
        href: '/c/tools/drilling/cat5920002?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'dewalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Dewalt.png',
        href: '/c/tools/drilling/cat5920002?brand=dewalt',
        frame: 'dewalt_frame',
        brandAlt: 'DeWalt',
        border: 'dewalt_border',
      },
      {
        title: 'essentials',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Essentials.png',
        href: '/c/tools/drilling/cat5920002?brand=essentials',
        frame: 'essentials_frame',
        brandAlt: 'Armeg',
        border: 'essentials_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Makita.png',
        href: '/c/tools/drilling/cat5920002?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Drilling_Milwaukee.png',
        href: '/c/tools/drilling/cat5920002?brand=milwaukee',
        frame: 'milwaukee_frame',
        brandAlt: 'Milwaukee',
        border: 'milwaukee_border',
      },
    ],
  },
  {
    title: 'Screwdriver Bits',
    brandProducts: [
      {
        title: 'wera',
        imgSrc: 'https://media.screwfix.com/is/image/ae235/232FP_P?$fxSharpen$=&wid=257&hei=257&dpr=on',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=wera',
        frame: 'wera_frame',
        brandAlt: 'Wera',
        border: 'wera_border',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/screwdriver_bits_eubauer.png',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'dewalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/screwdriver_bits_dewalt.png',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=dewalt',
        frame: 'dewalt_frame',
        brandAlt: 'DeWalt',
        border: 'dewalt_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/screwdriver_bits_Makita.png',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/screwdriver_bits_milwaukee.png',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=milwaukee',
        frame: 'milwaukee_frame',
        brandAlt: 'Milwaukee',
        border: 'milwaukee_border',
      },
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/screwdriver_bits_Bosch.png',
        href: '/c/tools/screwdriver-bits/cat5970004?brand=bosch',
        frame: 'bosch_frame',
        brandAlt: 'Bosch',
        border: 'bosch_border',
      },
    ],
  },
  {
    title: 'Cutting & Blades',
    brandProducts: [
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Cutting_&_blades_Bosch.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=bosch',
        frame: 'bosch_frame',
        brandAlt: 'Bosch',
        border: 'bosch_border',
      },
      {
        title: 'freud',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/ccutting_&_blades_freud.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=freud',
        frame: 'freud_frame',
        brandAlt: 'Freud',
        border: 'freud_border',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/cutting_&_blades_erbauer.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/cutting_&_blades_makita.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },
      {
        title: 'dewalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/cutting_&_blades_dewalt.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=dewalt',
        frame: 'dewalt_frame',
        brandAlt: 'DeWalt',
        border: 'dewalt_border',
      },
      {
        title: 'trend',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/cutting_&_saving_trend.png',
        href: '/c/tools/cutting-blades/cat5970020?brand=trend',
        frame: 'trend_frame',
        brandAlt: 'Trend',
        border: 'trend_border',
      },
    ],
  },
  {
    title: 'Multi Tool Accessories',
    brandProducts: [
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Multi_tool_bosch.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=bosch',
        frame: 'bosch_frame',
        brandAlt: 'Bosch',
        border: 'bosch_border',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Multi_tool_Erbauer.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'dremel',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Multi_tool_Dremel.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=dremel',
        frame: 'dremel_frame',
        brandAlt: 'Dremel',
        border: 'dremel_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Multi_tool_Makita.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },
      {
        title: 'dewalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Multi_Tool_dewalt.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=dewalt',
        frame: 'dewalt_frame',
        brandAlt: 'DeWalt',
        border: 'dewalt_border',
      },
      {
        title: 'toolpak',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/multi_tool_toolpak.png',
        href: '/c/tools/multi-tool-accessories/cat6160058?brand=toolpak',
        frame: 'toolpak_frame',
        brandAlt: 'Toolpak',
        border: 'toolpak_border',
      },
    ],
  },
  {
    title: 'Angle Grinder Discs',
    brandProducts: [
      {
        title: 'essentials',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_grinder_discs_essentials.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=essentials',
        frame: 'essentials_frame',
        brandAlt: 'Armeg',
        border: 'essentials_border',
      },
      {
        title: 'norton',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_grinder_dremel.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=norton',
        frame: 'norton_frame',
        brandAlt: 'Norton',
        border: 'norton_border',
      },
      {
        title: 'flex',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_Grinder_flex.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=flex',
        frame: 'erbauer_frame',
        brandAlt: 'Flex',
        border: 'erbauer_border',
      },
      {
        title: 'marcrist',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_grinder_Marcrist.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=marcrist',
        frame: 'marcrist_frame',
        brandAlt: '',
        border: 'marcrist_border',
      },
      {
        title: 'dremel',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_grinder_dremel.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=dremel',
        frame: 'dremel_frame',
        brandAlt: 'Dremel',
        border: 'dremel_border',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Angle_grinder_Erbauer.png',
        href: '/c/tools/angle-grinder-discs/cat5990032?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
    ],
  },
  {
    title: 'Sanding',
    brandProducts: [
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_Bosch.png',
        href: '/c/tools/sanding/cat6270002?brand=bosch',
        frame: 'bosch_frame',
        brandAlt: 'Bosch',
        border: 'bosch_border',
      },
      {
        title: 'flexovit',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_Flexovit.png',
        href: '/c/tools/sanding/cat6270002?brand=flexovit',
        frame: 'flexovit_frame',
        brandAlt: 'Flexovit',
        border: 'flexovit_border',
      },
      {
        title: 'essentials',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_essentials.png',
        href: '/c/tools/sanding/cat6270002?brand=essentials',
        frame: 'essentials_frame',
        brandAlt: 'Armeg',
        border: 'essentials_border',
      },
      {
        title: 'festool',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_Festool.png',
        href: '/c/tools/sanding/cat6270002?brand=festool',
        frame: 'festool_frame',
        brandAlt: 'Festool',
        border: 'festool_border',
      },
      {
        title: 'titan',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_Titan.png',
        href: '/c/tools/sanding/cat6270002?brand=titan',
        frame: 'titan_frame',
        brandAlt: 'Titan',
        border: 'titan_border',
      },
      {
        title: 'norton',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Sanding_Norton.png',
        href: '/c/tools/sanding/cat6270002?brand=norton',
        frame: 'norton_frame',
        brandAlt: 'Norton',
        border: 'norton_border',
      },
    ],
  },
  {
    title: 'Routing',
    brandProducts: [
      {
        title: 'trend',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Routing_trend.png',
        href: '/c/tools/routing/cat5990014?brand=trend',
        frame: 'trend_frame',
        brandAlt: 'Trend',
        border: 'trend_border',
      },
      {
        title: 'freud',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Routing_freud.jpeg',
        href: '/c/tools/routing/cat5990014?brand=freud',
        frame: 'freud_frame',
        brandAlt: 'Freud',
        border: 'freud_border',
      },
      {
        title: 'erbauer',
        imgSrc: '',
        href: '/c/tools/routing/cat5990014?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'festool',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Routing_Festool.png',
        href: '/c/tools/routing/cat5990014?brand=erbauer',
        frame: 'festool_frame',
        brandAlt: 'Festool',
        border: 'festool_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Routing_Makita.png',
        href: '/c/tools/routing/cat5990014?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },

      {
        title: 'unika',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Routing_Unika.png',
        href: '/c/tools/routing/cat5990014?brand=unikax',
        frame: 'unika_frame',
        brandAlt: 'Unika',
        border: 'unika_border',
      },
    ],
  },
  {
    title: 'Paddle Mixers',
    brandProducts: [
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Paddle_mixers_Erbauer.png',
        href: '/c/tools/paddle-mixers/cat6160074?brand=erbauer',
        frame: 'erbauer_frame',
        brandAlt: 'Erbauer',
        border: 'erbauer_border',
      },
      {
        title: 'berg',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/Paddle_mixer_Berg.png',
        href: '/c/tools/paddle-mixers/cat6160074?brand=berg',
        frame: 'berg_frame',
        brandAlt: 'Berg',
        border: 'berg_border',
      },
      {
        title: 'dewalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/paddle_mixer_Dewalt.png',
        href: '/c/tools/paddle-mixers/cat6160074?brand=dewalt',
        frame: 'dewalt_frame',
        brandAlt: 'DeWalt',
        border: 'dewalt_border',
      },
      {
        title: 'scheppach',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/paddle_mixer_scheppach.png',
        href: '/c/tools/paddle-mixers/cat6160074?brand=scheppach',
        frame: 'scheppach_frame',
        brandAlt: 'Scheppach',
        border: 'scheppach_border',
      },
      {
        title: 'tecmix',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/paddle_mixers_tecmix.jpeg',
        href: '/c/tools/paddle-mixers/cat6160074?brand=tecmix',
        frame: 'tecmix_frame',
        brandAlt: 'Tecmix',
        border: 'tecmix_border',
      },
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR029/paddle_mixers_makita.png',
        href: '/c/tools/paddle-mixers/cat6160074?brand=makita',
        frame: 'makita_frame',
        brandAlt: 'Makita',
        border: 'makita_border',
      },
    ],
  },
];
