export const bootLists = [
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "4",
    SKU: "9367D",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-4/9367d",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "5",
    SKU: "1654D",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-5/1654d",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "6",
    SKU: "6209D",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-6/6209d",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "7",
    SKU: "87720",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-7/87720",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "8",
    SKU: "84661",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-8/84661",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "9",
    SKU: "64632",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-9/64632",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "10",
    SKU: "71321",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-10/71321",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "11",
    SKU: "50328",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-11/50328",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "12",
    SKU: "42072",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-12/42072",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "13",
    SKU: "9944G",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-13/9944g",
  },
  {
    ProductName: "DeWalt Bolster Safety Boots Honey",
    Size: "14",
    SKU: "8929G",
    URL: "/p/dewalt-bolster-safety-boots-honey-size-14/8929g",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "7",
    SKU: "8168V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-7/8168v",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "8",
    SKU: "4842V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-8/4842v",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "9",
    SKU: "7001V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-9/7001v",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "10",
    SKU: "2448V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-10/2448v",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "11",
    SKU: "3301V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-11/3301v",
  },
  {
    ProductName: "DeWalt Phoenix Safety Boots Tan",
    Size: "12",
    SKU: "4061V",
    URL: "/p/dewalt-phoenix-safety-boots-tan-size-12/4061v",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "7",
    SKU: "657JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-7/657jj",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "8",
    SKU: "201JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-8/201jj",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "9",
    SKU: "534JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-9/534jj",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "10",
    SKU: "313JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-10/313jj",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "11",
    SKU: "665JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-11/665jj",
  },
  {
    ProductName: "DeWalt Hadley Safety Boots Brown",
    Size: "12",
    SKU: "277JJ",
    URL: "/p/dewalt-hadley-safety-boots-brown-size-12/277jj",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "7",
    SKU: "74561",
    URL: "/p/dewalt-recip-safety-boots-black-size-7/74561",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "8",
    SKU: "99679",
    URL: "/p/dewalt-recip-safety-boots-black-size-8/99679",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "9",
    SKU: "58579",
    URL: "/p/dewalt-recip-safety-boots-black-size-9/58579",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "10",
    SKU: "94428",
    URL: "/p/dewalt-recip-safety-boots-black-size-10/94428",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "11",
    SKU: "80923",
    URL: "/p/dewalt-recip-safety-boots-black-size-11/80923",
  },
  {
    ProductName: "DeWalt Recip Safety Boots Black",
    Size: "12",
    SKU: "45915",
    URL: "/p/dewalt-recip-safety-boots-black-size-12/45915",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "7",
    SKU: "89529",
    URL: "/p/site-onyx-safety-boots-black-size-7/89529",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "8",
    SKU: "48132",
    URL: "/p/site-onyx-safety-boots-black-size-8/48132",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "9",
    SKU: "98660",
    URL: "/p/site-onyx-safety-boots-black-size-9/98660",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "10",
    SKU: "73569",
    URL: "/p/site-onyx-safety-boots-black-size-10/73569",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "11",
    SKU: "72944",
    URL: "/p/site-onyx-safety-boots-black-size-11/72944",
  },
  {
    ProductName: "Site Onyx Safety Boots Black",
    Size: "12",
    SKU: "37142",
    URL: "/p/site-onyx-safety-boots-black-size-12/37142",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "7",
    SKU: "4454V",
    URL: "/p/site-fortress-safety-boots-black-size-7/4454v",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "8",
    SKU: "9604V",
    URL: "/p/site-fortress-safety-boots-black-size-8/9604v",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "9",
    SKU: "8452V",
    URL: "/p/site-fortress-safety-boots-black-size-9/8452v",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "10",
    SKU: "2219V",
    URL: "/p/site-fortress-safety-boots-black-size-10/2219v",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "11",
    SKU: "6015V",
    URL: "/p/site-fortress-safety-boots-black-size-11/6015v",
  },
  {
    ProductName: "Site Fortress   Safety Boots Black",
    Size: "12",
    SKU: "5330V",
    URL: "/p/site-fortress-safety-boots-black-size-12/5330v",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "7",
    SKU: "7645T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-7/7645t",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "8",
    SKU: "8405T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-8/8405t",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "9",
    SKU: "3180T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-9/3180t",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "10",
    SKU: "1409T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-10/1409t",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "11",
    SKU: "3987T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-11/3987t",
  },
  {
    ProductName: "DeWalt Pro-Lite Comfort   Safety Boots Brown",
    Size: "12",
    SKU: "7827T",
    URL: "/p/dewalt-pro-lite-comfort-safety-boots-brown-size-12/7827t",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "7",
    SKU: "2726P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-7/2726p",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "8",
    SKU: "5896P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-8/5896p",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "9",
    SKU: "3045P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-9/3045p",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "10",
    SKU: "6965P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-10/6965p",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "11",
    SKU: "9769P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-11/9769p",
  },
  {
    ProductName: "DeWalt Hydrogen Safety Boots Tan",
    Size: "12",
    SKU: "5206P",
    URL: "/p/dewalt-hydrogen-safety-boots-tan-size-12/5206p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "7",
    SKU: "9147P",
    URL: "/p/site-savannah-safety-boots-tan-size-7/9147p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "8",
    SKU: "3517P",
    URL: "/p/site-savannah-safety-boots-tan-size-8/3517p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "9",
    SKU: "8699P",
    URL: "/p/site-savannah-safety-boots-tan-size-9/8699p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "10",
    SKU: "7844P",
    URL: "/p/site-savannah-safety-boots-tan-size-10/7844p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "11",
    SKU: "3412P",
    URL: "/p/site-savannah-safety-boots-tan-size-11/3412p",
  },
  {
    ProductName: "Site Savannah Safety Boots Tan",
    Size: "12",
    SKU: "6853P",
    URL: "/p/site-savannah-safety-boots-tan-size-12/6853p",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "3",
    SKU: "594VG",
    URL: "/p/scruffs-switchback-ladies-safety-boots-tan-size-3/594vg",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "4",
    SKU: "-",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "5",
    SKU: "-",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "6",
    SKU: "-",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "7",
    SKU: "299KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-7/299kh",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "8",
    SKU: "382KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-8/382kh",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "9",
    SKU: "950KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-9/950kh",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "10",
    SKU: "902KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-10/902kh",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "11",
    SKU: "773KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-11/773kh",
  },
  {
    ProductName: "Scruffs Switchback 3 Safety Boots Tan",
    Size: "12",
    SKU: "291KH",
    URL: "/p/scruffs-switchback-3-safety-boots-tan-size-12/291kh",
  },
];
