var bubbleObj2 = [
    "100% IT Recruitment Ltd",
    "118 Recruitment Solutions",
    "121 SOCIAL CARE",
    "1Stop Healthcare",
    "247 Professional Health",
    "360 Recruitment Limited",
    "4Leisure Recruitment Ltd",
    "A1 Jobs",
    "A1 People",
    "Absolute Sales & Marketing Specialists",
    "Accountancy Elite",
    "ACER Construction & Engineering",
    "Active Recruiting Consultants Ltd (ARC)",
    "Activus Recruitment Ltd",
    "Adam Butler Consultancy - Executive Search",
    "Aeropeople Limited",
    "AH Recruitment Ltd",
    "AJ Recruitment Ltd",
    "All Personnel Recruitment Ltd - Trades & Labour Division",
    "Alma Personnel",
    "Amanda Wright Recruitment Ltd",
    "Ambrose and Connor Limited",
    "Anne Jagger Recruitment LTD",
    "Apex Engineering Solutions Ltd",
    "Appointments Bi-Language",
    "Aspen Wolf Ltd",
    "Atom Recruitment Ltd.",
    "ATS Recruitment",
    "Attic Recruitment Limited",
    "Aurora Recruitment",
    "Axis Recruitment - Logistics / Shipping / Supply Chain",
    "Axis Recruitment - Manufacturing",
    "Axis Recruitment - Office Support",
    "Axis Sales & Marketing Recruitment",
    "Badger Associates Ltd",
    "Beauty Recruitment",
    "Berry Recruitment - Care Division",
    "Berry Recruitment - Catering & Hospitality Division",
    "Berry Recruitment - Commercial Division",
    "Berry Recruitment - Construction & Asbestos Division",
    "Berry Recruitment - Driving Division",
    "Berry Recruitment - Industrial and GLA Division",
    "Berry Technical & I.T. Division",
    "Berry Technical - Gas Division",
    "Best Fit Recruitment",
    "Bluebaring Recruitment ltd",
    "Bluefire Engineering & Technical",
    "Bluefire Executive Search",
    "Bluefire Facilities Management",
    "Bluefire Human Resources",
    "Bluefire IT & Telecoms",
    "BMS Sales and Marketing Specialists",
    "Brightwork Ltd",
    "Bromak Recruitment - Construction and Housing Specialists",
    "Careers In Design (Recruitment) Ltd",
    "Catermatch Solutions",
    "Catfoss Engineering Recruitment Ltd",
    "CD Sales Recruitment",
    "CEIS Business and Recruitment Services Limited",
    "Central Recruitment",
    "Centring Recruitment Limited",
    "Certainty Recruitment",
    "Challender Recruitment - Automotive Specialist",
    "Change Resourcing Ltd",
    "Charles Hunter Associates",
    "Charter Selection - Marketing Recruitment",
    "City Site Solutions Ltd",
    "CMD RECRUITMENT LIMITED",
    "Connect 4 Automotive Recruitment",
    "Connect Appointments",
    "Construction & Property Recruitment",
    "Contract Options Catering Division",
    "Cottrell Moore Ltd",
    "County Recruitment Ltd",
    "Cranleigh Scientific",
    "CRG TEC LTD",
    "D & P Associates",
    "Deerfoot IT Recruitment Specialists",
    "Denby Professionals",
    "DentalElite",
    "Duval Associates",
    "E3 Recruitment (UK) LLP",
    "Education Staffing Solutions",
    "Electus Recruitment Solutions",
    "Elite Employee - Technical and Commercial",
    "Ellis Jackson Recruitment - Health & Social Care Specialists",
    "Ellis Mack Catering", "Hospitality & Retail Specialists",
    "Executive Headhunters Ltd",
    "Executive Sales & Marketing Recruitment",
    "Express Rail Services",
    "EXTRASTAFF LIMITED",
    "Facilitate Recruitment Ltd",
    "Farringdon James",
    "FINTEC recruit Limited - Engineering & Technical specialists",
    "First 4 Education (UK) Ltd",
    "First Choice Construction",
    "Flexible Solutionz Limited",
    "Food Careers (Food Manufacturing Recruitment) Ltd",
    "Get Recruited - Sales & Marketing",
    "Get Recruited - UK",
    "GLOSS CREATIVE RECRUITMENT",
    "Glu Recruit LTD",
    "Glue Resourcing",
    "Gold Recruitment Services",
    "Hardy Recruitment - Permanent & Contract Staffing Solutions",
    "Haul-It Nationwide Ltd",
    "Highbury Recruitment",
    "HOPS Recruitment",
    "Hughes Recruitment Solutions Ltd",
    "Huntsman Recruitment",
    "HW IT Search & Selection Ltd",
    "HW Search & Selection Ltd",
    "IBP Recruitment Ltd",
    "IC Creative",
    "IC Resources",
    "iMultiply - Finance and Executive Search",
    "Influx Recruitment",
    "Innova Search - (Engineering & Manufacturing Recruitment Specialist)",
    "Intec (UK) Ltd",
    "Intro Recruitment Limited",
    "IS Recruitment - IT Specialists",
    "IT Recruit UK",
    "J&L Asbestos Recruitment",
    "Janus Childcare Recruitment",
    "Janus Recruitment Ltd",
    "JEM Childcare Solutions",
    "JLC Solutions Logistics Recruitment",
    "Joanne Finnerty Recruitment Ltd",
    "Jobline",
    "Jon Morrissey LTD - Driver Recruitment",
    "JSM Specialist Services Limited - Construction & Engineering Specialist",
    "JT Recruit Ltd",
    "KPA Recruitment Ltd",
    "KPI Care",
    "KPI Engineering Ltd",
    "Langley James IT Recruitment",
    "Le Breton Recruitment - Childcare Specialists",
    "Le Breton Recruitment - Construction specialists",
    "Link Recruitment",
    "LinkPoint Resources Limited",
    "LNS Construction Recruitment",
    "Logistics Support Network",
    "LSS Recruitment Services Ltd - Construction Division",
    "LSS Recruitment Services Ltd - Industrial Division",
    "Lynx Education Recruitment Ltd",
    "Lynx Employment Ltd",
    "Mainstay Recruitment",
    "Mana Resourcing Ltd",
    "Mango Solutions Recruitment Ltd",
    "McBarron Wood Recruitment Specialists",
    "Mech-Elec Recruitment",
    "Milk Education",
    "Minstrell Recruitment Ltd",
    "MP Resourcing LTD",
    "Multi Trades Recruitment Ltd",
    "Multitask Recruitment Solutions",
    "Network Scientific Ltd.",
    "New Focus Recruitment",
    "Norse Contracting Ltd",
    "Oakhill Recruitment",
    "Oaklands Global - Aviation & Aerospace Recruitment",
    "PA London Ltd",
    "Panda Recruitment Services Ltd",
    "Pascal Recruitment Ltd - Procurement", "Supply Chain and Logistics",
    "PB RECRUITMENT CONSULTANTS LTD",
    "Peritus Healthcare Ltd",
    "Peritus Plus",
    "Pettit Recruitment Solutions Ltd - Construction Specialists",
    "Premier Group Recruitment",
    "Premier Technical Recruitment",
    "Proactive Personnel Ltd",
    "ProClinical",
    "ProCore Solutions Limited",
    "Prodrive Recruitment",
    "Progress Recruitment Solutions (UK) Ltd - Automotive and Logistics Specialists",
    "Protocol Education",
    "Pure Recruitment Ltd",
    "Pure Staff Ltd",
    "Purple Pen Recruitment Ltd",
    "PurplePower Recruitment Ltd",
    "Ram & Sons - Construction & Civil Engineer Recruitment",
    "Recruit Mint Ltd",
    "Reiver Recruitment",
    "Resolve Recruitment Services - Commercial Division",
    "Resolve Recruitment Services - Driving & Industrial Division",
    "Reuben Sinclair - Digital and PR division",
    "Reuben Sinclair - Sales & Marketing Specialists",
    "Revolution Driver Recruitment Solutions Ltd",
    "Richards Events & Recruitment Services Limited",
    "RIG Healthcare Recruit",
    "Right 4 Site Ltd",
    "Robert Alan Partnership Ltd",
    "Role Recruitment Limited - Construction Specialists",
    "RSE Group Ltd",
    "SalonSpa Solutions",
    "Sarah Harvey Recruitment Limited",
    "Scintillant Life Sciences",
    "Sellick Partnership",
    "Service Care - Health & Social Care Division",
    "Service Care - Legal Division",
    "SLC Recruit LTD",
    "Social Care Direct Recruitment",
    "Spa Elite - Spa", "Medical Aesthetic & Leisure Recruitment",
    "Staffbase Recruitment",
    "Staffstore UK Ltd",
    "Stratus Selection Limited",
    "Strong Recruitment Group",
    "Swallowtail Recruitment Ltd",
    "Swanstaff Recruitment - Commercial Division",
    "Swanstaff Recruitment - Driving & Industrial", "permanent division",
    "Swanstaff Recruitment - Driving & Industrial", "temporary division",
    "Swanstaff Recruitment - Health & Social Care",
    "TAG IT Recruitment",
    "TalentYard",
    "Team Support Healthcare",
    "Team Support Midlands Ltd",
    "Temp Trades Ltd",
    "Temple Construction Recruitment Specialists",
    "Tennial Personnel",
    "The Advocate Group",
    "The Advocate Group - FMCG & Fashion Division",
    "The Advocate Group - Headhunting and Senior Appointments",
    "The Advocate Group - IT Division",
    "The Advocate Group - Manufacturing Division",
    "The Advocate Group - Supply Chain Division",
    "The Best Connection",
    "The Best Connection",
    "Think Specialist Recruitment - OFFICE SUPPORT STAFF EXPERTS",
    "Thornton & Lowe",
    "TOK Construction Limited",
    "Top Team Personnel",
    "Topstaff Employment",
    "Totally Recruitment - Commercial",
    "Totally Recruitment - Industrial & Transport",
    "Tradeline Recruitment Ltd",
    "Trades & Labour (UK) Limited",
    "Trident Resourcing",
    "Try Staff Ltd",
    "TSRN UK",
    "turro Ltd - Social Care (Senior & Executive Level)",
    "TwentyFour - Digital & Creative Division",
    "TwentyFour Recruitment Group",
    "United Mechanical & Electrical Solutions Ltd",
    "Vector Recruitment Limited",
    "VentureTec Ltd",
    "Vetro Recruitment - Specialist Nursing", "Care & Education recruiter",
    "Vima Professional Placements Ltd",
    "Volante Recruitment Services",
    "Westray Recruitment Consultants Ltd",
    "YWA Search & Selection"
]

export default bubbleObj2;