/** Shared object between files */
export default {
  ID: '{{ID}}',
  VARIATION: '{{VARIATION}}',
  VOUCHER_CODES: {
    ernestjones: 'EJBYDV7T',
    hsamuel: 'HS4FFJDQ',
  },
  BREAKPOINT: 768,
  SUBMIT_API_URL: '/webstore/api/responsys/newsletter/signUp/',
  EXCLUSIONS: ["Ax Connected", 
    "Diesel On", 
    "Fitbit", 
    "Fossil Q", 
    "Garmin", 
    "GC Connect", 
    "Guess Connect", 
    "Huawei", 
    "Misfit", 
    "Skagen Connect", 
    "Timex IQ+", 
    "Smart Watches", 
    "Activity Tracker", 
    "MEY for Game of Thrones", 
    "Cartier", 
    "Omega", 
    "TAG Heuer", 
    "Breitling", 
    "Bremont", 
    "Zenith", 
    "Tudor", 
    "Chanel", 
    "Gucci", 
    "Chopard", 
    "Michael Kors Access"],
};
