export const ctaConfigV1 = [
  {
    countryPrefix: '/g/',
    landingUrl: [
      '/g/finance-reduce-churn/',
      '/g/finance-reduce-churn-gb/',
      '/g/finance-reduce-churn-50/',
      '/g/finance-reduce-churn-50-gb/',
      '/g/happy-customers/',
      '/g/happy-customers-gb/',
      '/g/keep-customers-happy/',
      '/g/keep-customers-happy-gb/',
      '/g/reduce-churn-by-50/',
      '/g/reduce-churn-by-50-gb/',
      '/g/reduce-churn-rc/',
      '/g/reduce-churn-rc-gb/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu/global-payment-timings-index-2021',
    ctaCopy: 'Get the index report',
    supportingCopy: 'Learn strategies to reduce your DSO and get paid 47% faster',
  },

  {
    countryPrefix: '/en-us/',
    landingUrl: [
      '/en-us/g/finance-reduce-churn/',
      '/en-us/g/finance-reduce-churn-50/',
      '/en-us/g/happy-customers/',
      '/en-us/g/keep-customers-happy/',
      '/en-us/g/reduce-churn-by-50/',
      '/en-us/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu-na/global-payment-timings-index-2021',
    ctaCopy: 'Get the index report',
    supportingCopy: 'Learn strategies to reduce your DSO and get paid 47% faster',
  },
  {
    countryPrefix: '/en-au/',
    landingUrl: [
      '/en-au/g/finance-reduce-churn/',
      '/en-au/g/finance-reduce-churn-50/',
      '/en-au/g/happy-customers/',
      '/en-au/g/keep-customers-happy/',
      '/en-au/g/reduce-churn-by-50/',
      '/en-au/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu-au/global-payment-timings-index-2021',
    ctaCopy: 'Get the index report',
    supportingCopy: 'Learn strategies to reduce your DSO and get paid 47% faster',
  },
  {
    countryPrefix: '/en-nz/',
    landingUrl: [
      '/en-nz/g/finance-reduce-churn/',
      '/en-nz/g/finance-reduce-churn-50/',
      '/en-nz/g/happy-customers/',
      '/en-nz/g/keep-customers-happy/',
      '/en-nz/g/reduce-churn-by-50/',
      '/en-nz/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu-nz/global-payment-timings-index-2021',
    ctaCopy: 'Get the index report',
    supportingCopy: 'Learn strategies to reduce your DSO and get paid 47% faster',
  },
  {
    countryPrefix: '/fr-',
    landingUrl: [
      '/fr-fr/g/finance-reduce-churn/',
      '/fr-fr/g/finance-reduce-churn-50/',
      '/fr-fr/g/happy-customers/',
      '/fr-fr/g/keep-customers-happy/',
      '/fr-fr/g/reduce-churn-by-50/',
      '/fr-fr/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu-fr/calculateur-fonds-de-roulement',
    ctaCopy: "Obtenir le rapport d'index",
    supportingCopy: 'Apprenez des stratégies pour réduire votre DSO et soyez payé 47% plus rapidement',
  },
  {
    countryPrefix: '/de-',
    landingUrl: [
      '/de-de/g/finance-reduce-churn/',
      '/de-de/g/finance-reduce-churn-50/',
      '/de-de/g/happy-customers/',
      '/de-de/g/keep-customers-happy/',
      '/de-de/g/reduce-churn-by-50/',
      '/de-de/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://content.gocardless.com/cashflow-mofu-de/der-globale-payment-timing-index-2021',
    ctaCopy: 'Holen Sie sich den Indexbericht',
    supportingCopy: 'Lernen Sie Strategien kennen, um Ihre DSO zu reduzieren und 47 % schneller bezahlt zu werden',
  },
];

export const ctaConfigV2 = [
  {
    countryPrefix: '/g/',
    landingUrl: [
      '/g/finance-reduce-churn/',
      '/g/finance-reduce-churn-gb/',
      '/g/finance-reduce-churn-50/',
      '/g/finance-reduce-churn-50-gb/',
      '/g/happy-customers/',
      '/g/happy-customers-gb/',
      '/g/keep-customers-happy/',
      '/g/keep-customers-happy-gb/',
      '/g/reduce-churn-by-50/',
      '/g/reduce-churn-by-50-gb/',
      '/g/reduce-churn-rc/',
      '/g/reduce-churn-rc-gb/',
    ],
    ctaLink: 'https://gocardless.com/g/book-a-demo/',
    ctaCopy: 'Get a demo',
    supportingCopy: 'Discover how you can reduce your DSO with GoCardless',
  },

  {
    countryPrefix: '/en-us/',
    landingUrl: [
      '/en-us/g/finance-reduce-churn/',
      '/en-us/g/finance-reduce-churn-50/',
      '/en-us/g/happy-customers/',
      '/en-us/g/keep-customers-happy/',
      '/en-us/g/reduce-churn-by-50/',
      '/en-us/g/reduce-churn-rc/',
    ],
    ctaLink: 'http://gocardless.com/en-us/g/book-a-demo/',
    ctaCopy: 'Get a demo',
    supportingCopy: 'Discover how you can reduce your DSO with GoCardless',
  },
  {
    countryPrefix: '/en-au/',

    landingUrl: [
      '/en-au/g/finance-reduce-churn/',
      '/en-au/g/finance-reduce-churn-50/',
      '/en-au/g/happy-customers/',
      '/en-au/g/keep-customers-happy/',
      '/en-au/g/reduce-churn-by-50/',
      '/en-au/g/reduce-churn-rc/',
    ],
    ctaLink: 'http://gocardless.com/en-au/g/book-a-demo/',
    ctaCopy: 'Get a demo',
    supportingCopy: 'Discover how you can reduce your DSO with GoCardless',
  },
  {
    countryPrefix: '/en-nz/',
    landingUrl: [
      '/en-nz/g/finance-reduce-churn/',
      '/en-nz/g/finance-reduce-churn-50/',
      '/en-nz/g/happy-customers/',
      '/en-nz/g/keep-customers-happy/',
      '/en-nz/g/reduce-churn-by-50/',
      '/en-nz/g/reduce-churn-rc/',
    ],
    ctaLink: 'http://gocardless.com/en-nz/g/book-a-demo/',
    ctaCopy: 'Get a demo',
    supportingCopy: 'Discover how you can reduce your DSO with GoCardless',
  },
  {
    countryPrefix: '/fr-',
    landingUrl: [
      '/fr-fr/g/finance-reduce-churn/',
      '/fr-fr/g/finance-reduce-churn-50/',
      '/fr-fr/g/happy-customers/',
      '/fr-fr/g/keep-customers-happy/',
      '/fr-fr/g/reduce-churn-by-50/',
      '/fr-fr/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://gocardless.com/fr-fr/g/je-voux-une-demo/',
    ctaCopy: 'Obtenez une démo',
    supportingCopy: 'Découvrez comment vous pouvez réduire votre DSO avec GoCardless',
  },
  {
    countryPrefix: '/de-',
    landingUrl: [
      '/de-de/g/finance-reduce-churn/',
      '/de-de/g/finance-reduce-churn-50/',
      '/de-de/g/happy-customers/',
      '/de-de/g/keep-customers-happy/',
      '/de-de/g/reduce-churn-by-50/',
      '/de-de/g/reduce-churn-rc/',
    ],
    ctaLink: 'https://gocardless.com/de-de/g/demo-anfordern/',
    ctaCopy: 'Holen Sie sich eine Demo',
    supportingCopy: 'Entdecken Sie, wie Sie Ihre DSO mit GoCardless reduzieren können',
  },
];
