export default {
  '/brand/polo-ralph-lauren': {
    'https://www.houseoffraser.co.uk/men/mens-polo-shirts/polo-ralph-lauren': "Polo Shirts",
    'https://www.houseoffraser.co.uk/men/shirts/polo-ralph-lauren': "Shirts",
    'https://www.houseoffraser.co.uk/men/knitwear/polo-ralph-lauren': "Jumpers",
    'https://www.houseoffraser.co.uk/bags-and-luggage/handbags/polo-ralph-lauren': "Handbags",
    'https://www.houseoffraser.co.uk/brand/polo-ralph-lauren#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EMens': "Mens",
    'https://www.houseoffraser.co.uk/brand/polo-ralph-lauren#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EWomens': "Womens",
  },
  '/brand/mulberry': {
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EHandbags': 'Handbags',
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EPurses': 'Purses',
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EScarves': 'Scarves',
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EShoes': 'Shoes',
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EBoots': 'Boots',
    'https://www.houseoffraser.co.uk/brand/mulberry#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ESunglasses': 'Sunglasses',
  },
  '/brand/barbour': {
    'https://www.houseoffraser.co.uk/brand/barbour#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ECoats%20and%20Jackets': 'Jackets',
    'https://www.houseoffraser.co.uk/brand/barbour#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ETops%20and%20T-Shirts': 'T-shirts',
    'https://www.houseoffraser.co.uk/brand/barbour#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EHoodies%20and%20Sweatshirts': 'Sweatshirts',
    'https://www.houseoffraser.co.uk/brand/barbour#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EKnitwear': 'Knitwear',
    'https://www.houseoffraser.co.uk/men/barbour': 'Mens',
    'https://www.houseoffraser.co.uk/women/barbour': 'Womens',
    'https://www.houseoffraser.co.uk/kids-and-baby/barbour': 'Kids',
  },
  '/brand/boss': {
    'https://www.houseoffraser.co.uk/beauty/perfumes/boss': 'Fragrance',
    'https://www.houseoffraser.co.uk/accessories/watches/boss': 'Watches',
    'https://www.houseoffraser.co.uk/accessories/sunglasses/boss': 'Sunglasses',
    'https://www.houseoffraser.co.uk/brand/boss#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ETops%20and%20T-Shirts': 'T-shirts',
    'https://www.houseoffraser.co.uk/brand/boss#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ETops%20and%20T-Shirts%2CHoodies%20and%20Sweatshirts': 'Sweatshirts',
    'https://www.houseoffraser.co.uk/men/boss': 'Mens',
    'https://www.houseoffraser.co.uk/women/boss-women': 'Womens',
    'https://www.houseoffraser.co.uk/kids-and-baby/boss': 'Kids',
  },
  '/brand/versace-jeans-couture': {
    'https://www.houseoffraser.co.uk/shoes-and-boots/shoes/trainers/versace-jeans-couture': 'Trainers',
    'https://www.houseoffraser.co.uk/bags-and-luggage/handbags/versace-jeans-couture': 'Bags',
    'https://www.houseoffraser.co.uk/brand/versace-jeans-couture#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5ETops%20and%20T-Shirts': 'T-shirts',
    'https://www.houseoffraser.co.uk/brand/versace-jeans-couture#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EHoodies%20and%20Sweatshirts': 'Sweatshirts',
    'https://www.houseoffraser.co.uk/brand/versace-jeans-couture#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EMens': 'Mens',
    'https://www.houseoffraser.co.uk/brand/versace-jeans-couture#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EWomens': 'Womens',
  },
  '/brand/calvin-klein': {
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EJeans': 'Jeans',
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EUnderwear': 'Underwear',
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EHoodies%20and%20Sweatshirts': 'Sweatshirts',
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=WEBCAT%5EHandbags': 'Bags',
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EMens': 'Mens',
    'https://www.houseoffraser.co.uk/brand/calvin-klein#dcp=1&dppp=36&OrderBy=rank&Filter=AFLOR%5EWomens': 'Womens',
    'https://www.houseoffraser.co.uk/kids-and-baby/calvin-klein': 'Kids',
  },
};
