export const data = {
	"/product/brother-dcp-l3510cdw/143998": {
		performance: [
			"As Fast as 15.5 Seconds First page",
			"Up to 18ppm Mono Print",
			"Up to 18ppm Colour Print",
			"Up to 600 x 2,400 dpi Print",
			"Up to 600 x 600 dpi Copy",
		],
		technical: [
			"USB, Wireless & Wi-Fi Direct",
			"PCL6, BR-Script3 PDF Version 1.7, XPS Version 1.0",
			"Windows, Mac & Linux Compatible",
			"800MHz Processor",
			"512MB RAM",
		],
		highlights: ["Print/Scan/Copy", "2-Line LCD Control Panel"],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed Slot",
		],
	},
	"/product/brother-mfc-j5340dw/151105": {
		performance: [
			"As Fast as 4.4 Seconds First page",
			"Up to 28ppm Mono Print",
			"Up to 28ppm Colour Print",
			"Up to 1,200 x 4,800 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"Up to 14.4Kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"Windows, Mac & Linux Compatible",
			"256MB RAM",
		],
		highlights: [
			"Print A3, Scan, Copy & Fax A4",
			"Quiet Mode Feature",
			"6.8cm Colour LCD Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed Slot",
		],
	},
	"/product/epson-ecotank-et-15000/149079": {
		performance: [
			"Up to 38ppm Mono Print",
			"Up to 24ppm Colour Print",
			"Up to 4,800 x 1,200 dpi Print",
			"Up to 33.6kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"Windows & Mac Compatible",
			"6.8cm Colour Touchscreen",
		],
		highlights: ["Print A3, Scan, Copy & Fax A4"],
		media: [
			"Automatic Double Sided Printing",
			"A4 Print/Scan/Copy/Fax + Option to print up to A3 with rear media feed",
			"250 Sheet Input Tray",
			"20 Sheet Rear Input Tray",
		],
	},
	"/product/epson-workforce-pro-wf-4820dwf/149137": {
		performance: [
			"Up to 36ppm Mono Print",
			"Up to 22ppm Colour Print",
			"Up to 4,800 x 2,400 dpi Print",
			"Up to 33.6kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"Windows & Mac Compatible",
			"10.9cm Touch Screen",
		],
		highlights: ["Print/Scan/Copy/Fax"],
		media: ["Automatic Double Sided Printing", "250 Sheet Input Tray"],
	},
	"/product/epson-workforce-pro-wf-4830dtwf/149138": {
		performance: [
			"Up to 36ppm Mono Print",
			"Up to 22ppm Colour Print",
			"Up to 4,800 x 2,400 dpi Print",
			"Up to 33.6kbps Fax",
		],
		technical: [
			"USB, Network, Wireless, Wi-Fi Direct & NFC",
			"ESC/P-R",
			"Windows & Mac Compatible",
		],
		highlights: ["Print/Scan/Copy/Fax", "10.9cm Touchscreen"],
		media: ["Automatic Double Sided Printing", "2 x 250 Sheet Input Trays"],
	},
	// "/product/hp-color-laserjet-enterprise-mfp-m480f/150089": {
	//   performance: ["As Fast as 9.5 Seconds First page", "Up to 27ppm Mono Print", "Up to 600 x 600 dpi Print", "Up to 27ppm Colour Print", "Up to 33.6kbps Fax"],
	//   technical: [
	//     "USB & Network",
	//     "HP PCL 6, HP PCL 5, HP PostScript level 3 Emulation",
	//     "Native PDF Printing (v 1.7), Apple AirPrint",
	//     "Windows & Mac Compatible",
	//     "800MHz Processor",
	//     "2GB RAM",
	//   ],
	//   highlights: ["Print/Scan/Copy/Fax", "10.9cm Colour LCD Touch Screen"],
	//   media: ["Automatic Double Sided Printing", "50 Sheet Multipurpose Tray", "250 Sheet Input Tray"],
	// },
	"/product/hp-laserjet-pro-m404dn/145731": {
		performance: [
			"As Fast as 6.3 Seconds First page",
			"Up to 38ppm Mono Print",
			"Up to 4,800 x 600 dpi Print",
		],
		technical: [
			"USB & Network",
			"HP PCL 6, HP PCL 5c, HP Postscript Level 3 Emulation, PDF, URF, PWG Raster",
			"Windows & Mac Compatible",
			"1200MHz Processor",
			"256MB RAM",
		],
		highlights: ["2-Line LCD Display"],
		media: [
			"Automatic Double Sided Printing",
			"100 Sheet Multipurpose Tray",
			"250 Sheet Input Tray",
		],
	},
	// "/product/hp-laserjet-pro-mfp-m428dw/145785": {
	// 	performance: [
	// 		"As Fast as 6.3 Seconds First page",
	// 		"Up to 38ppm Mono Print",
	// 		"Up to 4,800 x 600 dpi Print",
	// 	],
	// 	technical: [
	// 		"USB, Network, Wireless & Wi-Fi Direct",
	// 		"HP PCL 6, HP PCL 5c, HP PostScript Level 3 Emulation, PDF, URF, Native Office, PWG Raster",
	// 		"Windows & Mac Compatible",
	// 		"1200MHz Processor",
	// 		"512MB RAM",
	// 		"6.9cm Colour Touch Screen",
	// 	],
	// 	highlights: ["Print/Scan/Copy", ""],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"100 Sheet Input Tray",
	// 		"250 Sheet Input Tray",
	// 	],
	// },
	"/product/hp-laserjet-pro-mfp-m428fdn/145786": {
		performance: [
			"As Fast as 6.3 Seconds First page",
			"Up to 38ppm Mono Print",
			"Up to 4,800 x 600 dpi Print",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB & Network",
			"HP PCL 6, HP PCL 5c, HP PostScript Level 3 Emulation, PDF, URF, Native Office, PWG Raster",
			"Windows & Mac Compatible",
			"1200MHz Processor",
			"512MB RAM",
		],
		highlights: ["Print/Scan/Copy/Fax", "6.9cm Colour Touch Screen"],
		media: [
			"Automatic Double Sided Printing",
			"100 Sheet Input Tray",
			"250 Sheet Input Tray",
		],
	},
	// "/product/hp-laserjet-pro-mfp-m428fdw/145787": {
	// 	performance: [
	// 		"As Fast as 6.3 Seconds First page",
	// 		"Up to 38ppm Mono Print",
	// 		"Up to 4,800 x 600 dpi Print",
	// 		"Up to 33.6Kbps Fax",
	// 	],
	// 	technical: [
	// 		"USB, Network, Wireless & Wi-Fi Direct",
	// 		"HP PCL 6, HP PCL 5c, HP PostScript Level 3 Emulation, PDF, URF, Native Office, PWG Raster",
	// 		"Windows & Mac Compatible",
	// 		"1200MHz Processor",
	// 		"512MB RAM",
	// 	],
	// 	highlights: ["Print/Scan/Copy/Fax", "6.9cm Colour Touch Screen"],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"100 Sheet Input Tray",
	// 		"250 Sheet Input Tray",
	// 	],
	// },
	// "/product/hp-officejet-200/139149": {
	// 	performance: [
	// 		"As Fast as 12 Seconds First page",
	// 		"Up to 10ppm Mono Print",
	// 		"Up to 7ppm Colour Print",
	// 		"Up to 1,200 x 1,200 dpi Print",
	// 	],
	// 	technical: [
	// 		"USB & Wireless",
	// 		"Windows & Mac Compatible",
	// 		"525 MHz Processor",
	// 		"128MB RAM",
	// 	],
	// 	highlights: ["5.08cm Mono Graphic Display"],
	// 	media: [],
	// },
	"/product/hp-officejet-250/139147": {
		performance: [
			"As Fast as 11 Seconds First page",
			"Up to 10ppm Mono Print",
			"Up to 7ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 600 x 600 dpi Copy",
		],
		technical: [
			"USB & Wireless",
			"Windows & Mac Compatible",
			"700MHz Processor",
			"256MB RAM",
		],
		highlights: ["Print/Scan/Copy", "6.73cm Colour Touch Screen"],
		media: ["50 Sheet Input Tray"],
	},
	// "/product/hp-officejet-8015e/150133": {
	// 	performance: [
	// 		"As Fast as 13 Seconds First page",
	// 		"Up to 18ppm Mono Print",
	// 		"Up to 10ppm Colour Print",
	// 		"Up to 1,200 x 1,200 dpi Print",
	// 		"Up to 600 x 600 dpi Copy",
	// 	],
	// 	technical: [
	// 		"Wireless & Wi-Fi Direct",
	// 		"HP PCL3 GUI",
	// 		"Windows & Mac Compatible",
	// 		"1200MHz Processor",
	// 		"256MB RAM",
	// 	],
	// 	highlights: [
	// 		"Print/Scan/Copy",
	// 		"HP+ Eligible",
	// 		"6 Months of Instant Ink and Up to 3 Years Extended Warranty Included with HP+",
	// 		"Get Advanced Smart App Solutions with HP+",
	// 	],
	// 	media: ["Automatic Double Sided Printing", "225 Sheet Input Tray"],
	// },
	"/product/hp-officejet-pro-7740/138906": {
		performance: [
			"As Fast as 10 Seconds First page",
			"Up to 34ppm Mono Print",
			"Up to 34ppm Colour Print",
			"Up to 4,800 x 1,200 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network & Wireless",
			"HP PCL 3 GUI, HP PCL 3 Enhanced",
			"Windows & Mac Compatible",
			"512 MB RAM",
			"6.75cm LCD Touch Screen",
		],
		highlights: ["Print/Scan/Copy/Fax"],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"75 Sheet Output Tray",
			"Parts: Up to 99 copies",
			"",
		],
	},
	"/product/hp-officejet-pro-8730/137611": {
		performance: [
			"As Fast as 9 Seconds First page",
			"Up to 24ppm Mono Print",
			"Up to 20ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network & Wireless",
			"PCL3",
			"Windows & Mac Compatible",
			"233MHz Processor",
			"512MB RAM",
			"1GB HDD",
		],
		highlights: ["Print/Scan/Copy/Fax", "10.9cm Colour Touch Screen"],
		media: ["Automatic Double Sided Printing", "250 Sheet Input Tray"],
	},
	"/product/hp-officejet-pro-9010e/150137": {
		performance: [
			"As Fast as 9 Seconds First page",
			"Up to 22ppm Mono Print",
			"Up to 18ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 4,800 x 1,200 dpi Print Enhanced",
			"Up to 600 x 600 dpi Copy",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"HP PCL3 GUI",
			"Windows & Mac Compatible",
			"1.2GHz Processor",
			"512MB RAM",
		],
		highlights: [
			"Print/Scan/Copy/Fax",
			"HP+ Eligible",
			"6 Months of Instant Ink and Up to 3 Years Extended Warranty Included with HP+",
			"Get Advanced Smart App Solutions with HP+",
			"6.86cm Colour Touch Screen",
		],
		media: ["Automatic Double Sided Printing", "250 Sheet Input Tray"],
	},
	"/product/hp-officejet-pro-9022e/150141": {
		performance: [
			"As Fast as 9 Seconds First page",
			"Up to 24ppm Mono Print",
			"Up to 20ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 4,800 x 1,200 dpi Print Enhanced",
			"Up to 600 x 600 dpi Copy",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"HP PCL3 GUI",
			"Windows & Mac Compatible",
			"1.2GHz Processor",
			"512MB RAM",
		],
		highlights: [
			"Print/Scan/Copy/Fax",
			"HP+ Eligible",
			"6 Months of Instant Ink and Up to 3 Years Extended Warranty Included with HP+",
			"Get Advanced Smart App Solutions with HP+",
			"6.75cm Colour Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"250 Sheet Multipurpose Tray",
		],
	},
	"/product/kyocera-ecosys-m5526cdw/138547": {
		performance: [
			"As Fast as 11 Seconds First page",
			"Up to 26ppm Mono Print",
			"Up to 26ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network & Wireless",
			"PCL5/6 & Postscript 3",
			"Windows, Mac & Linux Compatible",
			"Coretex-A9 800MHz Processor",
			"512MB (1,536MB) RAM",
		],
		highlights: [
			"Print/Scan/Copy/Fax",
			"Continue printing in mono even if the printer is out of colour toners",
			"NHS Prescription Printing Approved",
			"High Security Through SSL, IPsec and Private Print Functionality",
			"10.9cm Colour Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"50 Sheet Multipurpose Tray",
		],
	},
	"/product/kyocera-ecosys-m8124cidn/141262": {
		performance: [
			"As Fast as 7.5 Seconds First page",
			"Up to 24ppm Mono Print",
			"Up to 24ppm Colour Print",
			"Up to 1,200 x 1,200 dpi Print",
			"Up to 600 x 600 dpi Copy",
		],
		technical: [
			"USB & Network",
			"PCL & Postscript 3",
			"PCL6 (5c/XL), KPDL3 (PostScript 3 compatible), PDF Direct Print, XPS Direct Print and Open XPS",
			"Windows, Mac & Linux Compatible",
			"ARM Cortex-A9 Dual Core 1.2GHz Processor",
			"1.5GB (3GB) RAM",
		],
		highlights: [
			"Print/Scan/Copy",
			"Continue printing in mono even if the printer is out of colour toners",
			"Secure Printing via SSL and Private Print",
			"4.3 Inch Colour Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"100 Sheet Multipurpose Tray",
			"500 Sheet Input Tray",
		],
	},
	"/product/xerox-b225/150346": {
		performance: [
			"As Fast as 6.4 Seconds First page",
			"Up to 34ppm Mono Print",
			"Up to 2400 dpi Print",
			"Up to 600 x 600 dpi Copy",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"PCL 5/6, PostScript 3",
			"Windows & Mac Compatible",
			"1GHz Dual Core Processor",
			"512MB RAM",
		],
		highlights: ["Print/Scan/Copy"],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed",
		],
	},
	"/product/xerox-b230/150348": {
		performance: [
			"As Fast as 6.8 Seconds First page",
			"Up to 34ppm Mono Print",
			"Up to 2400 dpi Print",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"PCL 5/6, PostScript 3",
			"Windows & Mac Compatible",
			"1GHz Dual Core Processor",
			"256MB RAM",
		],
		highlights: [],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed",
		],
	},
	"/product/xerox-b310/150349": {
		performance: [
			"As Fast as 5.2 Seconds First page",
			"Up to 40ppm Mono Print",
			"Up to 600 x 600 (2400 Image Quality) dpi Print",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"PostScript 3, PCL 5, PCL 6, Direct Image",
			"Windows & Mac Compatible",
			"1GHz Dual Core Processor",
			"256MB RAM",
		],
		highlights: [],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"100 Sheet Multipurpose Tray",
		],
	},
	"/product/xerox-c310/150812": {
		performance: [
			"As Fast as 6.7 Seconds First page",
			"Up to 33ppm Mono Print",
			"Up to 33ppm Colour Print",
			"Up to 4800 dpi Print",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"PostScript 3 Emulation, PCL 6 Emulation, PCL 5, XPS, PDF v1.7 Emulation, HTML, Direct Image",
			"Windows & Mac Compatible",
			"1GHz Dual Core Processor",
			"1GB RAM",
		],
		highlights: [],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed Slot",
		],
	},
	"/product/xerox-c315/150813": {
		performance: [
			"As Fast as 7.9 Seconds First page",
			"Up to 33ppm Mono Print",
			"Up to 33ppm Colour Print",
			"Up to 4800 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"Up to 33.6Kbps Fax",
		],
		technical: [
			"USB, Network, Wireless & Wi-Fi Direct",
			"PostScript 3 Emulation, PCL 6 Emulation, PCL 5, XPS, PDF v1.7 Emulation, HTML, Direct Image",
			"Windows & Mac Compatible",
			"1.2GHz Quad Core Processor",
			"2GB RAM",
		],
		highlights: ["Print/Scan/Copy/Fax"],
		media: [
			"Automatic Double Sided Printing",
			"250 Sheet Input Tray",
			"1 Sheet Manual Feed Slot",
		],
	},
	// "/product/xerox-phaser-6510dn/138514": {
	// 	performance: [
	// 		"As Fast as 12 Seconds First page",
	// 		"Up to 28ppm Mono Print",
	// 		"Up to 28ppm Colour Print",
	// 		"Up to 1,200 x 2,400 dpi Print",
	// 	],
	// 	technical: [
	// 		"USB & Network",
	// 		"Adobe PostScript 3, PCL 5e/6",
	// 		"Windows & Mac Compatible",
	// 		"733MHz Processor",
	// 		"1GB RAM",
	// 	],
	// 	highlights: [
	// 		"Continue printing in mono even if the printer is out of colour toners",
	// 		"2-Line LCD Screen",
	// 	],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"250 Sheet Input Tray",
	// 		"50 Sheet Bypass Tray",
	// 	],
	// },
	// "/product/xerox-phaser-6510dni/140764": {
	// 	performance: [
	// 		"As Fast as 12 Seconds First page",
	// 		"Up to 28ppm Mono Print",
	// 		"Up to 28ppm Colour Print",
	// 		"Up to 1,200 x 2,400 dpi Print",
	// 	],
	// 	technical: [
	// 		"USB, Network & Wireless",
	// 		"Adobe PostScript 3, PCL 5e/6",
	// 		"Windows & Mac Compatible",
	// 		"733MHz Processor",
	// 		"1GB RAM",
	// 	],
	// 	highlights: [
	// 		"Continue printing in mono even if the printer is out of colour toners",
	// 		"2-Line LCD Screen",
	// 	],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"250 Sheet Input Tray",
	// 		"50 Sheet Bypass Tray",
	// 	],
	// },
	"/product/xerox-versalink-c405dn/138869": {
		performance: [
			"As Fast as 12 Seconds First page",
			"Up to 35ppm Mono Print",
			"Up to 35ppm Colour Print",
			"Up to 600 x 600 x 8 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"33.6Kbps Fax",
		],
		technical: [
			"USB, Network & NFC",
			"PCL5/6, Postscript 3, PDF, XPS, TIFF, JPEG, HP-GL",
			"Windows & Mac Compatible",
			"1.05GHz Dual-Core Processor",
			"2GB RAM",
		],
		highlights: [
			"Print/Scan/Copy/Fax",
			"Continue printing in mono even if the printer is out of colour toners",
			"Benchmark Security Features with ConnectKey® Technology",
			"5 Inch Capacitive Colour Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"550 Sheet Input Tray",
			"150 Sheet Bypass Tray",
		],
	},
	"/product/xerox-versalink-c600dn/139740": {
		performance: [
			"As Fast as 8 Seconds First page",
			"Up to 53ppm Mono Print",
			"Up to 53ppm Colour Print",
			"Up to 1,200 x 2,400 dpi Print",
		],
		technical: [
			"USB & Network",
			"PCL 5/6, PDF, JPEG, PostScript 3",
			"Windows & Mac Compatible",
			"1.05GHz Processor",
			"2GB RAM",
			"Optional HDD",
		],
		highlights: [
			"Continue printing in mono even if the printer is out of colour toners",
			"Benchmark Security Features with ConnectKey® Technology",
			"5 Inch Compatitive Colour Touch Screen",
		],
		media: [
			"Automatic Double Sided Printing",
			"550 Sheet Input Tray",
			"150 Sheet Bypass tray",
		],
	},
	// "/product/xerox-workcentre-6515dn/138524": {
	// 	performance: [
	// 		"As Fast as 12 Seconds First page",
	// 		"Up to 28ppm Mono Print",
	// 		"Up to 28ppm Colour Print",
	// 		"Up to 1,200 x 2,400 dpi Print",
	// 		"Up to 600 x 600 dpi Copy",
	// 		"33.6Kbps Fax",
	// 	],
	// 	technical: [
	// 		"USB & Network",
	// 		"Adobe PostScript 3, PCL 5e/6, PDF, TIFF",
	// 		"Windows & Mac Compatible",
	// 		"1.05GHz Processor",
	// 		"2GB RAM",
	// 	],
	// 	highlights: [
	// 		"Print/Copy/Scan/Fax",
	// 		"Benchmark Security Features with IP filtering and Secure Print",
	// 		"Continue printing in mono even if the printer is out of colour toners",
	// 		"Customisable 5 Inch App Based LCD Touch Screen",
	// 	],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"250 Sheet Input Tray",
	// 		"50 Sheet Bypass Tray",
	// 	],
	// },
	// "/product/xerox-workcentre-6515dni/138526": {
	// 	performance: [
	// 		"As Fast as 12 Seconds First page",
	// 		"Up to 28ppm Mono Print",
	// 		"Up to 28ppm Colour Print",
	// 		"Up to 1,200 x 2,400 dpi Print",
	// 		"Up to 600 x 600 dpi Copy",
	// 		"33.6Kbps Fax",
	// 	],
	// 	technical: [
	// 		"USB, Network, Wireless & Wi-Fi Direct",
	// 		"Adobe PostScript 3, PCL 5e/6, PDF, TIFF",
	// 		"Windows & Mac Compatible",
	// 		"1.05GHz Processor",
	// 		"2GB RAM",
	// 	],
	// 	highlights: [
	// 		"Print/Copy/Scan/Fax",
	// 		"Benchmark Security Features with IP filtering and Secure Print",
	// 		"Continue printing in mono even if the printer is out of colour toners",
	// 		"Customisable 5 Inch App Based LCD Touch Screen",
	// 	],
	// 	media: [
	// 		"Automatic Double Sided Printing",
	// 		"250 Sheet Input Tray",
	// 		"50 Sheet Bypass Tray",
	// 	],
	// },
	"/product/xerox-workcentre-6515n/138519": {
		performance: [
			"As Fast as 12 Seconds First page",
			"Up to 28ppm Mono Print",
			"Up to 28ppm Colour Print",
			"Up to 1,200 x 2,400 dpi Print",
			"Up to 600 x 600 dpi Copy",
			"33.6Kbps Fax",
		],
		technical: [
			"USB & Network",
			"Adobe PostScript 3, PCL 5e/6, PDF, TIFF",
			"Windows & Mac Compatible",
			"1.05GHz Processor",
			"2GB RAM",
		],
		highlights: [
			"Print/Copy/Scan/Fax",
			"Benchmark Security Features with IP filtering and Secure Print",
			"Continue printing in mono even if the printer is out of colour toners",
			"Customisable 5 Inch App Based LCD Touch Screen",
		],
		media: ["250 Sheet Input Tray", "50 Sheet Bypass Tray"],
	},
};
