export default {
  "310400": { 1:"The perfect way to taste all the delicate notes on our different chocolate grades, solid chocolate batons showcasing our signature 40% milk, caramel milk and white chocolate, the perfect gift for anyone,", 2:"Carefully designed for the perfect tasting and sharing experience.", 3:"45 solid chocolate batons in 40% milk, caramel, and white chocolate.", 4:"A perfect gift, with the chance to taste a wider variety of flavours."},
  "310391": { 1:"Carefully designed and moulded chocolate that allows you to experience the tasting notes of all of our chocolate grades, designed to taste and share, a minimum of 40% cocoa solids in our milk chocolate make these astonishingly moreish and full of intricate cocoa notes", 2:"Carefully designed for the perfect tasting and sharing experience.", 3:"15 astonishingly moreish batons in our signature 40% milk chocolate.", 4:"An ideal gift for milk chocolate lovers, with their unique flavour."},
  "310390": { 1:"Carefully designed and moulded chocolate that allows you to experience the tasting notes of all of our chocolate grades, perfect for those who love the flavout of runny, sticky caramel and chocolate but without any mess, share, nible on or stash", 2:"Carefully designed for the perfect tasting and sharing experience.", 3:"15 smooth and creamy chocolate batons flavoured with real caramel.", 4:"Perfect for those who love the flavour of sticky caramel and chocolate, but without the mess."},
  "310393": { 1:"Carefully designed and moulded chocolate that allows you to experience the tasting notes of all of our chocolate grades, a deep and indulgent cocoa profile without being too rich, suitable for vegetarians and vegans", 2:"Carefully designed for the perfect tasting and sharing experience.", 3:"15 smooth chocolate batons in deep and decadent 70% dark chocolate.", 4:"Perfect for dark chocolate lovers and suitable for vegetarians and vegans."},
  "111968": { 1:"Our take on the French patisserie…recreated in chocolate form, a perfect after lunch/dinner treat to share with friends and family, high cocoa percentage allowing you to access the multi-layed lastes of the cocoa bean ", 2:"Iconic French Patisserie maracons recreated in chocolate form.", 3:"Light as air 60% hazelnut praline nestled between 40% milk chocolate disks.", 4:"Perfect for an after lunch or dinner treat to share with friends and family."},
  "112084": { 1:"Our take on the French patisserie…recreated in chocolate form, uses Valencian orange to bring citrus sweetness to our finest smooth mellow chocolate, a perfect gift ", 2:"Iconic French Patisserie maracons recreated in chocolate form.", 3:"Valencian orange infused delicate whip, zesty éclat, and 40% milk chocolate discs.", 4:"Our Orange Macarons make the perfect elegant small gift."},
  "112079": { 1:"Our take on the French patisserie…recreated in chocolate form, natural raspberry flavouring, the perfect accopaniment to a cup of tea or coffee", 2:"Iconic French Patisserie maracons recreated in chocolate form.", 3:"Light-as-air raspberry whip, sandwiched between two buttery, caramel-milk discs.", 4:"The perfect accompaniment to a cup of tea or coffe."},
  "260748": { 1:"Contains our most-loved chocolates in one place, satisfy your milk and dark chocolate cravings", 2:"14 of our top-selling chocolates, ever.", 3:"All the flavours you need in milk, dark and white chocolate to satisfy your cocoa cravings.", 4:"Perfect for those who have a smaller appetite, but still want big flavours."},
  "260740": { 1:"Perfect for sharing, contains our most-loved chocolates in one place, satisfy your milk and dark chocolate cravings", 2:"27 of our top-selling chocolates, ever.", 3:"Our most popular box, including a variety of flavours in milk, dark and white chocolate, perfect for sharing.", 4:"Find 2 of nearly every flavour, perfect for a complete chocolate tasting adventure."},
  "260756": { 1:"Perfect for sharing, contains our most-loved chocolates in one place, a luxury gift for the renowned chocoholic", 2:"40 of our top-selling chocolates, ever.", 3:"A wide variety of flavours in milk, dark and white chocolate, including some boozy indulgences, perfect for sharing.", 4:"The perfect luxury gift for a renowned chocoholic."},
  "260751": { 1:"Contains our best loved cakes and bakes, a perfect dessert and an indulgent afternoon tea alternative, created with all the flair, imagination and skill of an artisian chocolatier", 2:"Our best loved desserts recreated in 36% white chocolate and 40% milk.", 3:"We only use real natural ingredients to achieve the authentic taste found in our favourite desserts.", 4:"Perfect for serving as a quick and easy dessert or an indulgent afternoon tea."},
  "260743": { 1:"Perfect for sharing, contains our favourtie cakes and bakes, created with all the flair, imagination and skill of an artisian chocolatier", 2:"Our best loved desserts recreated in 36% white chocolate and 40% milk.", 3:"We only use real natural ingredients to achieve the authentic taste found in our favourite desserts.", 4:"Find 2 of nearly every flavour, perfect for a complete chocolate tasting adventure."},
  "263315": { 1:"Perfect for sharing, contains our favourtie cakes and bakes, a luxury gift for the dessert lover", 2:"Our best loved desserts recreated in 36% white chocolate and 40% milk.", 3:"We only use real natural ingredients to achieve the authentic taste found in our favourite desserts.", 4:"The perfect luxury gift for a renowned dessert lover."},
  "263322": { 1:"Three tires of our most iconic recipes, a 147 piece collection of filled and solid chocolayes and biscuits, an extra special gift for a loved one or show-stopping treat for guests", 2:"147-piece collection of our most iconic recipes.", 3:"Our cabinets store your chocolates safely, while creating a frisson of excitement when opening every drawer.", 4:"An extra-special gift for a loved one, or a show-stopping treat to serves guests."},
  "263319": { 1:"Jaw-dropping show stopper of our most iconic dark recipes, 55 filled and solid chocolates and biscuits in high cacao, ideal treat for the person who leans to the dark side of chocolate,", 2:"55-piece collection of our most celebrated dark chocolate recipes.", 3:"Our cabinets store your chocolates safely, while creating a frisson of excitement when opening the drawer.", 4:"An ideal treat for that person who always leans to the dark side of chocolate."},
  "263318": { 1:"A two-tier showcase of our most iconic chocolates, 59 filled and solid chocolates and biscuits, serve as a stunning centrepiece after dinner treat or a gift to that special person or simply dive in with friends and family", 2:"59-piece collection of our most iconic recipes.", 3:"Our cabinets store your chocolates safely, while creating a frisson of excitement when opening the drawer.", 4:"Perfect for a stunning centrepiece after dinner or a gift for that special person."}
};