export const socialData = {
    'home': {
        'Trending': {
            icon: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Estée Lauder Double Wear Stay-in-Place Foundation SPF 10 30ml",
                    image: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£29.75',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/estee-lauder-double-wear-stay-in-place-makeup-spf-10-30ml-10249140',
                },
                {
                    title: "No7 Swarovski The Ultimate Travel Palette",
                    image: 'http://boots.scene7.com/is/image/Boots/10292347%5F3cropped?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£15.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-swarovski-the-ultimate-travel-palette--10292347',
                },
                {
                    title: "Boots Protective FFP2 NR Face Masks 5 Single Use Respirators",
                    image: 'https://boots.scene7.com/is/image/Boots/10292473?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£9.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/boots-protective-ffp2-nr-face-masks-5s-10292473',
                },
                {
                    title: "Liz Earle Orange Flower Face & Body Collection",
                    image: 'https://boots.scene7.com/is/image/Boots/10307830?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£33.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/liz-earle-orange-flower-face-body-collection-10307830',
                },
                {
                    title: "Garnier 3.5% Vitamin C, Niacinamide, Salicylic Acid, Brightening & Anti Dark Spot Serum 30ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10305123%5F1?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£7.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/garnier-3-5-percent-vitamin-c-niacinamide-salicylic-acid-brightening-and-anti-dark-spot-serum-30ml-10305123',
                },
                {
                    title: "Soap & Glory A Blooming Glorious Collection",
                    image: 'https://boots.scene7.com/is/image/Boots/10306644%5F3cropped?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/soap-and-glory-a-blooming-glorious-collection-10306644',
                },
            ]
        },
        'New in': {
            icon: 'https://boots.scene7.com/is/image/Boots/VF?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Viktor and Rolf Flowerbomb Ruby Orchid Eau de Parfum 50ml",
                    image: 'https://boots.scene7.com/is/image/Boots/VF?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£67.57',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/viktor-and-rolf-flowerbomb-ruby-orchid-eau-de-parfum-50ml-10305668',
                },
                {
                    title: "Collagen Superdose By Gold Collagen Skin Care 300ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10303371?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£17.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/collagen-superdose-by-gold-collagen-skin-care-300ml-10303371',
                },
                {
                    title: "Berocca Immuno Effervescent Tablets Orange Flavour 15s",
                    image: 'https://boots.scene7.com/is/image/Boots/10308069?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£7.50',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/berocca-immuno-effervescent-tablets-orange-flavour-15s-10308069',
                },
                {
                    title: "Revolution Re-Loaded Palette Velvet Rose",
                    image: 'https://boots.scene7.com/is/image/Boots/10308786?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£5.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/revolution-re-loaded-palette-velvet-rose-10308786',
                },
                {
                    title: "Silicolgel 12 x 15ml Sachets",
                    image: 'https://boots.scene7.com/is/image/Boots/10300172?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£10.49',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/silicolgel-12-x-15ml-sachets-10300172',
                },
                {
                    title: "No7 Lash Extender Fiber Mascara Black 7ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10306561?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£14.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-lash-extender-fibre-mascara-black-7ml-10306561p',
                },
            ]
        },
        'Recommended': {
            icon: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Estée Lauder Double Wear Stay-in-Place Foundation SPF 10 30ml",
                    image: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£29.75',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/estee-lauder-double-wear-stay-in-place-makeup-spf-10-30ml-10249140',
                },
                {
                    title: 'Maybelline Lash Sensational Sky High Mascara 7.2ml',
                    image: 'https://boots.scene7.com/is/image/Boots/10291592?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£9.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/maybelline-lash-sensational-sky-high-mascara-10291592',
                },
                {
                    title: "Imedeen Prime Renewal - 120 Tablets",
                    image: 'https://boots.scene7.com/is/image/Boots/10042132?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£60.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/imedeen-prime-renewal-120-tablets-10042132',
                },
                {
                    title: "Hairburst Strawberry & Blackcurrant Chewable Vitamins 60 Pastilles",
                    image: 'https://boots.scene7.com/is/image/Boots/10223512?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£20.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/hairburst-strawberry-chewable-vits',
                },
                {
                    title: "Boots TENS Maternity Unit",
                    image: 'https://boots.scene7.com/is/image/Boots/10185535?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/boots-tens-maternity-unit-10185535',
                },
                {
                    title: 'No7 Protect & Perfect Intense ADVANCED Serum 30ml',
                    image: 'https://boots.scene7.com/is/image/Boots/10288490?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£24.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-protect-and-perfect-intense-advanced-serum-30ml-10288490',
                },
            ]
        },
        'Content': {
            icon: 'https://boots.scene7.com/is/image/Boots/How%2Dto%2Dbuy%2Dfragrance?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "How to buy fragrance",
                    image: 'https://boots.scene7.com/is/image/Boots/How%2Dto%2Dbuy%2Dfragrance?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/fragrance-advice/how-to-buy-fragrance',
                },
                {
                    title: "Beauty products to boost your mood & make you feel good",
                    image: 'https://boots.scene7.com/is/image/Boots/The%2Dbest%2Dfeel%2Dgood%2Dbeauty%2Dproducts%2Dfor%2Dyour%2Dmood%2Dmind%2Dand%2Dmake%2Dup%2Dbag?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/best-feel-good-beauty-products',
                },
                {
                    title: "How TikTok became the biggest thing in beauty",
                    image: 'https://boots.scene7.com/is/image/Boots/How%2DTikTok%2Dbecame%2Dthe%2Dbiggest%2Dthing%2Din%2Dbeauty?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/inspiration-advice/skincare-beauty-advice/makeup-tutorials/makeup-basics/how-tik-tok-made-beauty-big',
                },
                {
                    title: "5 easy ways to create an at-home beauty sanctuary",
                    image: 'https://boots.scene7.com/is/image/Boots/Your%2Dultimate%2Dguide%2Dto%2Dcreating%2Dan%2Dat%2Dhome%2Dbeauty%2Dsanctuary?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/how-to-create-a-beauty-sanctuary',
                },
                {
                    title: "Stress care is the new self-care",
                    image: 'https://boots.scene7.com/is/image/Boots/Stress%2Dcare%2Dthe%2Dnew%2Dself%2Dcare?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/stress-care-self-care',
                },
            ]
        },
        'No7': {
            icon: 'http://boots.scene7.com/is/image/Boots/10301973?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "No7 Protect & Perfect Intense ADVANCED Serum 75ml",
                    image: 'http://boots.scene7.com/is/image/Boots/10301973?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-protect-and-perfect-intense-advanced-serum-10301973',
                },
                {
                    title: "No7 Cleansing Melting Gel Cleanser 150ml",
                    image: 'http://boots.scene7.com/is/image/Boots/10312282?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£9.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/beauty/skincare/facial-skincare/cleanser-toner/no7-cleansing-melting-gel-cleanser-150ml-10312282',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation1?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation2?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation3?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
            ]
        },
    },
    'beauty': {
        'trending': {
            icon: 'https://boots.scene7.com/is/image/Boots/10312454?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Fenty Beauty Icon Semi-Matte Refillable Lipstick",
                    image: 'https://boots.scene7.com/is/image/Boots/10312454?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£15.30',
                    linkText: 'Shop now',
                    link: 'https://boots.scene7.com/is/image/Boots/10312454?scl=1&fmt=png-alpha',
                },
                {
                    title: "Liz Earle Cleanse & Glow Transforming Gel Cleanser 150ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10306453?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£24.50',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/liz-earle-cleanse-glow-transforming-gel-cleanser-150ml-10306453',
                },
                {
                    title: "DIOR Sauvage Eau de Toilette 100ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10199144?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£74.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/dior-sauvage-eau-de-toilette-100ml-10199144',
                },
                {
                    title: "Olay Vitamin C + AHA24 Day Gel Face Cream For Bright And Even Tone 50ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10305489?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£34.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/olay-vitamin-c-plus-aha24-day-gel-face-cream-for-bright-and-even-tone-50ml-10305489',
                },
                {
                    title: "CeraVe SA Smoothing Cleanser with Salicylic Acid 236ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10272454?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£12.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/cerave-sa-smoothing-cleanser-236ml-10272454',
                },
            ]
        },
        'New in': {
            icon: 'https://boots.scene7.com/is/image/Boots/VF?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Viktor and Rolf Flowerbomb Ruby Orchid Eau de Parfum 50ml",
                    image: 'https://boots.scene7.com/is/image/Boots/VF?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£67.57',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/viktor-and-rolf-flowerbomb-ruby-orchid-eau-de-parfum-50ml-10305668',
                },
                {
                    title: "Revolution Re-Loaded Palette Velvet Rose",
                    image: 'https://boots.scene7.com/is/image/Boots/10308786?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£5.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/revolution-re-loaded-palette-velvet-rose-10308786',
                },
                {
                    title: "No7 Lash Extender Fiber Mascara Black 7ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10306561?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£14.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-lash-extender-fibre-mascara-black-7ml-10306561p',
                },
                {
                    title: "Maybelline Colossal Curl Bounce Mascara",
                    image: 'https://boots.scene7.com/is/image/Boots/10307184?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£10.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/maybelline-colossal-curl-bounce-mascara-10307184',
                },
                {
                    title: "Ole Henriksen Strength Trainer Peptide Boost Moisturiser 50ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10303664?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£34.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/ole-henriksen-strength-trainer-peptide-boost-moisturizer-50ml-10303664'
                },
            ]
        },
        'Recommended': {
            icon: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Estée Lauder Double Wear Stay-in-Place Foundation SPF 10 30ml",
                    image: 'https://boots.scene7.com/is/image/Boots/EL?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£29.75',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/estee-lauder-double-wear-stay-in-place-makeup-spf-10-30ml-10249140',
                },
                {
                    title: 'Maybelline Lash Sensational Sky High Mascara 7.2ml',
                    image: 'https://boots.scene7.com/is/image/Boots/10291592?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£9.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/maybelline-lash-sensational-sky-high-mascara-10291592',
                },
                {
                    title: 'No7 Protect & Perfect Intense ADVANCED Serum 30ml',
                    image: 'https://boots.scene7.com/is/image/Boots/10288490?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£24.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-protect-and-perfect-intense-advanced-serum-30ml-10288490',
                },
                {
                    title: 'Boots Vitamin C Brightening Moisturising Cream',
                    image: 'https://boots.scene7.com/is/image/Boots/10271985?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£4.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/boots-vitamin-c-moisturising-cream-10271985',
                },
                {
                    title: 'Liz Earle Cleanse & Polish™ Hot Cloth Cleanser 200ml Starter Kit',
                    image: 'https://boots.scene7.com/is/image/Boots/10244713?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£30.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/liz-earle-cleanse-and-polish-starter-kit-200ml-10244713',
                },
            ]
        },
        'Content': {
            icon: 'https://boots.scene7.com/is/image/Boots/Our%2Dpick%2Dof%2Dthe%2Dbest%2Dbody%2Dscrubs%2Dskin%2Dboosting%2Dwinter%2Dbodycare?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "The Best Body Scrubs and Exfoliators for All Skin Types",
                    image: 'https://boots.scene7.com/is/image/Boots/Our%2Dpick%2Dof%2Dthe%2Dbest%2Dbody%2Dscrubs%2Dskin%2Dboosting%2Dwinter%2Dbodycare?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/inspiration-advice/skincare-beauty-advice/skincare-advice/skincare-routines/best-body-scrubs-and-exfoliators',
                },
                {
                    title: "15 of the best beauty products for dry skin 2021",
                    image: 'https://boots.scene7.com/is/image/Boots/15%2Dof%2Dthe%2Dbest%2Dbeauty%2Dproducts%2Dfor%2Ddry%2Dskin?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn More',
                    link: 'https://www.boots.com/inspiration-advice/skincare-beauty-advice/skincare-advice/skincare-basics/best-beauty-products-for-dry-skin',
                },
                {
                    title: "The best skincare routine and products",
                    image: 'https://boots.scene7.com/is/image/Boots/The%2Dbest%2Dskincare%2Droutine%2Dand%2Dproducts%2Dfor%2Dyour%2D40s?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn More',
                    link: 'https://www.boots.com/skincare-beauty-advice/skincare-advice/skincare-basics/best-skincare-routine-for-40s',
                },
                {
                    title: "The must-try probiotic skin care products of 2021",
                    image: 'https://boots.scene7.com/is/image/Boots/Probiotics%2Dand%2Dthe%2Dmicrobiome?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn More',
                    link: 'https://www.boots.com/skincare-beauty-advice/skincare-advice/skincare-basics/probiotic-skin-care',
                },
                {
                    title: "The Best Cleansers for Acne-Prone Skin 2021",
                    image: 'https://boots.scene7.com/is/image/Boots/10%2Dof%2Dthe%2Dbest%2Dcleansers%2Dand%2Dface%2Dwashes%2Dfor%2Dacne%2Dprone%2Dskin%201?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn More',
                    link: 'https://www.boots.com/cleanser-for-acne-prone-skin',
                },
            ]
        },
        'No7': {
            icon: 'http://boots.scene7.com/is/image/Boots/10301973?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "No7 Protect & Perfect Intense ADVANCED Serum 75ml",
                    image: 'http://boots.scene7.com/is/image/Boots/10301973?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-protect-and-perfect-intense-advanced-serum-10301973',
                },
                {
                    title: "No7 Cleansing Melting Gel Cleanser 150ml",
                    image: 'http://boots.scene7.com/is/image/Boots/10312282?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£9.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/beauty/skincare/facial-skincare/cleanser-toner/no7-cleansing-melting-gel-cleanser-150ml-10312282',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation1?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation2?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
                {
                    title: "No7 Restore & Renew Serum Foundation 30ml SPF 30",
                    image: 'https://boots.scene7.com/is/image/Boots/foundation3?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    text: '£19.95',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/no7-restore-and-renew-serum-foundation-30ml-spf-30-10300813',
                },
            ]
        },

    },
    'health': {
        'trending': {
            icon: 'https://boots.scene7.com/is/image/Boots/10311087?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Boots Protective Type IIR Face Masks 10s",
                    image: 'https://boots.scene7.com/is/image/Boots/10311087?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£5.50',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/boots-protective-type-ii-face-masks-10s-10299849',
                },
                {
                    title: "Gold Collagen Forte 10 Day Programme",
                    image: 'https://boots.scene7.com/is/image/Boots/10181841?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£35.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/gold-collagen-forte-10-x-50ml-10181841',
                },
                {
                    title: "Polytar Scalp Shampoo Coal Tar Solution 4%",
                    image: 'https://boots.scene7.com/is/image/Boots/10020476?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£6.40',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/polytar-scalp-shampoo-coal-tar-solution-10020476',
                },
                {
                    title: "Clearblue Advanced Digital Ovulation Test Kit",
                    image: 'https://boots.scene7.com/is/image/Boots/10154162?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£19.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/clearblue-digital-ovulation-test-with-dual-hormone-indicator-10s-10154162',
                },
                {
                    title: "Revive Collagen Tropical Flavoured Drink Supplement 10,000mg",
                    image: 'https://boots.scene7.com/is/image/Boots/10305465?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/revive-collagen-tropical-flavoured-drink-supplement-10000mg-14-x-22g-sachets-10305465',
                },
                {
                    title: "Sterimar Isotonic Nasal Hygiene Spray 100ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10028386?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£7.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/sterimar-isotonic-nasal-hygiene-spray-100ml-10028386',
                },
                {
                    title: "Lovehoney 10 Function Frisky Rabbit Vibrator",
                    image: 'https://boots.scene7.com/is/image/Boots/10271015?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£24.99',
                    linkText: 'Shop now',
                    link: 'https://boots.scene7.com/is/image/Boots/10271015?scl=1&fmt=png-alpha',
                },
                
            ]
        },
        'New in': {
            icon: 'https://boots.scene7.com/is/image/Boots/10305465?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Revive Collagen Tropical Flavoured Drink Supplement 10,000mg",
                    image: 'https://boots.scene7.com/is/image/Boots/10305465?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/revive-collagen-tropical-flavoured-drink-supplement-10000mg-14-x-22g-sachets-10305465',
                },
                {
                    title: "Collagen Superdose By Gold Collagen Skin Care 300ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10303371?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£17.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/collagen-superdose-by-gold-collagen-skin-care-300ml-10303371',
                },
                {
                    title: "Silicolgel 12 x 15ml Sachets",
                    image: 'https://boots.scene7.com/is/image/Boots/10300172?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£10.49',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/silicolgel-12-x-15ml-sachets-10300172',
                },
                {
                    title: "Berocca Immuno Effervescent Tablets Orange Flavour 15s",
                    image: 'https://boots.scene7.com/is/image/Boots/10308069?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£7.50',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/berocca-immuno-effervescent-tablets-orange-flavour-15s-10308069',
                },
                {
                    title: "Otrivine Natural Daily Nasal Wash 100ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10300783?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£8.69',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/otrivine-natural-daily-nasal-wash-100ml-10300783',
                },
                {
                    title: "Primal Strength Premium Home Dumbbell Pair 1kg",
                    image: 'https://boots.scene7.com/is/image/Boots/10305084?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£8.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/primal-strength-premium-home-dumbbell-pair-1kg-10305084',
                },
            ]
        },
        'Recommended': {
            icon: 'https://boots.scene7.com/is/image/Boots/10042132?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "Imedeen Prime Renewal - 120 Tablets",
                    image: 'https://boots.scene7.com/is/image/Boots/10042132?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£60.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/imedeen-prime-renewal-120-tablets-10042132',
                },
                {
                    title: "Hairburst Strawberry & Blackcurrant Chewable Vitamins 60 Pastilles",
                    image: 'https://boots.scene7.com/is/image/Boots/10223512?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£20.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/hairburst-strawberry-chewable-vits',
                },
                {
                    title: "Hycosan Extra Preservative Free Eye Drops - 7.5ml",
                    image: 'https://boots.scene7.com/is/image/Boots/10172236?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£12.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/hycosan-extra-preservative-free-eye-drops-7-5ml-10172236',
                },
                {
                    title: "Boots TENS Maternity Unit",
                    image: 'https://boots.scene7.com/is/image/Boots/10185535?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£39.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/boots-tens-maternity-unit-10185535',
                },
                {
                    title: "Acnecide 5% w/w Gel - 30g",
                    image: 'https://boots.scene7.com/is/image/Boots/10187571?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£10.49',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/acnecide-gel-30g-10187571',
                },
                {
                    title: "Ensure NutriVigor Shake Vanilla Flavour",
                    image: 'https://boots.scene7.com/is/image/Boots/10273223?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£10.00',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/ensure-nutrivigor-shake-vanilla-400g-10273223',
                },
                {
                    title: "Lovehoney Ignite 20 Function Rechargeable Mini Wand Vibrator",
                    image: 'https://boots.scene7.com/is/image/Boots/10290065?scl=1&fmt=png-alpha',
                    imageType: 'contain',
                    text: '£29.99',
                    linkText: 'Shop now',
                    link: 'https://www.boots.com/lovehoney-ignite-rechargeable-mini-wand-10290065',
                },
            ]
        },
        'Content': {
            icon: 'https://boots.scene7.com/is/image/Boots/Whatnottosayandwhattosayinsteadtosomeonestrugglingwiththeirmentalhealth%201?scl=1&fmt=png-alpha',
            carousel: [
                {
                    title: "What to say to someone with a mental health condition",
                    image: 'https://boots.scene7.com/is/image/Boots/Whatnottosayandwhattosayinsteadtosomeonestrugglingwiththeirmentalhealth%201?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/what-to-say-to-someone-struggling-with-their-mental-health',
                },
                {
                    title: "How do I treat hay fever?",
                    image: 'https://boots.scene7.com/is/image/Boots/online%2Ddoctor%5Fhayfever%5Fdecorative%2Dpanel%5FA%201?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/inspiration-advice/health/allergy-and-hayfever/treating-hayfever',
                },
                {
                    title: "What are food allergies & intolerances?",
                    image: 'https://boots.scene7.com/is/image/Boots/inspiration%2Dadvice%2Dwellness%2Dnutrition%2Dwhat%2Dare%2Dfree%2Dfrom%2Dfoods%2D1360x502?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/inspiration-advice/health/allergy-and-hayfever/food-allergy-intolerances',
                },
                {
                    title: "Cold & flu remedies",
                    image: 'https://boots.scene7.com/is/image/Boots/19%2D11%2Dboots%2Dpharmaceuticals%2Dbt%2Dcolds%2Dbuild4?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/cold-and-flu/cold-and-flu-remedies',
                },
                {
                    title: "Difference between gluten intolerance & coeliac disease",
                    image: 'https://boots.scene7.com/is/image/Boots/inspiration%2Dadvice%2Dhealth%2Ddigestion%2Dhub%2Dhero%2D1360x502%201?scl=1&fmt=png-alpha',
                    imageType: 'cover',
                    linkText: 'Learn more',
                    link: 'https://www.boots.com/other-digestive-problems/gluten-intolerance-and-coeliac-disease',
                },
            ]
        },
    },
}