export default {
  "/301-315-414/make-up/lips/lipstick": { "persona":"DAILY MAKEUP", "category":"LIPSTICK"},
  "/301-315-1002/make-up/lips/liquid-lipstick": { "persona":"DAILY MAKEUP", "category":"LIQUID LIPSTICK"},
  "/301-315-415/make-up/lips/lip-gloss": { "persona":"DAILY MAKEUP", "category":"LIP GLOSS"},
  "/301-315-882/make-up/lips/lip-oil": { "persona":"DAILY MAKEUP", "category":"LIP OIL"},
  "/301-315-598/make-up/lips/lip-kits": { "persona":"DAILY MAKEUP", "category":"LIP KITS"},
  "/301-317-422/make-up/face/foundation": { "persona":"DAILY MAKEUP", "category":"FOUNDATION"},
  "/301-317-873/make-up/face/liquid": { "persona":"DAILY MAKEUP", "category":"LIQUID FOUNDATION"},
  "/301-317-424/make-up/face/powder": { "persona":"DAILY MAKEUP", "category":"FOUNDATION POWDER"},
  "/301-317-863/make-up/face/compact": { "persona":"DAILY MAKEUP", "category":"FOUNDATION COMPACT"},
  "/301-317-427/make-up/face/prime-set": { "persona":"DAILY MAKEUP", "category":"PRIMER"},
  "/301-317-423/make-up/face/concealer": { "persona":"DAILY MAKEUP", "category":"CONCEALER"},
  "/301-317-425/make-up/face/blusher": { "persona":"DAILY MAKEUP", "category":"BLUSHER"},
  "/301-317-550/make-up/face/bronzer": { "persona":"DAILY MAKEUP", "category":"BRONZER"},
  "/301-317-426/make-up/face/highlighter": { "persona":"DAILY MAKEUP", "category":"HIGHLIGHTER"},
  "/301-316-418/make-up/eyes/mascara": { "persona":"DAILY MAKEUP", "category":"MASCARA"},
  "/301-316-421/make-up/eyes/brows": { "persona":"DAILY MAKEUP", "category":"BROWS"},
  "/301-316-420/make-up/eyes/eyeliner": { "persona":"DAILY MAKEUP", "category":"EYELINER"},
  "/301-319/make-up/make-up-brushes": { "persona":"DAILY MAKEUP", "category":"MAKEUP BRUSHES"},
  "/301-1000/make-up/tools-accessories": { "persona":"DAILY MAKEUP", "category":"MAKE-UP TOOLS & ACCESSORIES"},
  "/304-920-893/perfume/womens-fragrance/purse-sprays": { "persona":"DAILY MAKEUP", "category":"PURSE SPRAYS"},
  "/304-920-565/perfume/womens-fragrance/body-lotions": { "persona":"DAILY MAKEUP", "category":"BODY LOTIONS"},
  "/304-920-890/perfume/womens-fragrance/body-sprays": { "persona":"DAILY MAKEUP", "category":"BODY SPRAYS"},
  "/304-920-891/perfume/womens-fragrance/body-mists": { "persona":"DAILY MAKEUP", "category":"BODY MISTS"},
  "/304-920-568/perfume/womens-fragrance/body-powder": { "persona":"DAILY MAKEUP", "category":"BODY POWDER"},
  "/855-434/fashion/womenswear": { "persona":"DAILY MAKEUP", "category":"WOMENSWEAR"},
  "/855-1053/fashion/shapewear": { "persona":"DAILY MAKEUP", "category":"SHAPEWEAR"},
  "/313-609/sale/perfume-sale": { "persona":"DAILY MAKEUP", "category":"PERFUME SALE"},
  "/932-1048/distillery/make-up": { "persona":"DAILY MAKEUP", "category":"DISTILLERY MAKEUP"},
  "/301-315-416/make-up/lips/lip-liner": { "persona":"GLAM & TREAT", "category":"LIP LINER"},
  "/301-316-419/make-up/eyes/eyeshadow": { "persona":"GLAM & TREAT", "category":"EYESHADOW"},
  "/301-316-948/make-up/eyes/eyeshadow-palettes": { "persona":"GLAM & TREAT", "category":"EYESHADOW PALETTES"},
  "/301-318-445/make-up/nails/gel-nail": { "persona":"GLAM & TREAT", "category":"NAIL GEL"},
  "/301-318-428/make-up/nails/nail-colour": { "persona":"GLAM & TREAT", "category":"NAIL COLOUR"},
  "/302-554/skincare/face-masks": { "persona":"GLAM & TREAT", "category":"FACE MASKS"},
  "/304-920-912/perfume/womens-fragrance/fragrance-sets": { "persona":"GLAM & TREAT", "category":"FRAGRANCE SETS"},
  "/306-342/toiletries/bubble-bath": { "persona":"GLAM & TREAT", "category":"BUBBLE BATH"},
  "/306-343-924/toiletries/shower/shower-bath-oils": { "persona":"GLAM & TREAT", "category":"SHOWER BATH OILS"},
  "/306-347/toiletries/face-masks": { "persona":"GLAM & TREAT", "category":"FACE MASKS"},
  "/306-949/toiletries/aromatherapy": { "persona":"GLAM & TREAT", "category":"AROMATHERAPY"},
  "/855-725/fashion/bags-purses": { "persona":"GLAM & TREAT", "category":"BAGS / PURSES"},
  "/855-473/fashion/nightwear": { "persona":"GLAM & TREAT", "category":"NIGHTWEAR"},
  "/855-481/fashion/lingerie": { "persona":"GLAM & TREAT", "category":"LINGERIE"},
  "/855-491/fashion/jewellery": { "persona":"GLAM & TREAT", "category":"JEWELLERY"},
  "/855-616/fashion/accessories": { "persona":"GLAM & TREAT", "category":"ACCESSORIES"},
  "/855-492/fashion/watches": { "persona":"GLAM & TREAT", "category":"WATCHES"},
  "/855-474/fashion/footwear": { "persona":"GLAM & TREAT", "category":"FOOTWEAR"},
  "/310-399/home-gifts/home-accessories": { "persona":"GLAM & TREAT", "category":"HOME ACCESSORIES"},
  "/310-1066/home-gifts/wellbeing": { "persona":"GLAM & TREAT", "category":"WELLBEING"},
  "/310-465/home-gifts/home-fragrance": { "persona":"GLAM & TREAT", "category":"HOME FRAGRANCE"},
  "/310-480/home-gifts/gadgets": { "persona":"GLAM & TREAT", "category":"GADGETS"},
  "/310-642/home-gifts/kitchen": { "persona":"GLAM & TREAT", "category":"KITCHEN"},
  "/313-485/sale/fashion-sale": { "persona":"GLAM & TREAT", "category":"FASHION SALE"},
  "/313-487/sale/home-gift-sale": { "persona":"GLAM & TREAT", "category":"HOME & GIFTS SALE"},
  "/313-535/sale/jewellery-sale": { "persona":"GLAM & TREAT", "category":"JEWELLERY SALE"},
  "/313-657/sale/nightwear": { "persona":"GLAM & TREAT", "category":"NIGHTWEAR SALE"},
  "/313-826/sale/hair-colours-sale": { "persona":"GLAM & TREAT", "category":"HAIR COLOURS SALE"},
  "/832-833/beauty-sets/fragrance-sets": { "persona":"GLAM & TREAT", "category":"FRAGRANCE SETS"},
  "/1063/wellbeing": { "persona":"GLAM & TREAT", "category":"WELLBEING"},
  "/309/lingerie": { "persona":"GLAM & TREAT", "category":"LINGERIE"},
  "/308/jewellery-watches": { "persona":"GLAM & TREAT", "category":"JEWELLERY & WATCHES"},
  "/301-315-417/make-up/lips/lip-care": { "persona":"HEALTH ROUTINE", "category":"LIP CARE"},
  "/301-318-429/make-up/nails/nail-care": { "persona":"HEALTH ROUTINE", "category":"NAIL CARE"},
  "/302-331/skincare/anti-ageing": { "persona":"HEALTH ROUTINE", "category":"ANTI-AGEING SKINCARE"},
  "/302-583/skincare/moisturisers": { "persona":"HEALTH ROUTINE", "category":"MOISTURISERS"},
  "/302-333/skincare/cleansers": { "persona":"HEALTH ROUTINE", "category":"CLEANSERS"},
  "/302-330/skincare/eye-creams": { "persona":"HEALTH ROUTINE", "category":"EYE CREAMS"},
  "/302-555/skincare/serums-treatments": { "persona":"HEALTH ROUTINE", "category":"SERUMS & TREATMENTS"},
  "/302-335/skincare/skincare-sets": { "persona":"HEALTH ROUTINE", "category":"SKINCARE SETS"},
  "/302-556/skincare/tools-accessories": { "persona":"HEALTH ROUTINE", "category":"SKINCARE TOOLS & ACCESSORIES"},
  "/302-552/skincare/hand-cream": { "persona":"HEALTH ROUTINE", "category":"HAND CREAM"},
  "/304-920-894/perfume/womens-fragrance/roll-on-deodorant": { "persona":"HEALTH ROUTINE", "category":"ROLL ON DEODERANT"},
  "/306-446/toiletries/dry-oil-sprays": { "persona":"HEALTH ROUTINE", "category":"DRY OIL SPRAYS"},
  "/306-345/toiletries/body-moisturiser": { "persona":"HEALTH ROUTINE", "category":"BODY MOISTURISER"},
  "/306-343-921/toiletries/shower/shower-gels": { "persona":"HEALTH ROUTINE", "category":"SHOWER GELS"},
  "/306-343-922/toiletries/shower/shower-cremes": { "persona":"HEALTH ROUTINE", "category":"SHOWER CREMES"},
  "/306-343-1001/toiletries/shower/shower-accessories": { "persona":"HEALTH ROUTINE", "category":"SHOWER ACCESSORIES"},
  "/306-571/toiletries/haircare": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE"},
  "/306-346/toiletries/hand-care": { "persona":"HEALTH ROUTINE", "category":"HAND CARE"},
  "/306-348/toiletries/foot-care": { "persona":"HEALTH ROUTINE", "category":"FOOT CARE"},
  "/306-930/toiletries/toiletries-sets": { "persona":"HEALTH ROUTINE", "category":"TOILETRIES SETS"},
  "/306-352/toiletries/body-sprays-mist": { "persona":"HEALTH ROUTINE", "category":"BODY SPRAYS & MISTS"},
  "/306-351/toiletries/deodorants": { "persona":"HEALTH ROUTINE", "category":"DEODERANTS"},
  "/306-350/toiletries/hair-removal": { "persona":"HEALTH ROUTINE", "category":"HAIR REMOVAL"},
  "/310-579/home-gifts/health-fitness": { "persona":"HEALTH ROUTINE", "category":"HEALTH & FITNESS"},
  "/313-870/sale/haircare-sale": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE SALE"},
  "/313-662/sale/skincare-sale": { "persona":"HEALTH ROUTINE", "category":"SKINCARE SALE"},
  "/313-663/sale/toiletries-sale": { "persona":"HEALTH ROUTINE", "category":"TOILETRIES SALE"},
  "/932-1049/distillery/skincare": { "persona":"HEALTH ROUTINE", "category":"DISTILLERY SKINCARE"},
  "/932-937/distillery/distillery-skincare-kits": { "persona":"HEALTH ROUTINE", "category":"DISTILLERY SKINCARE SETS"},
  "/832-834/beauty-sets/skincare-sets": { "persona":"HEALTH ROUTINE", "category":"SKINCARE SETS"},
  "/832-835/beauty-sets/toiletries-sets": { "persona":"HEALTH ROUTINE", "category":"TOILETRIES SAETS"},
  "/307/haircare": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE"},
  "/307-360/haircare/shampoo": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE - SHAMPOO"},
  "/307-361/haircare/conditioner": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE - CONDITIONER"},
  "/306-571-572/toiletries/haircare/shampoo": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE - SHAMPOO"},
  "/306-571-573/toiletries/haircare/conditioner": { "persona":"HEALTH ROUTINE", "category":"HAIRCARE - CONDITIONER"},
};
