export default {
  "A" : {
    "Access Equipment (all)": "https://www.hss.com/hire/c/access",
    "Access Towers and Platforms": "https://www.hss.com/hire/c/access/access-towers-and-platforms",
    "Air Breakers": "https://www.hss.com/hire/c/breaking-and-drilling/air-breakers",
    "Air Compressors": "https://www.hss.com/hire/c/breaking-and-drilling/air-compressors",
    "Air Conditioners": "https://www.hss.com/hire/c/cooling/air-conditioners",
    "Angle grinder": "https://www.hss.com/hire/c/sawing-and-cutting/metal-grinding",
  },
  "B" : {
    "Belt sander": "N/A",
    "Boiler Hire Services": "https://www.hss.com/hire/c/heating/boiler-hire-services",
    "Breakers": "https://www.hss.com/hire/c/breaking-and-drilling/",
    "Breaking (all)": "https://www.hss.com/hire/c/breaking-and-drilling",
    "Broachers": "https://www.hss.com/hire/c/breaking-and-drilling/broachers",
    "Brush cutter": "https://www.hss.com/hire/p/brush-cutter-strimmer-petrol",
    "Building and Siteworks (all)": "https://www.hss.com/hire/c/building-and-siteworks",
  },
  "C" : {
    "Cable Handling": "https://www.hss.com/hire/c/lifting-and-handling/cable-handling",
    "Carpet": "? Not sure about this",
    "Carpet Cleaners": "https://www.hss.com/hire/c/cleaning-and-floorcare/carpet-cleaners",
    "Chainsaws": "https://www.hss.com/hire/p/chainsaw-15in-petrol-2152-or-353",
    "Cherry Pickers": "https://www.hss.com/hire/c/access/",
    "Chiller Hire Services": "https://www.hss.com/hire/c/cooling/chiller-hire-services",
    "Chippers": "https://www.hss.com/hire/c/gardening-and-landscaping/garden-shredders-and-wood-chippers",
    "Chipping Hammers": "https://www.hss.com/hire/c/breaking-and-drilling/chipping-hammers",
    "Circular saws": "https://www.hss.com/hire/c/sawing-and-cutting/timber-cutting",
    "Clamps": "https://www.hss.com/hire/c/lifting-and-handling/clamps",
    "Cleaning (all)": "https://www.hss.com/hire/c/cleaning-and-floorcare",
    "Clearance and Fencing": "https://www.hss.com/hire/c/gardening-and-landscaping/clearance-and-fencing",
    "Combi-Hammers": "https://www.hss.com/hire/c/breaking-and-drilling/combi-hammers",
    "Compactors": "https://www.hss.com/hire/c/concreting-and-compaction/cutting-and-compaction",
    "Concrete & Cement Mixers": "https://www.hss.com/hire/c/concreting-and-compaction/concrete-cement-mixers",
    "Concrete breakers": "https://www.hss.com/hire/c/breaking-and-drilling/",
    "Concrete mixers": "https://www.hss.com/hire/c/concreting-and-compaction/concrete-cement-mixers",
    "Concreting": "https://www.hss.com/hire/c/concreting-and-compaction/concreting",
    "Concreting and Compaction (all)": "https://www.hss.com/hire/c/concreting-and-compaction",
    "Confined Space": "https://www.hss.com/hire/c/safety-ventilation-extraction/confined-space",
    "Conveyors": "https://www.hss.com/hire/c/lifting-and-handling/conveyors",
    "Cooling": "https://www.hss.com/hire/c/cooling",
    "Cooling Fans": "https://www.hss.com/hire/c/cooling/cooling-fans",
    "Cordless Drills": "https://www.hss.com/hire/c/breaking-and-drilling/cordless-drills",
    "Cordless Saws": "https://www.hss.com/hire/c/sawing-and-cutting/cordless-saws",
    "Core drill": "? Not sure about this",
    "Core Drill Accessories": "https://www.hss.com/hire/c/breaking-and-drilling/core-drill-accessories",
    "Cranes": "https://www.hss.com/hire/c/lifting-and-handling/cranes",
    "Cutting and Compaction": "https://www.hss.com/hire/c/concreting-and-compaction/cutting-and-compaction",
    "Cylinders and Jacks": "https://www.hss.com/hire/c/lifting-and-handling/cylinders-and-jacks",
  },
  "D" : {
    "Decorating": "https://www.hss.com/hire/c/painting-and-decorating/decorating",
    "Decorating (all)": "https://www.hss.com/hire/c/painting-and-decorating",
    "Dehumidifiers": "https://www.hss.com/hire/search?text=Dehumidifier",
    "Diamond Drills": "https://www.hss.com/hire/c/breaking-and-drilling/diamond-drills",
    "Diggers": "N/A",
    "Direct Fuel Heaters": "https://www.hss.com/hire/c/heating/direct-fuel-heaters",
    "Disc cutters": "https://www.hss.com/hire/c/sawing-and-cutting/",
    "Drain Clearance, Inspection and Maintenance": "https://www.hss.com/hire/c/plumbing-and-pipework/drain-clearance-inspection-and-maintenance",
    "Drilling (all)": "https://www.hss.com/hire/c/breaking-and-drilling",
    "Drilling Accessories": "https://www.hss.com/hire/c/breaking-and-drilling/drilling-accessories",
    "Drills": "https://www.hss.com/hire/c/breaking-and-drilling/",
    "Dryers and Dehumidifiers": "https://www.hss.com/hire/c/pumping-and-drying/dryers",
    "Drying (all)": "https://www.hss.com/hire/c/pumping-and-drying",
    "Dumpers": "https://www.hss.com/hire/p/mini-dumper-0-25-ton",
    "Dust Accessories": "https://www.hss.com/hire/c/breaking-and-drilling/dust-accessories",
  },
  "E" : {
    "Eex Safety Lighting": "https://www.hss.com/hire/c/lighting/eex-safety-lighting",
    "Electric and Bi Energy Boom Lifts": "https://www.hss.com/hire/c/access/electric-and-bi-energy-boom-lifts",
    "Electric and Bi Energy Boom Lifts": "https://www.hss.com/hire/c/powered-access/electric-and-bi-energy-boom-lifts",
    "Electric Breakers": "https://www.hss.com/hire/c/breaking-and-drilling/electric-breakers",
    "Electric Heaters": "https://www.hss.com/hire/c/heating/electric-heaters",
    "Electric Scissor Lifts": "https://www.hss.com/hire/c/access/electric-scissor-lifts",
    "Electric Scissor Lifts": "https://www.hss.com/hire/c/powered-access/electric-scissor-lifts",
    "Electrical Accessories": "https://www.hss.com/hire/c/power/electrical-accessories",
    "Evaporative Coolers": "https://www.hss.com/hire/c/cooling/coolers",
    "Excavators": "https://www.hss.com/hire/c/building-and-siteworks/excavators",
    "Extraction and Screening": "https://www.hss.com/hire/c/welding/extraction-and-screening",
  },
  "F" : {
    "Fall Arresters and Height Safety": "https://www.hss.com/hire/c/safety-ventilation-extraction/fall-arresters-and-height-safety",
    "Fan - Portable Heater Fan": "https://www.hss.com/hire/p/retail-fan-heater-2-8kw",
    "Fans": "See below as fans could be in many places",
    "Fans - Cooling Fans": "https://www.hss.com/hire/c/cooling/cooling-fans",
    "Fans - Industrial Fan Heaters": "https://www.hss.com/all-seasons-hire/c/heaters-ash/",
    "Fencing": "https://www.hss.com/hire/c/gardening-and-landscaping/clearance-and-fencing",
    "Fire Safety": "https://www.hss.com/hire/c/safety-ventilation-extraction/fire-safety",
    "Fixing": "https://www.hss.com/hire/c/sanding-and-fixing/fixing",
    "Floor Sanders": "https://www.hss.com/hire/c/sanding-and-fixing/floor-sanders",
    "Floor Sanding Equipment": "https://www.hss.com/hire/c/sanding-and-fixing/floor-sanders",
    "Floor Scrubbers": "https://www.hss.com/hire/c/cleaning-and-floorcare/floor-scrubbers",
    "Floorcare": "https://www.hss.com/hire/c/cleaning-and-floorcare/floorcare",
    "Forklifts and Attachments": "https://www.hss.com/hire/c/lifting-and-handling/forklift-attachments",
  },
  "G" : {
    "Gantries": "https://www.hss.com/hire/c/lifting-and-handling/gantries",
    "Garden Clearance": "https://www.hss.com/hire/c/gardening-and-landscaping/garden-clearance",
    "Garden shredders": "https://www.hss.com/hire/c/gardening-and-landscaping/garden-shredders-and-wood-chippers",
    "Gardening (all)": "https://www.hss.com/hire/c/gardening-and-landscaping",
    "Gas Detection": "https://www.hss.com/hire/c/safety-ventilation-extraction/gas-detection",
    "General Drills": "https://www.hss.com/hire/c/breaking-and-drilling/general-drills",
    "Generators": "https://www.hss.com/hire/c/power/generators",
    "Genie Lifts": "https://www.hss.com/hire/c/lifting-and-handling/material-lifts",
    "Grinders": "https://www.hss.com/hire/c/sawing-and-cutting/metal-grinding",
  },
  "H" : {
    "Hammer Drills": "https://www.hss.com/hire/c/breaking-and-drilling/hammer-drills",
    "Handling": "https://www.hss.com/hire/c/lifting-and-handling",
    "Heating (all)": "https://www.hss.com/hire/c/heating",
    "Hedge and Tree Cutting": "https://www.hss.com/hire/c/gardening-and-landscaping/hedge-and-tree-cutting",
    "Hedge trimmers": "https://www.hss.com/hire/c/gardening-and-landscaping/hedge-and-tree-cutting",
    "Hoists": "https://www.hss.com/hire/c/lifting-and-handling/hoists-and-slings",
    "Hoovers": "https://www.hss.com/hire/c/cleaning-and-floorcare/vacuum-cleaners",
  },
  "I" : {
    "Indirect Fuel Heaters": "https://www.hss.com/hire/c/heating/indirect-fuel-heaters",
    "Inspection & Measuring": "https://www.hss.com/hire/c/surveying-and-location/inspection-and-measuring",
  },
  "J" : {
    "Jack hammers": "https://www.hss.com/hire/c/breaking-and-drilling/",
    "Jet washers": "https://www.hss.com/hire/c/cleaning-and-floorcare/pressure-washers",
    "Joinery": "https://www.hss.com/hire/c/sawing-and-cutting/woodworking-and-joinery",
    "Junction Boxes": "https://www.hss.com/hire/c/power/junction-boxes-and-splitters",
  },
  "K" : {},
  "L" : {
    "Ladders and Steps": "https://www.hss.com/hire/c/access/ladders-and-steps",
    "Landscaping (all)": "",
    "Lasers and Levels": "https://www.hss.com/hire/c/surveying-and-location/lasers-and-levels",
    "Lawn Care": "https://www.hss.com/hire/c/gardening-and-landscaping/lawn-care",
    "Lawn mowers": "https://www.hss.com/hire/c/gardening-and-landscaping/lawn-care",
    "LED Lighting": "https://www.hss.com/hire/c/lighting/led-lighting",
    "Lifting": "https://www.hss.com/hire/c/lifting-and-handling",
    "Lighting (all)": "https://www.hss.com/hire/c/lighting",
    "Lighting Towers": "https://www.hss.com/hire/c/lighting/lighting-towers",
    "Load Testing and Weights": "https://www.hss.com/hire/c/lifting-and-handling/load-testing-and-weights",
    "Locators": "https://www.hss.com/hire/c/surveying-and-location/locators",
    "Log splitters": "N/A",
    "Low Level Access": "https://www.hss.com/hire/c/access/low-level-access",
    "Low Level Access": "https://www.hss.com/hire/c/powered-access/low-level-access",
  },
  "M" : {
    "Masonry Cutting": "https://www.hss.com/hire/c/sawing-and-cutting/masonry-cutting",
    "Material Hoists": "https://www.hss.com/hire/c/lifting-and-handling/material-hoists",
    "Material Lifts": "https://www.hss.com/hire/c/lifting-and-handling/material-lifts",
    "Metal Cutting": "https://www.hss.com/hire/c/sawing-and-cutting/metal-cutting",
    "Metal Grinding": "https://www.hss.com/hire/c/sawing-and-cutting/metal-grinding",
    "Mini Diggers": "N/A",
    "Mitre Saws": "https://www.hss.com/hire/c/sawing-and-cutting/",
    "Mixers": "https://www.hss.com/hire/c/concreting-and-compaction/concrete-cement-mixers",
    "MMA and TIG Inverters": "https://www.hss.com/hire/c/welding/mma-and-tig-inverters",
    "Mowers": "https://www.hss.com/hire/c/gardening-and-landscaping/lawn-care",
  },
  "N" : {
    "Nail Gun": "https://www.hss.com/hire/c/sanding-and-fixing/fixing",
  },
  "O" : {
    "Orbital and Belt Sanders": "https://www.hss.com/hire/c/sanding-and-fixing/orbital-and-belt-sanders",
  },
  "P" : {
    "Packing": "https://www.hss.com/hire/c/lifting-and-handling/packing",
    "Paint Sprayer": "https://www.hss.com/hire/c/painting-and-decorating/spray-systems",
    "Painting (all)": "https://www.hss.com/hire/c/painting-and-decorating",
    "Pallet truck": "https://www.hss.com/hire/c/lifting-and-handling/trucks-and-trolleys",
    "Petrol Breakers": "https://www.hss.com/hire/c/breaking-and-drilling/petrol-breakers",
    "Petrol strimmers": "https://www.hss.com/hire/search?text=Petrol+strimmers",
    "Pipe Bending and Forming": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-bending-and-forming",
    "Pipe Cutting": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-cutting",
    "Pipe Freezing, Flushing and Testing": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-freezing-flushing-and-testing",
    "Pipe Pressing": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-pressing",
    "Pipe Storage and Benches": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-storage-and-benches",
    "Pipe Threading": "https://www.hss.com/hire/c/plumbing-and-pipework/pipe-threading",
    "Pipework (all)": "",
    "Platforms": "https://www.hss.com/hire/search?text=Platforms",
    "Plumbing (all)": "https://www.hss.com/hire/c/plumbing-and-pipework",
    "Podium": "https://www.hss.com/hire/c/access/",
    "Power (all)": "https://www.hss.com/hire/c/power",
    "Power Cleaners": "https://www.hss.com/hire/c/cleaning-and-floorcare/pressure-washers",
    "Power washers": "https://www.hss.com/hire/search?text=Power+washers",
    "Powered Access (all)": "https://www.hss.com/hire/c/powered-access",
    "Pressure Washers": "https://www.hss.com/hire/c/cleaning-and-floorcare/pressure-washers",
    "Pumping and Pumps": "https://www.hss.com/hire/c/pumping-and-drying/pumping-and-pumps",
  },
  "Q" : {},
  "R" : {
    "Radiant Heaters": "https://www.hss.com/hire/c/heating/radiant-heaters",
    "Rescue": "https://www.hss.com/hire/c/safety-ventilation-extraction/rescue",
    "Roadworks": "https://www.hss.com/hire/c/building-and-siteworks/roadworks",
    "Rollers": "https://www.hss.com/hire/search?text=Rollers",
    "Roof ladders": "https://www.hss.com/hire/search?text=Roof+ladders",
    "Roofing and Support": "https://www.hss.com/hire/c/building-and-siteworks/roofing-and-support",
    "Rotavators": "https://www.hss.com/hire/search?text=rotavator",
  },
  "S" : {
    "Safety, Ventilation and Extraction (all)": "https://www.hss.com/hire/c/safety-ventilation-extraction",
    "Sand blasters": "https://www.hss.com/hire/search?text=Sand+blasters",
    "Sanders ": "https://www.hss.com/hire/c/sanding-and-fixing",
    "Sawing and Cutting (all)": "https://www.hss.com/hire/c/sawing-and-cutting",
    "Scaffold tower": "https://www.hss.com/hire/search?text=Scaffold+tower",
    "Scaffolding": "https://www.hss.com/hire/search?text=Scaffolding",
    "Scarifier": "https://www.hss.com/hire/search?text=Scarifier",
    "Scissor lifts": "https://www.hss.com/hire/search/?text=scissor%20lifts",
    "Security, Fences, and Barriers": "https://www.hss.com/hire/c/building-and-siteworks/security-and-barriers",
    "Shredders": "https://www.hss.com/hire/search?text=Shredders",
    "Site Accessories": "https://www.hss.com/hire/c/building-and-siteworks/site-accessories",
    "Site Equipment": "https://www.hss.com/hire/c/building-and-siteworks/site-equipment",
    "Site Storage and Accommodation": "https://www.hss.com/hire/c/building-and-siteworks/site-storage",
    "Skates and Stair Climbers": "https://www.hss.com/hire/c/lifting-and-handling/skates-and-stair-climbers",
    "Slab and Block Lifters": "https://www.hss.com/hire/c/lifting-and-handling/slab-and-block-lifters",
    "Slings": "https://www.hss.com/hire/c/lifting-and-handling/hoists-and-slings",
    "Splitters": "https://www.hss.com/hire/c/power/junction-boxes-and-splitters",
    "Spray Systems": "https://www.hss.com/hire/c/painting-and-decorating/spray-systems",
    "Steam Cleaners": "https://www.hss.com/hire/c/cleaning-and-floorcare/steam-cleaners",
    "Stump Grinder": "https://www.hss.com/hire/p/portable-stump-chipper",
    "Surface Preparation": "https://www.hss.com/hire/c/concreting-and-compaction/surface-preparation",
    "Surveying": "https://www.hss.com/hire/c/surveying-and-location/surveying",
    "Surveying and Location (all)": "https://www.hss.com/hire/c/surveying-and-location",
  },
  "T" : {
    "Tile Cutting": "https://www.hss.com/hire/c/sawing-and-cutting/tile-cutting",
    "Timber Cutting": "https://www.hss.com/hire/c/sawing-and-cutting/timber-cutting",
    "Towers": "https://www.hss.com/hire/c/access/",
    "Transformers": "https://www.hss.com/hire/c/power/transformers",
    "Trestles, Stagings and Steps": "https://www.hss.com/hire/c/access/trestles-stagings-and-steps",
    "Trolleys": "https://www.hss.com/hire/c/lifting-and-handling/trucks-and-trolleys",
    "Trucks ": "https://www.hss.com/hire/c/lifting-and-handling/trucks-and-trolleys",
    "Turf cutters": "https://www.hss.com/hire/search?text=Turf+cutters",
  },
  "U" : {},
  "V" : {
    "Vacuum Cleaners": "https://www.hss.com/hire/c/cleaning-and-floorcare/vacuum-cleaners",
    "Ventilation and Extraction": "https://www.hss.com/hire/c/safety-ventilation-extraction/ventilation-and-extraction",
    "Vertical Masts": "https://www.hss.com/hire/c/access/vertical-masts",
    "Vertical Masts": "https://www.hss.com/hire/c/powered-access/vertical-masts",
    "Vibrating plates": "https://www.hss.com/hire/search?text=Vibrating+plates",
  },
  "W" : {
    "Wacker": "https://www.hss.com/hire/search?text=Wacker",
    "Wacker Plates": "https://www.hss.com/hire/search?text=Wacker+Plates",
    "Wall Sanders": "https://www.hss.com/hire/c/sanding-and-fixing/wall-sanders",
    "Welder Generator Accessories": "https://www.hss.com/hire/c/welding/welder-generator-accessories",
    "Welder Generators": "https://www.hss.com/hire/c/welding/welder-generators",
    "Welding (all)": "https://www.hss.com/hire/c/welding",
    "Winches": "https://www.hss.com/hire/c/lifting-and-handling/winches",
    "Wood Chippers": "https://www.hss.com/hire/c/gardening-and-landscaping/garden-shredders-and-wood-chippers",
    "Wood Chippers": "https://www.hss.com/hire/search?text=Wood+Chippers",
    "Woodworking": "https://www.hss.com/hire/c/sawing-and-cutting/woodworking-and-joinery",
    "Work Lighting": "https://www.hss.com/hire/c/lighting/work-lighting",
    "Work Platforms": "https://www.hss.com/hire/c/access/work-platforms"
  },
  "X" : {},
  "Y" : {},
  "Z" : {},
  "#" : {
    "3 Phase Accessories": "https://www.hss.com/hire/c/power/3-phase-accessories",
  },  
};