const navigationData = [
  { category: 'Ear protection', data: ['Ear plugs', 'Ear Muffs'], links: ['/Personal-Protective-Equipment-PPE-/Hearing-Protection~c~AD', '/Personal-Protective-Equipment-PPE-/Hearing-Protection/Ear-Muffs~c~ADC'] },
  { category: 'Head protection', data: ['Helmets & Hardhats', 'Bump Caps', 'Respiratory Helmets & Hoods', 'Food Industry Caps'], links: ['/Personal-Protective-Equipment-PPE-/Head-Protection/Safety-Helmets-and-Hard-Hats~c~AAA', '/Personal-Protective-Equipment-PPE-/Head-Protection/Bump-Caps~c~AAB', '/Personal-Protective-Equipment-PPE-/Respiratory-Protective-Equipment/Respiratory-Helmets-and-Hoods~c~AEG', '/Clothing-and-Workwear/Disposable-Workwear/Food-Industry-Workwear~c~BCE'] },
  { category: 'Face protection', data: ['Safety Glasses and Goggles', 'Brow guards & Visors', 'Respiratory Protective Equipment'], links: ['/Personal-Protective-Equipment-PPE-/Safety-Glasses-and-Goggles~c~AB', '/Personal-Protective-Equipment-PPE-/Face-Protection~c~AC', '/Personal-Protective-Equipment-PPE-/Respiratory-Protective-Equipment~c~AE'] },
  { category: 'Upper body protection', data: ['Hi-Vis tops', 'Warehouse Coats', 'Aprons', 'Waterproof Jackets', 'Coats, Jackets & Bodywarmers', 'Fleeces & Softshell Jackets', 'Polo Shirts/T-Shirts', 'hoodies and sweatshirts', 'Outdoor/Thermal Clothing'], links: ['/Clothing-and-Workwear/Hi-Vis-Clothing~c~BA', '/Clothing-and-Workwear/Protective-Workwear/Warehouse-Coats~c~BBD', '/Clothing-and-Workwear/Protective-Workwear/Aprons~c~BBG', '/Clothing-and-Workwear/Waterproof-PVC-Clothing/Waterproof-Jackets~c~BDC', '/Clothing-and-Workwear/Coats-Jackets-and-Bodywarmers~c~BE', '/Clothing-and-Workwear/Fleeces-and-Softshell-Jackets~c~BF', '/Clothing-and-Workwear/Polo-Shirts-T-Shirts~c~BH', '/Clothing-and-Workwear/Sweatshirts-Hooded-Sweatshirts~c~BG', '/Clothing-and-Workwear/Outdoor-Thermal-Clothing~c~BBI'] },
  { category: 'Full body protection', data: ['Boilersuits & Coveralls', 'Corporate workwear', 'Flame Retardent Coveralls', 'Disposable Coveralls', 'Waterproof Wet Suits'], links: ['/Clothing-and-Workwear/Protective-Workwear/Boilersuits-and-Coveralls~c~BBA', '/Clothing-and-Workwear/Corporate-Workwear~c~BI', '/Clothing-and-Workwear/Protective-Workwear/Flame-Retardent-Coveralls~c~BBB', '/Clothing-and-Workwear/Disposable-Workwear/Disposable-Coveralls~c~BCA', '/Clothing-and-Workwear/Waterproof-PVC-Clothing/Waterproof-Wet-Suits~c~BDA'] },
  { category: 'Hand protection', data: ['Gloves', 'Disposable Gloves'], links: ['/Personal-Protective-Equipment-PPE-/Hand-Protection~c~AF', '/Personal-Protective-Equipment-PPE-/Hand-Protection/Disposable-Gloves~c~AFE'] },
  { category: 'Foot protection', data: ['Work Boots', 'Ladies Work shoes', 'Safety Trainers', 'Rigger Boots', 'Wellington Boots', 'Socks', 'Disposable Overshoes'], links: ['/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGH', '/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGP', '/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGK', '/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGG', '/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGR', '/Personal-Protective-Equipment-PPE-/Safety-Footwear~c~AG?q=%3Aprice-asc%3Acategory%3AAGT', '/Clothing-and-Workwear/Disposable-Workwear/Disposable-Overshoes~c~BCB'] },
  { category: 'Leg protection', data: ['Knee Pads', 'Hi-Vis Trousers', 'Railway Industry Trousers', 'Waterproof Trousers', 'Workwear Trousers'], links: ['/Clothing-and-Workwear/Protective-Workwear/Knee-Pads~c~BBF', '/Clothing-and-Workwear/Hi-Vis-Clothing/Hi-Vis-Trousers~c~BAC', '/Clothing-and-Workwear/Hi-Vis-Clothing/Railway-Industry-Trousers~c~BAG', '/Clothing-and-Workwear/Waterproof-PVC-Clothing/Waterproof-Trousers~c~BDD', '/Clothing-and-Workwear/Trousers~c~BJ'] },
];

export default navigationData;
