export default {
  "/hire/p/light-vibrating-plate-flat-base": { "most_popular":"3 Days", "price":"£43.99", "number_of_customers_hired":7560, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/carpet-cleaner-small": { "most_popular":"3 Days", "price":"£28.05", "number_of_customers_hired":5923, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/floor-sander-240v": { "most_popular":"4 Days", "price":"£45.56", "number_of_customers_hired":7167, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/power-digger-rotavator": { "most_popular":"3 Days", "price":"£53.27", "number_of_customers_hired":3564, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/floor-and-edge-sander-hire-pack": { "most_popular":"4 Days", "price":"£68.22", "number_of_customers_hired":4851, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/mitower": { "most_popular":"8 Days", "price":"£97.00", "number_of_customers_hired":3334, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/concrete-mixer-tip-up-110v": { "most_popular":"Week", "price":"£34.84", "number_of_customers_hired":3955, "replace":"", "highlight":"Week", "v1":true, "v2":false},
  "/hire/p/compact-power-washer": { "most_popular":"3 Days", "price":"£29.10", "number_of_customers_hired":1662, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/110v-vibrating-plate": { "most_popular":"4 Days", "price":"£36.92", "number_of_customers_hired":1376, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/medium-vib-plate-flat-base": { "most_popular":"4 Days", "price":"£64.05", "number_of_customers_hired":1851, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/wallpaper-stripper-240v": { "most_popular":"5 Days", "price":"£37.09", "number_of_customers_hired":1583, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/garden-roller": { "most_popular":"3 Days", "price":"£18.86", "number_of_customers_hired":1442, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/stihl-300mm-petrol-cut-off-saw": { "most_popular":"5 Days", "price":"£37.56", "number_of_customers_hired":1374, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/treble-ladder-2-5-6-0m-t8": { "most_popular":"4 Days", "price":"£34.79", "number_of_customers_hired":1144, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/mitower-plus": { "most_popular":"8 Days", "price":"£122.69", "number_of_customers_hired":1150, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/breaker-vibration-damped-110v": { "most_popular":"3 Days", "price":"£2.27", "number_of_customers_hired":1642, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/edging-sander-240v": { "most_popular":"4 Days", "price":"£36.13", "number_of_customers_hired":5550, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/concrete-mixer-tip-up-240v": { "most_popular":"Week", "price":"£34.48", "number_of_customers_hired":554, "replace":"", "highlight":"Week", "v1":true, "v2":false},
  "/hire/p/te2000-medium-duty-breaker": { "most_popular":"3 Days", "price":"£59.32", "number_of_customers_hired":1182, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/treble-ladder-3-5-9-1m-t12": { "most_popular":"4 Days", "price":"£32.21", "number_of_customers_hired":1916, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/sl15-lift-stacker-manual": { "most_popular":"4 Days", "price":"£131.05", "number_of_customers_hired":554, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/181kg-lifter-stacker-gl8": { "most_popular":"4 Days", "price":"£96.73", "number_of_customers_hired":477, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/brush-cutter-strimmer-petrol": { "most_popular":"3 Days", "price":"£56.78", "number_of_customers_hired":427, "replace":"Weekend", "highlight":"", "v1":true, "v2":true},
  "/hire/p/heavy-duty-breaker-hilti-te3000": { "most_popular":"4 Days", "price":"£83.94", "number_of_customers_hired":623, "replace":"Week", "highlight":"", "v1":true, "v2":true},
  "/hire/p/52ltr-pump-dehumidifier": { "most_popular":"10 Days", "price":"£233.53", "number_of_customers_hired":1138, "replace":"Week", "highlight":"", "v1":true, "v2":true}
};