const actionTypes = {
    add_to_cart: 'add_to_cart',
    add_to_wishlist: 'add_to_wishlist',
    apply_coupon: 'apply_coupon',
    click_book_appointment: 'click_book_appointment',
    click_cta: 'click_cta',
    click_decrease_cart_quantity: 'click_decrease_cart_quantity',
    click_increase_cart_quantity: 'click_increase_cart_quantity',
    click_login: 'click_login',
    click_product: 'click_product',
    click_promotion: 'click_promotion',
    click_sign_up: 'click_sign_up',
    close: 'close',
    display: 'display',
    file_download: 'file_download',
    hover: 'hover',
    image_zoom: 'image_zoom',
    login: 'login',
    logout: 'logout',
    open: 'open',
    click_pdp_product_rating: 'click_pdp_product_rating',
    remove_from_cart: 'remove_from_cart',
    reorder_remove_item: 'reorder_remove_item',
    retail_registration_complete: 'retail_registration_complete',
    scroll: 'scroll',
    search_redirect: 'search_redirect',
    search_view_more_click: 'search_view_more_click',
    select: 'select',
    share: 'share',
    submit: 'submit',
    view: 'view',
    view_cart: 'view_cart',
    view_product: 'view_product',  
    view_promotion: 'view_promotion',
    view_search_results: 'view_search_results',
};

export default actionTypes;