const thesePosts = {
  gb: {
    // 'mycycling'
    '/gb/newsroom/mycycling-won-good-design-award/': 'mycycling',
    '/gb/newsroom/technogyms-mycycling-is-compatible-with-zwift/': 'mycycling',
    '/gb/newsroom/mycycling-technogym-cyclist-training/': 'mycycling',
    '/gb/newsroom/cycling-nutrition-how-to-prevent-hunger-crisis/': 'mycycling',
    '/gb/newsroom/peace-of-mind-cross-country/': 'mycycling',
    '/gb/newsroom/wellness-suites-cater-privacy-when-travelling/': 'mycycling',
    '/gb/newsroom/javier-gomez-noya-trains-technogym/': 'mycycling',
    '/gb/newsroom/test-why-measure-the-anaerobic-threshold/': 'mycycling',
    '/gb/newsroom/power-of-the-team/': 'mycycling',
    // '/gb/newsroom/christmas-give-yourself-wellness/': 'mycycling',
    // 'skillmill'
    '/gb/newsroom/technogym-wins-the-adi-design-index-award-with-skillmill/': 'skillmill',
    '/gb/newsroom/technogym-compasso-doro-skillmill/': 'skillmill',
    '/gb/newsroom/skillmill-gear-year-runners-world-america/': 'skillmill',
    '/gb/newsroom/marathon-training-tips-by-technogym/': 'skillmill',
    // 'myrun'
    // '/gb/newsroom/marathon-training-tips-by-technogym/': 'myrun',
    '/gb/newsroom/technogym-myrun-now-compatible-with-zwift-running-platform/': 'myrun', 
    '/gb/newsroom/lots-of-good-opportunities-to-train-in-winter/': 'myrun',
    '/gb/newsroom/christmas-give-yourself-wellness/': 'myrun',
    '/gb/newsroom/technogym-sponsor-florence-marathon/': 'myrun',
    // '/gb/newsroom/wellness-suites-cater-privacy-when-travelling/': 'myrun',
    '/gb/newsroom/how-to-run/': 'myrun',
    '/gb/newsroom/keep-your-legs-running-fit/': 'myrun',
    '/gb/newsroom/running-healthy-knees/': 'myrun',
    '/gb/newsroom/get-in-shape-summer/': 'myrun',
    '/gb/newsroom/women-embrace-wellness/': 'myrun',
    // 'skillrun'
    '/gb/newsroom/technogym-skillrun-treadmill/': 'skillrun',
    '/gb/newsroom/technogym-official-supplier-pyeongchang-2018-winter-olympic-games/': 'skillrun',
  },
  it: {
    '/it/newsroom/natale-regalati-il-wellness/': 'mycycling',
    '/it/newsroom/la-forza-del-team/': 'mycycling',
    '/it/newsroom/javier-gomez-noya-si-allena-con-technogym/': 'mycycling',
    '/it/newsroom/lo-stato-di-quiete/': 'mycycling',
    '/it/newsroom/lalimentazione-nellallenamento-del-ciclismo/': 'mycycling',
    '/it/newsroom/mycycling-technogym-allenamento-del-ciclista/': 'mycycling',
    '/it/newsroom/technogyms-mycycling-compatibile-con-zwift/': 'mycycling',
    '/it/newsroom/mycycling-vince-il-good-design-award/': 'mycycling',
    // 'skillmill'
    // '/it/newsroom/technogym-fornitore-ufficiale-pyeongchang-2018-giochi-olimpici-invernali/': 'skillmill',
    '/it/newsroom/come-si-prepara-una-maratona/': 'skillmill',
    '/it/newsroom/skillmill-gear-year-runners-world-america/': 'skillmill',
    '/it/newsroom/technogym-compasso-doro-skillmill/': 'skillmill',
    '/it/newsroom/technogym-vince-il-premio-adi-design-index-2017/': 'skillmill',
    // 'myrun'
    // '/it/newsroom/come-si-prepara-una-maratona/': 'myrun',
    '/it/newsroom/technogym-myrun-compatibile-con-zwift-running-platform/': 'myrun',
    '/it/newsroom/inverno-un-sacco-di-buone-opportunita-per-allenarsi/': 'myrun',
    // '/it/newsroom/natale-regalati-il-wellness/': 'myrun',
    '/it/newsroom/technogym-sponsor-della-firenze-marathon/': 'myrun',
    '/it/newsroom/wellness-suite-in-hotel/': 'myrun',
    '/it/newsroom/trail-running-correre-natura/': 'myrun',
    '/it/newsroom/correre-viaggio-tra-tecnica-e-mente/': 'myrun',
    '/it/newsroom/ironman-endurance-allenamento-alimentazione/': 'myrun',
    '/it/newsroom/come-allenarsi-con-il-tapis-roulant/': 'myrun',
    '/it/newsroom/liberi-stress-vacanze-estive/': 'myrun',
    '/it/newsroom/allenamento-forza-nella-pallacanestro/': 'myrun',
    // 'skillrun'
    '/it/newsroom/technogym-fornitore-ufficiale-pyeongchang-2018-giochi-olimpici-invernali/': 'skillrun',
    '/it/newsroom/sport-e-performance-congress-scienza-nella-corsa/': 'skillrun',
    '/it/newsroom/technogym-skillrun-tapis-roulant/': 'skillrun',
  },
};
export default thesePosts;
