export default {
  "/products/real-luxury-luxury-scented-candle": "Lavender, Rosewood &amp; Jasmine",
  "/products/perfect-night-sleep-luxury-scented-candle": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/complete-bliss-luxury-scented-candle": "Rose, Lime and Black Pepper",
  "/products/feel-refreshed-luxury-scented-candle": "Sicilian Lemon &amp; Fresh Basil",
  "/products/happiness-luxury-scented-candle": "White Neroli, Mimosa &amp; Lemon",
  "/products/bedtime-hero-scented-candle-3-wick": "Chamomile, Ylang Ylang &amp; Cedarwood",
  "/products/real-luxury-standard-scented-candle": "Lavender, Rosewood &amp; Jasmine",
  "/products/perfect-nights-sleep-standard-scented-candle": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/feel-refreshed-standard-scented-candle": "Sicilian Lemon &amp; Fresh Basil",
  "/products/happiness-standard-scented-candle": "White Neroli, Mimosa &amp; Lemon",
  "/products/complete-bliss-standard-scented-candle": "Rose, Lime and Black Pepper",
  "/products/perfect-nights-sleep-travel-scented-candle": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/complete-bliss-travel-scented-candle": "Rose, Lime and Black Pepper",
  "/products/real-luxury-travel-scented-candle": "Lavender, Rosewood &amp; Jasmine",
  "/products/happiness-travel-scented-candle": "White Neroli, Mimosa &amp; Lemon",
  "/products/christmas-wish-scented-candle-3-wick": "Mandarin, Cinnamon &amp; Tonka bean",
  "/products/perfect-peace-scented-candle-3-wick": "Pine, Myrrh &amp; Zesty Lime",
  "/products/limited-edition-real-luxury-scented-candle-3-wick": "Lavender, Rosewood &amp; Jasmine",
  "/products/christmas-wish-scented-candle-1-wick": "Mandarin, Cinnamon &amp; Tonka bean",
  "/products/perfect-peace-scented-candle-1-wick": "Pine, Myrrh &amp; Zesty Lime",
  "/products/limited-edition-real-luxury-scented-candle-1-wick": "Lavender, Rosewood &amp; Jasmine",
  "/products/the-get-to-know-neom-edit": "A Collection for all Moods",
  "/products/neom-kickstarter-kit": "4 bestselling natural heroes",
  "/products/sleepy-bedtime-duo": "Award-winning face oil &amp; candle duo",
  "/products/the-mood-boosting-routine": "The Ultimate Happiness Bundle",
  "/products/the-supercharged-routine": "A Natural Energy Boost",
  "/products/the-gift-of-energised-mornings-calm-nights": "Two iconic NEOM must-haves",
  "/products/the-gift-of-happy-days-sleepy-nights": "Two iconic NEOM must-haves",
  "/products/the-gift-of-bedtime-calm": "Award-winning bath foam &amp; candle duo",
  "/products/the-mood-boosters": "A must-have trio for happy, positive vibes",
  "/products/all-day-wellbeing": "Luxury edit of feel-good favourites",
  "/products/scents-of-wellbeing": "A trio of festive fragrances",
  "/products/calm-vibes": "The Perfect Stocking Filler",
  "/products/time-for-real-luxury": "The Gift of Relaxation",
  "/products/ultimate-sleep-kit": "Dreamy Sleep in 3 Steps",
  "/products/christmas-wellbeing-collection": "For Morning, Noon &amp; Night",
  "/products/tranquillity-reed-diffuser": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/complete-bliss-reed-diffuser": "Rose, Lime and Black Pepper",
  "/products/real-luxury-reed-diffuser": "Lavender, Rosewood &amp; Jasmine",
  "/products/feel-refreshed-reed-diffuser": "Sicilian Lemon &amp; Fresh Basil",
  "/products/happiness-reed-diffuser": "White Neroli, Mimosa &amp; Lemon",
  "/products/tranquillity-home-fragranceduo": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/happiness-home-fragranceduo": "White Neroli, Mimosa &amp; Lemon",
  "/products/real-luxury-home-fragranceduo": "Lavender, Rosewood &amp; Jasmine",
  "/products/tranquillity-reed-diffuser-refill": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/happiness-reed-diffuser-refill": "White Neroli, Mimosa &amp; Lemon",
  "/products/real-luxury-reed-diffuser-refill": "Lavender, Rosewood &amp; Jasmine",
  "/products/the-mood-boosting-routine": "The Ultimate Happiness Bundle",
  "/products/the-supercharged-routine": "A Natural Energy Boost",
  "/products/the-mood-boosters": "White Neroli, Mimosa &amp; Lemon",
  "/products/wellbeing-essential-oil-blends-collection": "A Collection for all Moods",
  "/products/pick-your-blend-to-suit-your-mood-essential-oil-blend-collection": "All 10 natural Essential Oil Blends",
  "/products/perfect-peace-essential-oil-blend-10ml": "Pine, Myrrh &amp; Zesty Lime",
  "/products/christmas-wish-essential-oil-blend-10ml": "Mandarin, Cinnamon &amp; Tonka bean",
  "/products/bedtime-hero-essential-oil-blend-10ml": "Chamomile, Ylang Ylang &amp; Cedarwood",
  "/products/perfect-night-sleep-essential-oil-blend-10ml": "Lavender, Jasmine &amp; Sweet Basil",
  "/products/real-luxury-essential-oil-blend-10ml": "Lavender, Rosewood &amp; Jasmine",
  "/products/happiness-essential-oil-blend-10ml": "White Neroli, Mimosa &amp; Lemon",
  "/products/feel-refreshed-energy-essential-oil-blend-10ml": "Sicilian Lemon &amp; Fresh Basil",
  "/products/complete-bliss-essential-oil-blend": "Rose, Lime and Black Pepper",
  "/products/sensuous-essential-oil-blend": "Ylang ylang, Frankincense &amp; Patchouli",
  "/products/feel-good-vibes-essential-oil-blend-10ml": "May Chang, Mandarin &amp; Ylang Ylang",
  "/products/focus-the-mind-essential-oil-blend-10ml": "Green Hibiscus &amp; Woody undertones",
  "/products/moment-of-calm-essential-oil-blend-10ml": "Wild Rose &amp; Neroli",
  "/products/black-pepper-bergamot-essential-oil-blend": "Powerful, intense and warming",
  "/products/jasmine-bergamot-geranium-essential-oil-blend-10ml": "Uplifting, fresh and honeyed",
  "/products/grapefruit-mandarin-eucalyptus-essential-oil-blend-10ml": "Energising, zesty and fresh",
  "/products/tuberose-cedarwood-ylang-ylang-essential-oil-blend-10ml": "Deep, sensual and rich",
  "/products/ylang-ylang-vetivert-tonka-bean-essential-oil-blend": "Floral, rich and exotic",
  "/products/orange-blossom-neroli-essential-oil-blend-10ml": "Soothing, comforting and relaxing"
}
