export default [
  '49Winters',
  'Agent Provocateur',
  'Alanui',
  'Alexander McQueen',
  'Alexander Wang',
  'Amouage',
  'APC',
  'Balmain',
  'Boglioli',
  'Bottega Veneta',
  'Burberry London',
  'Buscemi',
  'Canada Goose',
  'Canali',
  'Caruso',
  'Celine',
  'Chloe',
  'Christian Louboutin',
  'Churchs',
  'Dior',
  'Dior Homme',
  'Dolce and Gabbana',
  'DSquared2',
  'Etro',
  'Fendi',
  'Giuseppe Zanotti',
  'GIVENCHY',
  'Golden Goose Deluxe Brand',
  'Gucci',
  'Helmut Lang',
  'Hermes',
  'Heron Preston',
  'Jimmy Choo',
  'JW Anderson',
  'Kenzo',
  'Lanvin',
  'Mackage',
  'Maharishi',
  'Maison Margiela',
  'Marc Jacobs',
  'Marcelo Burlon',
  'Marni',
  'MCM',
  'McQ Alexander McQueen',
  'Missoni',
  'Miu Miu',
  'Moncler',
  'Moncler C',
  'Moncler Gamme Bleu',
  'Moncler Grenoble',
  'Montblanc',
  'Moschino',
  'Mulberry',
  'Neil Barrett',
  'Nigel Cabourn',
  'Off White',
  'Off White X Timberland',
  'Palm Angels',
  'Paul Smith',
  'Philipp Plein',
  'Pierre Balmain',
  'Rhude',
  'Roberto Cavalli',
  'Saint Laurent',
  'Sophia Webster',
  'Stella McCartney',
  'Stone Island Shadow Project',
  'Sunspel',
  'TBlack',
  'Tods',
  'Trickers',
  'Tumi',
  'Valentino',
  'Versace',
  'Versace Collection',
  'Versace Icon',
  'Versus Versace',
  'Victoria Beckham',
  'Vilebrequin',
  'Vivienne Westwood',
  'Vivienne Westwood Accessories',
  'Vivienne Westwood Man',
  'Woolrich',
  'Yeezy',
  'Young Versace',
  'Yves Saint Laurent',
  'Yves Salomon',
  'Zegna',
  'Zimmermann',
  'Adidas by Stella McCartney',
  'Android Homme',
  'Armani',
  'Billionaire Boys Club',
  'Boutique Moschino',
  'CP Company',
  'Coach',
  'Camilla',
  'Diane Von Furstenberg',
  'Filling Pieces',
  'Grenson',
  'Jacob Cohen',
  'Jeffery West',
  'Joseph',
  'Just Cavalli',
  'M Missoni',
  'Marc by Marc Jacobs',
  'Mason Garments',
  'Max et Moi',
  'Mercer',
  'Miansai',
  'MSGM',
  'Pairs In Paris',
  'Plein Sport',
  'Pyrenex',
  'Sartoria Tramarossa',
  'Self Portrait',
  'Stone Island',
  'Stuart Weitzman',
  'Theory',
  'Vince',
  'Vivienne Westwood Jewellery',
  'Y3',
];
