const topFilters = {
    '/beauty/luxury-beauty-skincare/': [
        'Estee Lauder',
        'Clinique',
        'The Ordinary',
        'KVD',
        'Benefit',
        'IT Cosmetics',
        'Liz Earle',
        'NARS',
        'Fenty Beauty',
        'Fenty Skin',
        'Lancome',
    ],
    '/beauty/skincare/': [
        'La Roche Posay',
        'Garnier',
        'Palmers',
        'Neutrogena',
        'Teatree & Witch Hazel',
        'Nivea',
        'Simple',
        'Dove',
        'E45',
        'Olay',
    ],
    '/beauty/hair/': [
        'Bleach London',
        'Head and Shoulders',
        'Herbal Essences',
        'Tresemme',
        'Elvive',
        'Pantene',
        'Shrine',
        'Noughty',
        'Aussie',
        "L'Oreal",
    ],
    '/beauty/beauty-accessories/': [
        'Real Techniques',
        'Revolution',
        'Denman',
        'Eylure',
        'Cantu',
        'Elegant Touch',
        'Invisibobble',
        'Skinnydip',
        'Tangle Teezer',
        'Ardell',
    ],
    '/fragrance/perfume/': [
        'Mugler',
        'Paco Rabanne',
        'Jimmy Choo',
        'Christian Dior',
        'Marc Jacobs',
        'Gucci',
        'Ariana Grande',
        'Valentino',
        'Viktor & Rolf',
        'Hugo Boss'
    ],
    '/fragrance/aftershave/': [
        'Christian Dior',
        'Hugo Boss',
        'Paco Rabanne',
        'Versace',
        'Mont Blanc',
        'Calvin Klein',
        'Diesel',
        'Lacoste',
        'Emporio Armani',
        'Dolce and Gabbana'
    ],

}

export default topFilters;