var modalData = {
    content: {
      uk: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/f8ee18e51f8c16e6cb421a3fc35ab3af_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Welcome to our UK site',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              '<li>Over 500 curated emerging designers</li>',
              '<li>Free delivery from all UK brands</li>',
              '<li>Free worldwide returns</li>',
              '<li>No customs duties or taxes</li>',
            '</ul>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Start shopping</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">Sign up for our newsletter</span>',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
            '<div class="uc9_contact">',
              '<div class="uc9_contact-row">',
                '<span class="uc9_contact__phone">+44 (0) 20 3627 3191</span>',
                '<span class="uc9_contact__address">32 Dover Street, London, W1S 4NE</span>',
              '</div>',
              '<div class="uc9_contact-row">',
                '<span class="uc9_contact__phone">+44 (0) 20 7229 5698</span>',
                '<span class="uc9_contact__address">46 Ledbury Road, London, W11 2AB</span>',
              '</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join('')
      },
      us: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/b302c4e8c36d9de8fb08f1de23728e20_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Welcome to our US site',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              //'<li>Free delivery over $240</li>',
              '<li>Over 500 curated emerging designers</li>',
              '<li>Free delivery from all US brands</li>',
              '<li>Free worldwide returns</li>',
              '<li>No customs duties or taxes</li>',
            '</ul>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Start shopping</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">Sign up for our newsletter</span>',
            '<p>Be the first to know about new designer, trends and offers</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
            '<div class="uc9_contact">',
              '<div class="uc9_contact-row">',
                '<span class="uc9_contact__phone">+1 (646) 934 6601</span>',
                '<span class="uc9_contact__address">95 Grand Street, New York, NY 10013, USA</span>',
              '</div>',
            '</div>',
          '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join('')
      },
      au: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/fb0a8994ab8c865f6affefde48ac5fb2_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Welcome to our AUS site',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              '<li>Over 500 curated emerging designers</li>',
              //'<li>Free delivery from all AUS brands</li>',
              '<li>Free worldwide returns</li>',
              //'<li>Free delivery over $300</li>',
              '<li>No customs duties or taxes</li>',
            '</ul>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Start shopping</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">Sign up for our newsletter</span>',
            '<p>Be the first to know about new designer, trends and offers</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
            '<div class="uc9_contact">',
              '<div class="uc9_contact-row">',
                '<span class="uc9_contact__phone uc9_contact__phone-icon">+ 61283111555</span>',
              '</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join('')
      },
      eu: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/946daef15041d8d7e288e4aedf5c648c_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Welcome to our EU site',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              //'<li>Free delivery over €210</li>',
              '<li>Over 500 curated emerging designers</li>',
              '<li>Free worldwide returns</li>',
              '<li>No customs duties or taxes<span class="uc9_subtext">*some exclusions apply</span></li>',
            '</ul>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Start shopping</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">Sign up for our newsletter</span>',
            '<p>Be the first to know about new designer, trends and offers</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join('')
      },
      de: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/71a6c6d2ff3fea148df07a382e713b5d_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Willkommen auf unserer Website!',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              //'<li>Free delivery over €210</li>',
              '<li>Über 750 kuratierte aufstrebende Designer</li>',
              '<li>Kostenlose Lieferung aller deutschen Marken</li>',
              '<li>Kostenlose Rücksendung und Umtausch</li>',
              '<li>Keine Zölle oder weitere Steuern</li>',
              '<li>Höchste Sicherheit & Datenschutz</li>',
            '</ul>',
            '<p>Ethisch. Einzigartig. Jeden Tag neue Arrivals!</p>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">JETZT SHOPPEN </a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">WERDE TEIL DER WOLF & BADGER COMMUNITY</span>',
            '<p>Sign-up hier für unseren Newsletter über neue Designer, Trends, Angebote und mehr</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Email Adresse hier eingeben" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">SIGN-UP</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Vielen Dank fuer Deine Newsletter Registrierung!',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Sign-up hier für unseren Newsletter über neue Designer, Trends, Angebote und mehr</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Email Adresse hier eingeben" class="uc9_input"/>',
              '<div class="uc9_send">SIGN-UP</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Vielen Dank fuer Deine Newsletter Registrierung!',
          '</div>'
        ].join('')
      },
      fr: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div class="uc9_lightbox_flag"><img src="https://dd6zx4ibq538k.cloudfront.net/static/images/4347/b2a1d76a8e903a12fbe946d0db0d02ac_100_100.png" /></div>',
              '<div class="uc9_lightbox_heading">',
                'Bienvenue sur notre site!',
              '</div>',
              '<div id="uc9_lightbox-exit"></div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              //'<li>Free delivery over €210</li>',
              '<li>Plus de 750 designers sélectionnés & emergés</li>',
              '<li>Livraison gratuite de toutes les marques françaises</li>',
              '<li>Retour gratuit sur tout</li>',
              '<li>Pas de droits de douane ni taxes</li>',
            '</ul>',
            '<p>Ethique, unique. Nouvelles arrivées chaque jour!</p>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Commencer le SHOPPING</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">INSCRIPTION A LA NEWSLETTER WOLF & BADGER!</span>',
            '<p>Sign-up ici pour de nouveautés à ne pas manquer</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Entrez votre adresse email svp" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">JE M’INSCRIS</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Merci pour l\'inscription à notre newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Sign-up ici pour de nouveautés à ne pas manquer</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Entrez votre adresse email svp" class="uc9_input"/>',
              '<div class="uc9_send">JE M’INSCRIS</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Merci pour l\'inscription à notre newsletter',
          '</div>'
        ].join('')
      },
      row: {
        image: 'https://dd6zx4ibq538k.cloudfront.net/static/images/4347/069aa86a8dd950f8dfc79e9e6196bc27_366_562.jpeg',
        html_right: [
          '<div class="uc9_top-bar">',
              '<div id="uc9_lightbox-exit"></div>',
              '<div class="uc9_lightbox_heading">',
                'Welcome to Wolf & Badger',
              '</div>',
          '</div>',
          '<div class="uc9_centre uc9_top-content">',
            '<div class="uc9_logo-wrap"><div class="uc9_logo"></div><div class="uc9_tagline">The world\'s best independent brands</div></div>',
            '<ul>',
              //'<li>Free delivery over £150</li>',
              '<li>Over 500 curated emerging designers</li>',
              '<li>Free worldwide returns</li>',
              '<li>No customs duties or taxes<span class="uc9_subtext">*some exclusions apply</span></li>',
            '</ul>',
            '<div class="uc9_centre"><a class="uc9_closeLightbox uc9_btn">Start shopping</a></div>',
          '</div>',
          '<div class="uc9_email-wrapper">',
            '<span class="uc9_heading">Sign up for our newsletter</span>',
            '<p>Be the first to know about new designer, trends and offers</p>',
            '<div class="uc9_input-wrap uc9_centre">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input uc9_small"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join(''),
        html_bottom: [
          '<hr>',
          '<div class="uc9_email-wrapper">',
            '<p>Be the first to know about new designers, trends and events</p>',
            '<div class="uc9_input-wrap">',
              '<input type="text" placeholder="Enter your email address" class="uc9_input"/>',
              '<div class="uc9_send">Register</div>',
            '</div>',
          '</div>',
          '<div class="uc9_email-success">',
            'Thank you for signing up to our newsletter',
          '</div>'
        ].join('')
      },
    }
  };

  export default modalData;