const data = {
  mycycling: {
    gb: ['https://www.technogym.com/gb/newsroom/mycycling-won-good-design-award/', 'https://www.technogym.com/gb/newsroom/technogyms-mycycling-is-compatible-with-zwift/', 'https://www.technogym.com/gb/newsroom/mycycling-technogym-cyclist-training/', 'https://www.technogym.com/gb/newsroom/cycling-nutrition-how-to-prevent-hunger-crisis/', 'https://www.technogym.com/gb/newsroom/peace-of-mind-cross-country/', 'https://www.technogym.com/gb/newsroom/wellness-suites-cater-privacy-when-travelling/', 'https://www.technogym.com/gb/newsroom/javier-gomez-noya-trains-technogym/', 'https://www.technogym.com/gb/newsroom/test-why-measure-the-anaerobic-threshold/', 'https://www.technogym.com/gb/newsroom/power-of-the-team/', 'https://www.technogym.com/gb/newsroom/christmas-give-yourself-wellness/'],
    it: ['https://www.technogym.com/it/newsroom/mycycling-vince-il-good-design-award/', 'https://www.technogym.com/it/newsroom/technogyms-mycycling-compatibile-con-zwift/', 'https://www.technogym.com/it/newsroom/mycycling-technogym-allenamento-del-ciclista/', 'https://www.technogym.com/it/newsroom/lalimentazione-nellallenamento-del-ciclismo/', 'https://www.technogym.com/it/newsroom/lo-stato-di-quiete/', 'https://www.technogym.com/it/newsroom/javier-gomez-noya-si-allena-con-technogym/', 'https://www.technogym.com/it/newsroom/la-forza-del-team/', 'https://www.technogym.com/it/newsroom/natale-regalati-il-wellness/'],
  },
  skillmill: {
    gb: ['https://www.technogym.com/gb/newsroom/technogym-wins-the-adi-design-index-award-with-skillmill/', 'https://www.technogym.com/gb/newsroom/technogym-compasso-doro-skillmill/', 'https://www.technogym.com/gb/newsroom/skillmill-gear-year-runners-world-america/', 'https://www.technogym.com/gb/newsroom/marathon-training-tips-by-technogym/', 'https://www.technogym.com/gb/newsroom/technogym-official-supplier-pyeongchang-2018-winter-olympic-games/'],
    it: ['https://www.technogym.com/it/newsroom/technogym-vince-il-premio-adi-design-index-2017/', 'https://www.technogym.com/it/newsroom/technogym-compasso-doro-skillmill/', 'https://www.technogym.com/it/newsroom/skillmill-gear-year-runners-world-america/', 'https://www.technogym.com/it/newsroom/come-si-prepara-una-maratona/', 'https://www.technogym.com/it/newsroom/technogym-fornitore-ufficiale-pyeongchang-2018-giochi-olimpici-invernali/'],
  },
  myrun: {
    gb: ['https://www.technogym.com/gb/newsroom/marathon-training-tips-by-technogym/', 'https://www.technogym.com/gb/newsroom/technogym-myrun-now-compatible-with-zwift-running-platform/', 'https://www.technogym.com/gb/newsroom/lots-of-good-opportunities-to-train-in-winter/', 'https://www.technogym.com/gb/newsroom/christmas-give-yourself-wellness/', 'https://www.technogym.com/gb/newsroom/technogym-sponsor-florence-marathon/', 'https://www.technogym.com/gb/newsroom/wellness-suites-cater-privacy-when-travelling/', 'https://www.technogym.com/gb/newsroom/how-to-run/', 'https://www.technogym.com/gb/newsroom/keep-your-legs-running-fit/', 'https://www.technogym.com/gb/newsroom/running-healthy-knees/', 'https://www.technogym.com/gb/newsroom/get-in-shape-summer/', 'https://www.technogym.com/gb/newsroom/women-embrace-wellness/'],
    it: ['https://www.technogym.com/it/newsroom/come-si-prepara-una-maratona/', 'https://www.technogym.com/it/newsroom/technogym-myrun-compatibile-con-zwift-running-platform/', 'https://www.technogym.com/it/newsroom/inverno-un-sacco-di-buone-opportunita-per-allenarsi/', 'https://www.technogym.com/it/newsroom/natale-regalati-il-wellness/', 'https://www.technogym.com/it/newsroom/technogym-sponsor-della-firenze-marathon/', 'https://www.technogym.com/it/newsroom/wellness-suite-in-hotel/', 'https://www.technogym.com/it/newsroom/trail-running-correre-natura/', 'https://www.technogym.com/it/newsroom/correre-viaggio-tra-tecnica-e-mente/', 'https://www.technogym.com/it/newsroom/ironman-endurance-allenamento-alimentazione/', 'https://www.technogym.com/it/newsroom/come-allenarsi-con-il-tapis-roulant/', 'https://www.technogym.com/it/newsroom/liberi-stress-vacanze-estive/', 'https://www.technogym.com/it/newsroom/allenamento-forza-nella-pallacanestro/'],
  },
  skillrun: {
    gb: ['https://www.technogym.com/gb/newsroom/technogym-skillrun-treadmill/', 'https://www.technogym.com/gb/newsroom/technogym-official-supplier-pyeongchang-2018-winter-olympic-games/'],
    it: ['https://www.technogym.com/it/newsroom/technogym-skillrun-tapis-roulant/', 'https://www.technogym.com/it/newsroom/sport-e-performance-congress-scienza-nella-corsa/', 'https://www.technogym.com/it/newsroom/technogym-fornitore-ufficiale-pyeongchang-2018-giochi-olimpici-invernali/'],
  },
};
export default data;
