/* eslint-disable */

var nav_HTML = $([
    '<div class="TP011_nav">',
    '<ul class="TP011_level0">',
    '<li id="TP011_menu-listing">',
    '<a href="#">',
    '<div class="TP011_hamburger">',
    '<span></span>',
    '<span></span>',
    '<span></span>',
    '<span></span>',
    '</div>',
    '<span>Menu</span>',
    '</a>',
    '<div class="TP011_megamenu">',
    '<ul class="TP011_level1"></ul>',
    '</div>',
    '</li>',
    '<li id="TP011_az-listing">',
    '<a href="#">',
    '<div class="TP011_hamburger">',
    '<span></span>',
    '<span></span>',
    '<span></span>',
    '<span></span>',
    '</div>',
    '<span>A to Z Listing</span>',
    '</a>',
    '</li>',
    '<li class="TP090_cat">',
        '<a href="https://www.travisperkins.co.uk/Product/Tools+Workwear/Power-Tools/c/1500471">Power Tools</a>',
        '<div class="TP090_prod-wrap">',
            '<h2>Power Tools</h2>',
            '<div class="TP090_prod-wrap-inner">',
                '<div class="TP090_prod-wrap-table">',
                    '<a href="//www.travisperkins.co.uk/DeWalt-18V-Nail-Gun-Twin-Pack-DCK264P2-GB/p/180400" class="TP090_prod">',
                    '<img src="//travisperkins.scene7.com/is/image/travisperkins/GPID_1000127647_00?defaultImage=travisperkins/missing-product&id=nmESH3&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="DeWalt 18V Nail Gun Twin Pack DCK264P2-GB">',
                    '<p>DeWalt 18V Nail Gun Twin Pack DCK264P2-GB</p>',
                    '<span class="TP090_price">',
                    '<span class="TP090_price-main">£540.00</span>',
                    '<span class="TP090_price-each">each (ex vat)</span>',
                    '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/DeWalt-XR-18V-Cordless-3-Mode-Rotary-Hammer-Drill-2-X-4-0Ah-Li-Ion-Batteries-DCH253M2-GB/p/685222" class="TP090_prod">',
                        '<img src="//travisperkins.scene7.com/is/image/travisperkins/B2607_685222_00?defaultImage=travisperkins/missing-product&id=a-DTx3&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="DeWalt 18V Xr Heavy Duty 3 Mode Hammer Drill DCH253m2 C/W 2 x 4.0AH Batteries">',
                        '<p>DeWalt 18V Xr Heavy Duty 3 Mode Hammer Drill DCH253m2 C/W 2 x 4.0AH Batteries</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£250.00</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a style="vertical-align: top;" href="//www.travisperkins.co.uk/Makita-18V-Cordless-SDS-Plus-Brushless-3-Mode-Rotary-Hammer-Drill-Body-Only-DHR242Z/p/881610" class="TP090_prod">',
                        '<img style="height: 100px; margin-top: 20px; padding-bottom: 40px;" src="//travisperkins.scene7.com/is/image/travisperkins/M0852_881610_00?defaultImage=travisperkins/missing-product&id=7q7h-0&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Makita 18V Cordless SDS-Plus Brushless 3 Mode Rotary Hammer Drill Body Only DHR242Z">',
                        '<p>Makita 18V Cordless SDS-Plus Brushless 3 Mode Rotary Hammer Drill Body Only DHR242Z</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£165.00</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/Product/Tools+Workwear/Power-Tools/c/1500471" class="TP090_prod TP090_view-all">',
                        '<span class="TP090_view_all-text">',
                            'View all <span>365</span> Power Tools',
                        '</span>',
                    '</a>',
                '</div>',
            '</div>',
        '</div>',
    '</li>',
    '<li class="TP090_cat">',
        '<a href="//www.travisperkins.co.uk/Product/Gardens+Landscaping/Fencing/Fence-Panels+Trellis/c/1500100">Fence Panels</a>',
        '<div class="TP090_prod-wrap">',
            '<h2>Fence Panels</h2>',
            '<div class="TP090_prod-wrap-inner">',
                '<div class="TP090_prod-wrap-table">',
                    '<a href="//www.travisperkins.co.uk/Super-Lap-Pressure-Treated-Fence-Panel-1828mm-x-1828mm/p/160637" class="TP090_prod">',
                        '<img src="//travisperkins.scene7.com/is/image/travisperkins/L1641_160637_00?defaultImage=travisperkins/missing-product&id=uuARN0&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt=""Super Lap Pressure Treated Fence Panel 1828mm x 1828mm>',
                        '<p>Super Lap Pressure Treated Fence Panel 1828mm x 1828mm</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£26.65</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/Super-Lap-Pressure-Treated-Fence-Panel-1828mm-x-1524mm/p/160641" class="TP090_prod">',
                        '<img src="//travisperkins.scene7.com/is/image/travisperkins/L1641_160641_00?defaultImage=travisperkins/missing-product&id=Ft1Rz1&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Super Lap Pressure Treated Fence Panel 1828mm x 1524mm">',
                        '<p>Super Lap Pressure Treated Fence Panel 1828mm x 1524mm</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£25.63</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/Close-Board-Dip-Treated-Fence-Panel-1828mm-x-1828mm/p/848946" class="TP090_prod">',
                        '<img src="https://travisperkins.scene7.com/is/image/travisperkins/L1641_848946_00?defaultImage=travisperkins/missing-product&id=93MSH1&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Close Board Dip Treated Fence Panel 1828mm x 1828mm">',
                        '<p>Close Board Dip Treated Fence Panel 1828mm x 1828mm</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£24.95</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="https://www.travisperkins.co.uk/Product/Gardens+Landscaping/Fencing/Fence-Panels+Trellis/c/1500100?q=%3Arelevance%3AType%3AFence+Panel&text=#" class="TP090_prod TP090_view-all">',
                        '<span class="TP090_view_all-text">',
                            'View all <span>26</span> Fence Panels',
                        '</span>',
                    '</a>',
                '</div>',
            '</div>',
        '</div>',
    '</li>',
    '<li class="TP090_cat">',
        '<a href="https://www.travisperkins.co.uk/Product/Gardens+Landscaping/Paving+Walling/Decorative-Paving-Slabs/c/1500124">Decorative Paving Slabs</a>',
        '<div class="TP090_prod-wrap">',
            '<h2>Decorative Paving Slabs</h2>',
            '<div class="TP090_prod-wrap-inner">',
                '<div class="TP090_prod-wrap-table">',
                    '<a href="//www.travisperkins.co.uk/Marshalls-Indian-Buff-Sandstone-Paving-Project-Pack-15-23m2-Coverage/p/769541" class="TP090_prod">',
                    '<img src="//travisperkins.scene7.com/is/image/travisperkins/M3549_769541_00?defaultImage=travisperkins/missing-product&id=kEsRH3&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Marshalls Indian Buff Sandstone Paving Project Pack 15.23m2 Coverage">',
                        '<p>Marshalls Indian Buff Sandstone Paving Project Pack 15.23m2 Coverage</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£273.63</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/Marshalls-Indian-Sandstone-Paving-5-Size-Project-Pack-Grey-Multi-15-23m2-22mm-Calibrated/p/743017" class="TP090_prod">',
                        '<img src="//travisperkins.scene7.com/is/image/travisperkins/GPID_1000796726_00?defaultImage=travisperkins/missing-product&id=iOdSJ0&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Marshalls Indian Sandstone Paving 5 Size Project Pack Grey Multi 15.23m2 22mm Calibrated">',
                        '<p>Marshalls Indian Sandstone Paving 5 Size Project Pack Grey Multi 15.23m2 22mm Calibrated</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£288.87</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="//www.travisperkins.co.uk/Marshalls-Pendle-Buff-Paving-Slab-450mm-x-450mm-x-32mm/p/794295" class="TP090_prod">',
                        '<img src="//travisperkins.scene7.com/is/image/travisperkins/M3549_794295_00?defaultImage=travisperkins/missing-product&id=w0lTx2&fmt=jpg&fit=constrain,1&wid=900&hei=900" alt="Marshalls Pendle Buff Paving Slab 450mm x 450mm x 32mm">',
                        '<p>Marshalls Pendle Buff Paving Slab 450mm x 450mm x 32mm</p>',
                        '<span class="TP090_price">',
                        '<span class="TP090_price-main">£3.23</span>',
                        '<span class="TP090_price-each">each (ex vat)</span>',
                        '</span>',
                    '</a>',
                    '<a href="www.travisperkins.co.uk/Product/Gardens+Landscaping/Paving+Walling/Decorative-Paving-Slabs/c/1500124" class="TP090_prod TP090_view-all">',
                        '<span class="TP090_view_all-text">',
                            'View all <span>333</span> Decorative <br /> Paving Slabs',
                        '</span>',
                    '</a>',
                '</div>',
            '</div>',
        '</div>',
    '</li>',
    '<a class="TP090_offers" href="/tradeoffers">Offers</a>',
    '</ul>',
    '</div>'
].join(''));

export default nav_HTML;