const variantOptions = [
  {
    volume: '2.5l',
    color: 'white 01',
    finish: 'Matt',
    sku: '969jx',
    url: '/p/lickpro-matt-white-01-emulsion-paint-2-5ltr/969jx',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 01',
    finish: 'Matt',
    sku: '123jx',
    url: '/p/lickpro-matt-white-01-emulsion-paint-5ltr/123jx',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 02',
    finish: 'Matt',
    sku: '502jy',
    url: '/p/lickpro-matt-white-02-emulsion-paint-2-5ltr/502jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 02',
    finish: 'Matt',
    sku: '723jy',
    url: '/p/lickpro-matt-white-02-emulsion-paint-5ltr/723jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 03',
    finish: 'Matt',
    sku: '795jy',
    url: '/p/lickpro-matt-white-03-emulsion-paint-2-5ltr/795jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 03',
    finish: 'Matt',
    sku: '672jy',
    url: '/p/lickpro-matt-white-03-emulsion-paint-5ltr/672jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 04',
    finish: 'Matt',
    sku: '337jy',
    url: '/p/lickpro-matt-white-04-emulsion-paint-2-5ltr/337jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 04',
    finish: 'Matt',
    sku: '348jy',
    url: '/p/lickpro-matt-white-04-emulsion-paint-5ltr/348jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 05',
    finish: 'Matt',
    sku: '304jy',
    url: '/p/lickpro-matt-white-05-emulsion-paint-2-5ltr/304jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 05',
    finish: 'Matt',
    sku: '255jy',
    url: '/p/lickpro-matt-white-05-emulsion-paint-5ltr/255jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 06',
    finish: 'Matt',
    sku: '516jy',
    url: '/p/lickpro-matt-white-06-emulsion-paint-2-5ltr/516jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 06',
    finish: 'Matt',
    sku: '527jy',
    url: '/p/lickpro-matt-white-06-emulsion-paint-5ltr/527jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 07',
    finish: 'Matt',
    sku: '224jy',
    url: '/p/lickpro-matt-white-07-emulsion-paint-2-5ltr/224jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 07',
    finish: 'Matt',
    sku: '606jy',
    url: '/p/lickpro-matt-white-07-emulsion-paint-5ltr/606jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 09',
    finish: 'Matt',
    sku: '817jy',
    url: '/p/lickpro-matt-white-09-emulsion-paint-2-5ltr/817jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 09',
    finish: 'Matt',
    sku: '707JY',
    url: '/p/lickpro-matt-white-09-emulsion-paint-5ltr/707jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 10',
    finish: 'Matt',
    sku: '421jy',
    url: '/p/lickpro-matt-white-10-emulsion-paint-2-5ltr/421jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 10',
    finish: 'Matt',
    sku: '715jx',
    url: '/p/lickpro-matt-white-10-emulsion-paint-5ltr/715jx',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'white 11',
    finish: 'Matt',
    sku: '949jy',
    url: '/p/lickpro-matt-white-11-emulsion-paint-2-5ltr/949jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '5l',
    color: 'white 11',
    finish: 'Matt',
    sku: '566jy',
    url: '/p/lickpro-matt-white-11-emulsion-paint-5ltr/566jy',
    productName: 'Lick pro matt white Emulsion Paint',
  },
  {
    volume: '2.5l',
    color: 'BS B15',
    finish: 'Matt',
    sku: '112Jy',
    url: '/p/lickpro-matt-white-bs-10-b-15-emulsion-paint-2-5ltr/112jy',
    productName: 'LickPRo MAtt While BS Emulsion Paint B15',
  },
  {
    volume: '5l',
    color: 'BS B15',
    finish: 'Matt',
    sku: '280jx',
    url: '/p/lickpro-matt-white-bs-08-b-15-emulsion-paint-5ltr/107jy',
    productName: 'LickPRo MAtt While BS Emulsion Paint B15',
  },
  {
    productName: 'LickPro Matt White BS C31',
    volume: '2.5l',
    color: 'BS C31',
    finish: 'Matt',
    sku: '787jy',
    url: '/p/lickpro-matt-white-bs-08-c-31-emulsion-paint-2-5ltr/787jy',
  },
  {
    productName: 'LickPro Matt White BS C31',
    volume: '5l',
    color: 'BS C31',
    finish: 'Matt',
    sku: '107jy',
    url: '/p/lickpro-matt-white-bs-08-c-31-emulsion-paint-5ltr/280jx',
  },
  {
    productName: 'Lick Pro Matt White RAL 9001 Emulsion Paint',
    volume: '2.5l',
    color: 'RAL 9001',
    finish: 'Matt',
    sku: '607jx',
    url: '/p/lickpro-matt-white-ral-9001-emulsion-paint-2-5ltr/607jx',
  },
  {
    productName: 'Lick Pro Matt White RAL 9001 Emulsion Paint',
    volume: '5l',
    color: 'RAL 9001',
    finish: 'Matt',
    sku: '548jx',
    url: '/p/lickpro-matt-white-ral-9001-emulsion-paint-5ltr/548jx',
  },
  {
    productName: 'LickPro Matt White RAL 9010 Emulsion Paint',
    volume: '2.5l',
    color: 'RAL9010',
    finish: 'Matt',
    sku: '416jy',
    url: '/p/lickpro-matt-white-ral-9010-emulsion-paint-2-5ltr/416jy',
  },
  {
    productName: 'LickPro Matt White RAL 9010 Emulsion Paint',
    volume: '5l',
    color: 'RAL9010',
    finish: 'Matt',
    sku: '575jy',
    url: '/p/lickpro-matt-white-ral-9010-emulsion-paint-5ltr/575jy',
  },
  {
    productName: 'LickPro Matt white BS 10 B15 Emulsion Paint',
    volume: '2.5l',
    color: 'BS 10 B15',
    finish: 'Matt',
    sku: '112Jy',
    url: '/p/lickpro-matt-white-bs-10-b-15-emulsion-paint-2-5ltr/112jy',
  },
  {
    productName: 'LickPro Matt white BS 10 B15 Emulsion Paint',
    volume: '5l',
    color: 'BS 10 B15',
    finish: 'Matt',
    sku: '454jy',
    url: '/p/lickpro-matt-white-bs-10-b-15-emulsion-paint-5ltr/454jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 01',
    finish: 'Eggshell',
    sku: '561jy',
    url: '/p/lickpro-eggshell-white-01-emulsion-paint-2-5ltr/561jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 01',
    finish: 'Eggshell',
    sku: '770jy',
    url: '/p/lickpro-eggshell-white-01-emulsion-paint-5ltr/770jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 02',
    finish: 'Eggshell',
    sku: '867jx',
    url: '/p/lickpro-eggshell-white-02-emulsion-paint-2-5ltr/867jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 02',
    finish: 'Eggshell',
    sku: '614jy',
    url: '/p/lickpro-eggshell-white-02-emulsion-paint-5ltr/614jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 03',
    finish: 'Eggshell',
    sku: '700jy',
    url: '/p/lickpro-eggshell-white-03-emulsion-paint-2-5ltr/700jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 03',
    finish: 'Eggshell',
    sku: '450jy',
    url: '/p/lickpro-eggshell-white-03-emulsion-paint-5ltr/450jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 04',
    finish: 'Eggshell',
    sku: '977jy',
    url: '/p/lickpro-eggshell-white-04-emulsion-paint-2-5ltr/977jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 04',
    finish: 'Eggshell',
    sku: '427jy',
    url: '/p/lickpro-eggshell-white-04-emulsion-paint-5ltr/427jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 05',
    finish: 'Eggshell',
    sku: '749jy',
    url: '/p/lickpro-eggshell-white-05-emulsion-paint-2-5ltr/749jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 05',
    finish: 'Eggshell',
    sku: '295jy',
    url: '/p/lickpro-eggshell-white-05-emulsion-paint-5ltr/295jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 06',
    finish: 'Eggshell',
    sku: '453jx',
    url: '/p/lickpro-eggshell-white-06-emulsion-paint-2-5ltr/453jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 06',
    finish: 'Eggshell',
    sku: '200jx',
    url: '/p/lickpro-eggshell-white-06-emulsion-paint-5ltr/200jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 07',
    finish: 'Eggshell',
    sku: '233jy',
    url: '/p/lickpro-eggshell-white-07-emulsion-paint-2-5ltr/233jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 07',
    finish: 'Eggshell',
    sku: '318jx',
    url: '/p/lickpro-eggshell-white-07-emulsion-paint-5ltr/318jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 09',
    finish: 'Eggshell',
    sku: '728jy',
    url: '/p/lickpro-eggshell-white-09-emulsion-paint-2-5ltr/728jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 09',
    finish: 'Eggshell',
    sku: '626jy',
    url: '/p/lickpro-eggshell-white-09-emulsion-paint-5ltr/626jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 10',
    finish: 'Eggshell',
    sku: '354jx',
    url: '/p/lickpro-eggshell-white-10-emulsion-paint-2-5ltr/354jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 10',
    finish: 'Eggshell',
    sku: '247jy',
    url: '/p/lickpro-eggshell-white-10-emulsion-paint-5ltr/247jy',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '2.5l',
    color: 'white 11',
    finish: 'Eggshell',
    sku: '430jx',
    url: '/p/lickpro-eggshell-white-11-emulsion-paint-2-5ltr/430jx',
  },
  {
    productName: 'Lick Pro Eggshell white emulsion paint',
    volume: '5l',
    color: 'white 11',
    finish: 'Eggshell',
    sku: '347jy',
    url: '/p/lickpro-eggshell-white-11-emulsion-paint-5ltr/347jy',
  },
  {
    productName: 'LickPro Eggshell White Emulsion Paint',
    volume: '2.5l',
    color: 'RAL 9001',
    finish: 'Eggshell',
    sku: '955jy',
    url: '/p/lickpro-eggshell-white-ral-9001-emulsion-paint-2-5ltr/955jy',
  },
  {
    productName: 'LickPro Eggshell White Emulsion Paint',
    volume: '5l',
    color: 'RAL 9001',
    finish: 'Eggshell',
    sku: '772jy',
    url: '/p/lickpro-eggshell-white-ral-9001-emulsion-paint-5ltr/772jy',
  },
  {
    productName: 'LickPro Eggshell White BS 10 B15 Emulsion Paint',
    volume: '2.5l',
    color: 'BS 10 B15',
    finish: 'Eggshell',
    sku: '637jy',
    url: '/p/lickpro-eggshell-white-bs-10-b-15-emulsion-paint-2-5ltr/637jy',
  },
  {
    productName: 'LickPro Eggshell White BS 10 B15 Emulsion Paint',
    volume: '5l',
    color: 'BS 10 B15',
    finish: 'Eggshell',
    sku: '100jy',
    url: '/p/lickpro-eggshell-white-bs-10-b-15-emulsion-paint-5ltr/100jy',
  },
  {
    productName: 'LickPro Eggshell White BS 08 C31 Emulsion Paint',
    volume: '2.5l',
    color: 'BS 08 C31',
    finish: 'Eggshell',
    sku: '610jy',
    url: '/p/lickpro-eggshell-white-bs-08-c-31-emulsion-paint-2-5ltr/610jy',
  },
  {
    productName: 'LickPro Eggshell White BS 08 C31 Emulsion Paint',
    volume: '5l',
    color: 'BS 08 C31',
    finish: 'Eggshell',
    sku: '498jy',
    url: '/p/lickpro-eggshell-white-bs-08-c-31-emulsion-paint-5ltr/498jy',
  },
  {
    productName: 'LickPro Eggshell White BS 08 B15 Emulsion Paint',
    volume: '2.5l',
    color: 'BS 08 B15',
    finish: 'Eggshell',
    sku: '326jy',
    url: '/p/lickpro-eggshell-white-bs-08-b-15-emulsion-paint-2-5ltr/362jy',
  },
  {
    productName: 'LickPro Eggshell White BS 08 B15 Emulsion Paint',
    volume: '5l',
    color: 'BS 08 B15',
    finish: 'Eggshell',
    sku: '413jx',
    url: '/p/lickpro-eggshell-white-bs-08-b-15-emulsion-paint-5ltr/413jx',
  },
  {
    productName: 'Lick Pro Eggshell white RAL 9010 Emulsion Paint',
    volume: '2.5l',
    color: 'RAL 9010',
    finish: 'Eggshell',
    sku: '246jy',
    url: '/p/lickpro-eggshell-white-ral-9010-emulsion-paint-2-5ltr/246jy',
  },
  {
    productName: 'Lick Pro Eggshell white RAL 9010 Emulsion Paint',
    volume: '5l',
    color: 'RAL 9010',
    finish: 'Eggshell',
    sku: '102jy',
    url: '/p/lickpro-eggshell-white-ral-9010-emulsion-paint-5ltr/102jy',
  },
  {
    productName: 'Dulux Matt Emulsion Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Matt',
    sku: '9481V',
    url: '/p/dulux-matt-pure-brilliant-white-emulsion-paint-2-5ltr/9481v',
  },
  {
    productName: 'Dulux Matt Emulsion Paint',
    volume: '10L',
    color: 'Pure Brilliant White',
    finish: 'Matt',
    sku: '1013v',
    url: '/p/dulux-matt-pure-brilliant-white-emulsion-paint-10ltr/1013v',
  },
  {
    productName: 'Dulux EasyCare Matt Emulsion Paint',
    volume: '2.5l',
    color: 'White Cotton',
    finish: 'Matt',
    sku: '2000T',
    url: '/p/dulux-easycare-matt-white-cotton-emulsion-paint-2-5ltr/2000t',
  },
  {
    productName: 'Dulux EasyCare Matt Emulsion Paint',
    volume: '10L',
    color: 'Pure Brilliant White',
    finish: 'Matt',
    sku: '6583v',
    url: '/p/dulux-easycare-matt-pure-brilliant-white-emulsion-paint-10ltr/6583v',
  },
  {
    productName: 'Dulux EasyCare Matt Emulsion Paint',
    volume: '2.5l',
    color: 'White Mist',
    finish: 'Matt',
    sku: '6797T',
    url: '/p/dulux-easycare-matt-white-mist-emulsion-paint-2-5ltr/6797t',
  },
  {
    productName: 'Dulux Silk Emulsion Paint',
    volume: '2.5l',
    color: 'Pure Brilliant White',
    finish: 'Silk',
    sku: '4503v',
    url: '/p/dulux-silk-pure-brilliant-white-emulsion-paint-2-5ltr/4503v',
  },
  {
    productName: 'Dulux Silk Emulsion Paint',
    volume: '10L',
    color: 'Pure Brilliant White',
    finish: 'Silk',
    sku: '8071v',
    url: '/p/dulux-silk-pure-brilliant-white-emulsion-paint-10ltr/8071v',
  },
  {
    productName: 'Dulux EasyCare Soft Sheen Pure Brilliant White Emulsion Bathroom Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Soft Sheen',
    sku: 42729,
    url: '/p/dulux-easycare-soft-sheen-pure-brilliant-white-emulsion-bathroom-paint-2-5ltr/42729',
  },
  {
    productName: 'Dulux Easycare Matt Pure Brilliant White Emulsion Kitchen Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Matt',
    sku: 84926,
    url: '/p/dulux-easycare-matt-pure-brilliant-white-emulsion-kitchen-paint-2-5ltr/84926',
  },
  {
    productName: 'Dulux Trade Satin Pure brilliant White Trim Paint',
    volume: '1L',
    color: 'Pure Brilliant White',
    finish: 'Satin',
    sku: 13081,
    url: '/p/dulux-trade-satin-pure-brilliant-white-trim-paint-1ltr/13081',
  },
  {
    productName: 'Dulux Trade Satin Pure brilliant White Trim Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Satin',
    sku: 12367,
    url: '/p/dulux-trade-satin-pure-brilliant-white-trim-paint-2-5ltr/12367',
  },
  {
    productName: 'Dulux Trade High Gloss Pure Brilliant White Trim Paint',
    volume: '1L',
    color: 'Pure Brilliant White',
    finish: 'High Gloss',
    sku: 82973,
    url: '/p/dulux-trade-high-gloss-pure-brilliant-white-trim-paint-1ltr/82973',
  },
  {
    productName: 'Dulux Trade High Gloss Pure Brilliant White Trim Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'High Gloss',
    sku: 83378,
    url: '/p/dulux-trade-high-gloss-pure-brilliant-white-trim-paint-2-5ltr/83378',
  },
  {
    productName: 'Dulux Trade Satin Pure brilliant White Trim Quick-Dry Paint',
    volume: '1L',
    color: 'Pure Brilliant White',
    finish: 'Satin',
    sku: '1450H',
    url: '/p/dulux-trade-satin-pure-brilliant-white-trim-quick-dry-paint-1ltr/1450h',
  },
  {
    productName: 'Dulux Trade Satin Pure brilliant White Trim Quick-Dry Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Satin',
    sku: '9723H',
    url: '/p/dulux-trade-satin-pure-brilliant-white-trim-quick-dry-paint-2-5ltr/9723h',
  },
  {
    productName: 'Dulux Trade High Gloss Pure Brilliant White Trim Quick-Dry Paint',
    volume: '1L',
    color: 'Pure Brilliant White',
    finish: 'High Gloss',
    sku: '2352H',
    url: '/p/dulux-trade-high-gloss-pure-brilliant-white-trim-quick-dry-paint-1ltr/2352h',
  },
  {
    productName: 'Dulux Trade High Gloss Pure Brilliant White Trim Quick-Dry Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'High Gloss',
    sku: '3522P',
    url: '/p/dulux-trade-high-gloss-pure-brilliant-white-trim-quick-dry-paint-2-5ltr/3522p',
  },
  {
    productName: 'Dulux Trade Diamond Eggshell Pure Brilliant White Trim Diamon Quick-Drying Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Eggshell',
    sku: 32853,
    url: '/p/dulux-trade-diamond-eggshell-pure-brilliant-white-trim-diamond-quick-drying-paint-2-5ltr/32853',
  },
  {
    productName: 'Dulux Trade Diamond Eggshell Pure Brilliant White Trim Diamon Quick-Drying Paint',
    volume: '5L',
    color: 'Pure Brilliant White',
    finish: 'Eggshell',
    sku: '2609G',
    url: '/p/dulux-trade-diamond-eggshell-pure-brilliant-white-trim-diamond-quick-drying-paint-5ltr/2609g',
  },
  {
    productName: 'Dulux Trade Eggshell Pure Brilliant White Trim Solvent-Based Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Eggshell',
    sku: 12363,
    url: '/p/dulux-trade-eggshell-pure-brilliant-white-trim-solvent-based-paint-2-5ltr/12363',
  },
  {
    productName: 'Dulux Trade Matt White Emulsion Paint',
    volume: '5L',
    color: 'White',
    finish: 'Matt',
    sku: 48384,
    url: '/p/dulux-trade-matt-white-emulsion-paint-5ltr/48384',
  },
  {
    productName: 'Dulux Trade Matt White Emulsion Paint',
    volume: '10L',
    color: 'White',
    finish: 'Matt',
    sku: 75849,
    url: '/p/dulux-trade-matt-white-emulsion-paint-10ltr/75849',
  },
  {
    productName: 'Dulux Trade Matt White Emulsion Paint',
    volume: '10L',
    color: 'White',
    finish: 'Matt',
    sku: 43988,
    url: '/p/dulux-trade-matt-white-emulsion-paint-10ltr/43988',
  },
  {
    productName: 'ulsion Paint Retail Retail Matt Brilliant White Emulsion Paint',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: '7291V',
    url: '/p/leyland-retail-retail-matt-brilliant-white-emulsion-paint-10ltr/7291v',
  },
  {
    productName: 'Leyland Trade Satin Brilliant White Trim Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'Satin',
    sku: '325HF',
    url: '/p/leyland-trade-satin-brilliant-white-trim-paint-750ml/325hf',
  },
  {
    productName: 'Leyland Trade Satin Brilliant White Trim Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Satin',
    sku: 75370,
    url: '/p/leyland-trade-satin-brilliant-white-trim-paint-2-5ltr/75370',
  },
  {
    productName: 'Leyland Trade Gloss Brilliant White Trim Fast-Drying Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'Gloss',
    sku: 52285,
    url: '/p/leyland-trade-gloss-brilliant-white-trim-fast-drying-paint-750ml/52285',
  },
  {
    productName: 'Leyland Trade Gloss Brilliant White Trim Fast-Drying Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Gloss',
    sku: 80033,
    url: '/p/leyland-trade-gloss-brilliant-white-trim-fast-drying-paint-2-5ltr/80033',
  },
  {
    productName: 'Leyland Trade Gloss Brilliant White Trim Non-Drip Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'Gloss',
    sku: 37216,
    url: '/p/leyland-trade-gloss-white-trim-non-drip-paint-750ml/37216',
  },
  {
    productName: 'Leyland Trade Gloss Brilliant White Trim Non-Drip Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Gloss',
    sku: 48759,
    url: '/p/leyland-trade-gloss-brilliant-white-trim-non-drip-paint-2-5ltr/48759',
  },
  {
    productName: 'Leyland Trade Eggshell Brilliant White Emulsion Acrylic Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'Eggshell',
    sku: '508HF',
    url: '/p/leyland-trade-eggshell-brilliant-white-emulsion-acrylic-paint-750ml/508hf',
  },
  {
    productName: 'Leyland Trade Eggshell Brilliant White Emulsion Acrylic Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Eggshell',
    sku: 45956,
    url: '/p/leyland-trade-eggshell-brilliant-white-emulsion-acrylic-paint-2-5ltr/45956',
  },
  {
    productName: 'Leyland Trade High Gloss Brilliant White Trim Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'High Gloss',
    sku: '6915H',
    url: '/p/leyland-trade-high-gloss-brilliant-white-trim-paint-750ml/6915h',
  },
  {
    productName: 'Leyland Trade High Gloss Brilliant White Trim Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'High Gloss',
    sku: 43021,
    url: '/p/leyland-trade-high-gloss-brilliant-white-trim-paint-2-5ltr/43021',
  },
  {
    productName: 'Leyland Trade High Gloss Brilliant White Trim Paint',
    volume: '5L',
    color: 'Brilliant White',
    finish: 'High Gloss',
    sku: 60193,
    url: '/p/leyland-trade-high-gloss-brilliant-white-trim-paint-5ltr/60193',
  },
  {
    productName: 'Leyland Trade Smart Eggshell Brilliant White Emulsion Smart Multi-Surface Paint',
    volume: '750ml',
    color: 'Brilliant White',
    finish: 'Eggshell',
    sku: '919PT',
    url: '/p/leyland-trade-smart-eggshell-brilliant-white-emulsion-smart-multi-surface-paint-750ml/919pt',
  },
  {
    productName: 'Leyland Trade Smart Eggshell Brilliant White Emulsion Smart Multi-Surface Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Eggshell',
    sku: '289PT',
    url: '/p/leyland-trade-smart-eggshell-brilliant-white-emulsion-smart-multi-surface-paint-2-5ltr/289pt',
  },
  {
    productName: 'Leyland Trade Smart Eggshell Brilliant White Emulsion Smart Multi-Surface Paint',
    volume: '5l',
    color: 'Brilliant White',
    finish: 'Eggshell',
    sku: '815PT',
    url: '/p/leyland-trade-smart-eggshell-brilliant-white-emulsion-smart-multi-surface-paint-5ltr/815pt',
  },
  {
    productName: 'Leyland Trade Smart Matt Brilliant White Emulsion Paint',
    volume: '2.5L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: '229PT',
    url: '/p/leyland-trade-smart-matt-brilliant-white-emulsion-paint-2-5ltr/229pt',
  },
  {
    productName: 'Leyland Trade Smart Matt Brilliant White Emulsion Paint',
    volume: '5L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: '417PT',
    url: '/p/leyland-trade-smart-matt-brilliant-white-emulsion-paint-5ltr/417pt',
  },
  {
    productName: 'Leyland Trade Contract Matt Brilliant White Emulsion Paint',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: 33680,
    url: '/p/leyland-trade-contract-matt-brilliant-white-emulsion-paint-10ltr/33680',
  },
  {
    productName: 'Leyland Trade Vinyl Matt Brilliant White Emulsion Paint',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: 28311,
    url: '/p/leyland-trade-vinyl-matt-brilliant-white-emulsion-paint-10ltr/28311',
  },
  {
    productName: 'Leyland Trade Contract Silk Brilliant White Emulsion',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Silk',
    sku: 91723,
    url: '/p/leyland-trade-contract-silk-brilliant-white-emulsion-paint-10ltr/91723',
  },
  {
    productName: 'Leyland Trade Vinyl Silk Brilliant White Emulsion Paint',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Silk',
    sku: '9180V',
    url: '/p/leyland-trade-vinyl-silk-brilliant-white-emulsion-paint-10ltr/9180v',
  },
  {
    productName: 'Leyland Trade Super Leytex Matt Brilliant White Emulsion Paint',
    volume: '15L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: 60248,
    url: '/p/leyland-trade-super-leytex-matt-brilliant-white-emulsion-paint-15ltr/60248',
  },
  {
    productName: 'No Nonsese Gloss Pure Brilliant White Acrylic Water Based Paint',
    volume: '1L',
    color: 'Pure Brilliant White',
    finish: 'Gloss',
    sku: '3399X',
    url: '/p/no-nonsense-gloss-pure-brilliant-white-acrylic-water-based-paint-1ltr/3399x',
  },
  {
    productName: 'No Nonsese Gloss Pure Brilliant White Acrylic Water Based Paint',
    volume: '2.5L',
    color: 'Pure Brilliant White',
    finish: 'Gloss',
    sku: '8658X',
    url: '/p/no-nonsense-gloss-pure-brilliant-white-acrylic-water-based-paint-2-5ltr/8658x',
  },
  {
    productName: 'No Nonsese Satin Brilliant White Acrylic Water Based Paint',
    volume: '1L',
    color: 'Brilliant White',
    finish: 'Satin',
    sku: '699FR',
    url: '/p/no-nonsense-satin-brilliant-white-acrylic-water-based-paint-1ltr/699fr',
  },
  {
    productName: 'No Nonsese Satin Brilliant White Acrylic Water Based Paint',
    volume: '2.5l',
    color: 'Brilliant White',
    finish: 'Satin',
    sku: '8658X',
    url: '/p/no-nonsense-gloss-pure-brilliant-white-acrylic-water-based-paint-2-5ltr/8658x',
  },
  {
    productName: 'No Nonsense Matt Brilliant White Emulsion Contract Paint',
    volume: '10L',
    color: 'Brilliant White',
    finish: 'Matt',
    sku: '532FV',
    url: '/p/no-nonsense-matt-brilliant-white-emulsion-contract-paint-10ltr/532fv',
  },
  {
    productName: 'V33 Satin Acrylic Wall Tile & Panelling Paint',
    volume: '750ml',
    color: 'White',
    finish: 'Satin',
    sku: '403GX',
    url: '/p/v33-satin-white-acrylic-wall-tile-panelling-paint-750ml/403gx',
  },
  {
    productName: 'V33 Satin Acrylic Wall Tile & Panelling Paint',
    volume: '750ml',
    color: 'Cotton Off-White',
    finish: 'Satin',
    sku: '727GX',
    url: '/p/v33-satin-cotton-off-white-acrylic-wall-tile-panelling-paint-750ml/727gx',
  },
  {
    productName: 'V33 Satin Trim Cabinet Paint',
    volume: '750ml',
    color: 'White',
    finish: 'Satin',
    sku: '881GV',
    url: '/p/v33-satin-white-trim-cabinet-paint-750ml/881gv',
  },
  {
    productName: 'V33 Satin Trim Cabinet Paint',
    volume: '750ml',
    color: 'Cotton Off-White',
    finish: 'Satin',
    sku: '337GV',
    url: '/p/v33-satin-cotton-off-white-trim-cabinet-paint-750ml/337gv',
  },
  {
    productName: 'V33 Satin Acrylic Floor & Stair Paint',
    volume: '750ml',
    color: 'White',
    finish: 'Satin',
    sku: '723GX',
    url: '/p/v33-satin-white-acrylic-floor-stair-paint-750ml/723gx',
  },
  {
    productName: 'V33 Satin Acrylic Floor & Stair Paint',
    volume: '750ml',
    color: 'Cotton Off-White',
    finish: 'Satin',
    sku: '983GX',
    url: '/p/v33-satin-cotton-off-white-acrylic-floor-stair-paint-750ml/983gx',
  },
];

export default variantOptions;
