export const cartRecommendations = [
  {
    productName: 'Are We Having Pancakes? Side Plate',
    ProductUrl: '/are-we-having-pancakes-side-plate/',
    brandName: 'Jimbob Art',
    productId: '86460',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/omcfbr9gay4dy3ahhuit',
    top15: 'true',
  },
  {
    productName: 'Lolita Loop Earrings',
    ProductUrl: '/lolita-loop-earrings/',
    brandName: 'Mirabelle Jewellery',
    productId: '250412',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/ath5k1m7qtccscdxquog',
    top15: 'true',
  },

  {
    productName: 'Classic Laines Toffee Slippers With Artisan Golden Honeybee',
    ProductUrl: '/classic-laines-toffee-slippers-with-artisan-golden-honeybee/',
    brandName: 'LAINES LONDON',
    productId: '772449',
    image:
      'https://res.cloudinary.com/wolfandbadger/image/upload/f_auto,q_auto:best,c_pad,h_800,w_800/products/tflwqrhvhpqamlv4tq3v',
    top15: 'true',
  },
  {
    productName: 'Balloon Poodle Threader Earrings-Oliver Green',
    ProductUrl: '/balloon-poodle-threader-earrings/',
    brandName: 'Ninemoo',
    productId: '781181',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/m0xn2hd2rikr1bsjt0f5',
    top15: 'true',
  },
  {
    productName: 'List Of Countries World Map',
    ProductUrl: '/list-of-countries/',
    brandName: 'Bold Tuesday',
    productId: '133765',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/ou7evtf1vjfzh9x8vorx',
    top15: 'true',
  },
  {
    productName: 'Rita Jumper - Navy, Love Rays',
    ProductUrl: '/rita-jumper-navy-love-rays/',
    brandName: 'Sugarhill Brighton',
    productId: '654354',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/wzblati5de1w7hmhiiuz',
    top15: 'true',
  },
  {
    productName: 'Dolly Fun Pom Slider Slippers In Red',
    ProductUrl: '/dolly-fun-pom-slider-slippers-in-red/',
    brandName: 'Pretty You',
    productId: '704182',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/wxlgeb3wgxyvkeldo6qs',
    top15: 'true',
  },
  {
    productName: 'Head Chef Double Oven Glove',
    ProductUrl: '/head-chef-double-oven-glove/',
    brandName: 'Stuart Gardiner Design',
    productId: '147742',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/e9zevtkska7abhrvcptk',
    top15: 'true',
  },
  {
    productName: 'Not Amewsed Enamel Pin In Black & Gold',
    ProductUrl: '/not-amewsed-enamel-pin-in-black-gold/',
    brandName: 'Amar&Riley',
    productId: '723613',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/ekp97wppdwaxnfukfwq5',
    top15: 'true',
  },
  {
    productName: 'Cloud Comb In Iridescent Labradorite',
    ProductUrl: '/cloud-comb-in-iridescent-labradorite/',
    brandName: 'MLE',
    productId: '520985',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/onibx05dvv7lq0fzp96m',
    top15: 'true',
  },
  {
    productName: 'I Love My Pussy Pet Bowl',
    ProductUrl: '/i-love-my-pussy-pet-bowl/',
    brandName: 'Cheeky Mare',
    productId: '444877',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/lgauzj3knsizynoqdbke',
    top15: 'true',
  },
  {
    productName: 'Silver Mix Tape Necklace',
    ProductUrl: '/silver-mix-tape-necklace/',
    brandName: 'Scream Pretty',
    productId: '474325',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/fqbbtrq2ssqrdgwa1drc',
    top15: 'true',
  },
  {
    productName: 'Ladies Trad Satin Pyjama Set - Lucky Magpie',
    ProductUrl: '/ladies-trad-satin-pyjama-set-lucky-magpie/',
    brandName: 'Their Nibs',
    productId: '683008',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/dyxke7usrmgv0gmbfo2f',
    top15: 'true',
  },
  {
    productName: 'La Piscine Giclée Art Print',
    ProductUrl: '/la-piscine-a3-art-print/',
    brandName: 'Fanclub',
    productId: '347930',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/e5mn1atkmdshje45eiko',
    top15: 'true',
  },
  {
    productName: 'Badger Pancakes Tea Towel',
    ProductUrl: '/badger-pancakes-tea-towel/',
    brandName: 'Jimbob Art',
    productId: '359472',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/mitpp1hclkh2hklqypft',
    top15: 'true',
  },
  {
    productName: 'Glass Ceiling Emerald Green Bamboo Top',
    ProductUrl: '/glass-ceiling-emerald-green-bamboo-top/',
    brandName: 'Me & Thee',
    productId: '662318',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/ht1tb390zdaq66lefspu',
    top15: 'true',
  },
  {
    productName: 'Classic Laines Navy Slippers With Artisan Golden Honeybee',
    ProductUrl: '/classic-laines-navy-slippers-with-artisan-golden-honeybee/',
    brandName: 'LAINES LONDON',
    productId: '772434',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/tvduflconxrkmohkydij',
    top15: 'false',
  },
  {
    productName: 'Pastel Prosecco Tea Cup & Saucer',
    ProductUrl: '/pastel-prosecco-tea-cup-saucer/',
    brandName: 'Yvonne Ellen',
    productId: 'bad link (404)',
    image: '',
    top15: 'false',
  },
  {
    productName: 'Water Meadow Breathing Balm - 30ml',
    ProductUrl: '/pastel-prosecco-tea-cup-saucer/',
    brandName: 'Bertioli by Thyme',
    productId: 'bad link (404)',
    image: '',
    top15: 'false',
  },
  {
    productName: 'Are We Having Pancakes? Side Plate',
    ProductUrl: '/are-we-having-pancakes-side-plate/',
    brandName: 'Jimbob Art',
    productId: '86460',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/omcfbr9gay4dy3ahhuit',
    top15: 'false',
  },
  {
    productName: 'Pancakes Go Here SproductIde Plate',
    ProductUrl: '/pancakes-go-here/',
    brandName: 'Jimbob Art',
    productId: '254981',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/syr5batrhx4czhjw1ha2',
    top15: 'false',
  },
  {
    productName: 'At Last - Etta James - Song Lyric Print',
    ProductUrl: '/at-last-etta-james-song-lyric-print/',
    brandName: 'Reign & Hail',
    productId: '513936',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/e4rkcb99aqt7vz2umgtw',
    top15: 'false',
  },
  {
    productName: 'Silver Screw Cuff Bracelet',
    ProductUrl: '/all-silver-cuff/',
    brandName: 'Opes Robur',
    productId: '83366',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/z2yz2xe2bglt1r4vwulj',
    top15: 'false',
  },
  {
    productName: 'Lolita Loop Earrings',
    ProductUrl: '/lolita-loop-earrings/',
    brandName: 'Mirabelle Jewellery',
    productId: '250412',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/ath5k1m7qtccscdxquog',
    top15: 'false',
  },
  {
    productName: 'Paintjob Leggings',
    ProductUrl: '/paintjob-leggings/',
    brandName: 'Aloha From Deer',
    productId: '255275',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/rh3o4rneoeosmkqzkgdo',
    top15: 'false',
  },
  {
    productName: 'Asgard Duo Cats Giclée Print',
    ProductUrl: '/asgard-duo-cats/',
    brandName: 'Baldy And The FproductIdget',
    productId: '457608',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/uonqtmqcwzuwilabhmms',
    top15: 'false',
  },
  {
    productName: 'Rock Cake Apron',
    ProductUrl: '/rock-cake-apron/',
    brandName: 'Stuart Gardiner Design',
    productId: '559655',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/lvjjftd0wzcvieyvpjfj',
    top15: 'false',
  },
  {
    productName: "May Contain Biscuits' Tote Bag",
    ProductUrl: '/may-contain-biscuits-tote-bag/',
    brandName: 'Jimbob Art',
    productId: '307010',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/wattv0jyvyobnbivfodv',
    top15: 'false',
  },
  {
    productName: 'Silver Balloon Dog Necklace',
    ProductUrl: '/silver-balloon-dog-necklace/',
    brandName: 'Scream Pretty',
    productId: '471921',
    image: 'https://res.cloudinary.com/wolfandbadger/image/upload/c_pad,h_1500,w_1500/products/vj7mb1qrfvhktcax2qjs',
    top15: 'false',
  },
];

export const currencyConfig = {
  uk: {
    code: 'GBP',
    symbol: '£',
    region: 'uk',
  },
  us: {
    code: 'USD',
    symbol: '$',
    region: 'us',
  },
  ca: {
    code: 'CAD',
    symbol: 'C$',
    region: 'ca',
  },
  eu: {
    code: 'EUR',
    symbol: '€',
    region: 'eu',
  },
  au: {
    code: 'AUD',
    symbol: 'A$',
    region: 'au',
  },
  row: {
    code: 'USD',
    symbol: '$',
    region: 'global',
  },
};
