export const dataArr = [
  {
    id: 189,
    title: `2 x medium pizzas <br/> 2 x side <br/> 1 x large drink (sugar tax may apply) `,
  },
  {
    id: 181,
    title: `2 x large pizzas <br/> 2 x side <br/> 1 x large drink (sugar tax may apply)`,
  },
  {
    id: 626,
    title: `1 x medium pizza <br/> 1 x classic side <br/> 1 x regular drink`,
  },
  { id: 619, title: `1 x large pizza <br/> 2 x classic side` },
  {
    id: 169,
    title: `Buy one pizza and get another up to the same size and value free`,
  },
  {
    id: 623,
    title: `Buy one pizza and get another up to the same size and value free <br/> (Tuesday only)`,
  },
  {
    id: 620,
    title: `1 x large pizza <br/> 1 x classic side <br/> 1 x premium chicken side`,
  },
  {
    id: 68,
    title: `Buy one pizza and get another up to the same size and value free`,
  },
  { id: 248, title: `1 x large pizza (Add £2 for XXL)` },
  { id: 273, title: `1 x XXL pizza` },
  { id: 624, title: `Buy one side and get another one free (Tuesday only)` },
  { id: 118, title: `1 x ice cream` },
  {
    id: 67,
    title: `Buy one pizza and get another up to the same size and value free (excluding small)`,
  },
  {
    id: 62,
    title: `1 x small pizza <br/> 1 x side <br/> 1 x regular drink (sugar tax may apply)`,
  },
  {
    id: 69,
    title: `Buy one pizza and get another up to the same size and value free plus free 500ml Ben & Jerry's`,
  },
  { id: 470, title: `1 x garlic pizza sticks or potato tots` },
  { id: 250, title: `3 x XXL pizza` },
  {
    id: 57,
    title: `1 x large pizza <br/> 1 x side <br/> 1 x large drink (Sugar tax may apply)`,
  },
  { id: 164, title: `2 x medium pizzas` },
  { id: 654, title: `1 x large pizza (collection only)` },
  { id: 655, title: `1 x XXL pizza (collection only)` },
  { id: 318, title: `1 x large pizza` },
  { id: 173, title: `1 x large cheese & tomato pizza with 2 free toppings` },
  { id: 528, title: `1 x large cheese & tomato pizza with 2 free toppings` },
  { id: 78, title: `1 x large pizza` },
  {
    id: 617,
    title: `1 x large meat-free pizza for £9.99 when you buy a side at full price (excludes CYO pizza)`,
  },
  { id: 39, title: `2 x large pizzas` },
  {
    id: 668,
    title: `1 x small pizza <br/> 1 x classic side <br/> 1 x regular drink (sugar tax may apply) <br/> (Mon – Fri, 11:00 – 15:00 only)`,
  },
  { id: 168, title: `1 x any size pizza` },
  { id: 46, title: `2 x XXL pizzas` },
  { id: 51, title: `1 x large pizza` },
  { id: 63, title: `1 x any XXL pizza plus 2 free sides` },
  { id: 652, title: `1 x medium pizza (collection only)` },
  { id: 653, title: `1 x large pizza (collection only)` },
  { id: 252, title: `1 x medium pizza` },
  { id: 272, title: `1 x medium pizza` },
  { id: 151, title: `1 x large pizza` },
  { id: 637, title: `1 x XXL pizza` },
  { id: 656, title: `1 x XXL pizza (collection only)` },
  { id: 152, title: `1 x large pizza` },
  { id: 138, title: `1 x XXL Pizza` },
  { id: 256, title: `1 x any size pizza (collection only)` },
  { id: 301, title: `1 x giant choc chip cookie (max 1 per order)` },
  { id: 94, title: `1 x any size pizza ` },
  { id: 661, title: `1 x large pizza plus 1 free side ` },
  { id: 88, title: `3 x XXL pizzas (includes CYO with up to 4 toppings)` },
  { id: 628, title: `1 x chocolate scrolls` },
  {
    id: 129,
    title: `1 x large drink <br/> 1 x potato pots <br/> 1 x garlic pizza sticks`,
  },
  {
    id: 667,
    title: `1 x potato tots <br/> 1 x chicken poppers or cauli wings <br/> (Mon – Fri, 11:00 – 15:00 only)`,
  },
  { id: 52, title: `1 x large cheese & tomato pizza with 2 free toppings` },
  { id: 549, title: `1 x XXL pizza` },
  { id: 175, title: `1 x medium pizza` },
  {
    id: 354,
    title: `2 x medium pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)`,
  },
  { id: 378, title: `1 x small cheese & tomato pizza with 2 free toppings` },
  { id: 525, title: `1 x small cheese & tomato pizza with 2 free toppings` },
  { id: 212, title: `1 x large pizza` },
  {
    id: 669,
    title: `1 x chicken poppers <br/> 1 x wings <br/> (Mon – Fri, 11:00 – 15:00 only)`,
  },
  { id: 541, title: `1 x small pizza <br/> 1 x regular drink` },
  { id: 158, title: `1 x medium pizza` },
  { id: 556, title: `1 x free large pizza with 3 toppings` },
  { id: 102, title: `1 x small Cheese & Tomato pizza` },
  {
    id: 211,
    title: `Buy one pizza and get another up to the same size and value free`,
  },
  { id: 190, title: `1 x small pizza` },
  { id: 560, title: `2 x large cheese and tomato pizzas with 2 free toppings` },
  {
    id: 295,
    title: `2 x medium pizzas <br/> 1 x garlic sticks <br/>1 x potato tots <br/> 1 x large drink (sugar tax may apply)`,
  },
  { id: 543, title: `1 x medium pizza` },
  {
    id: 449,
    title: `1 x large pizza <br/> 1 x potato tots <br/> 1 x large drink <br/> (excludes create your own. Sugar tax may apply)`,
  },
  { id: 555, title: `1 x small pizza with 2 free toppings` },
  { id: 180, title: `1 x any size pizza` },
  {
    id: 218,
    title: `2 x large pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)`,
  },
  { id: 125, title: `1 x small pizza` },
  { id: 214, title: `3 x XXL pizzas` },
  {
    id: 372,
    title: `1 x large pizza <br/> 1 x garlic pizza sticks <br/> 1 x potato tots `,
  },
  {
    id: 59,
    title: `1 x medium pizza <br/>1 x garlic pizza sticks <br/> 1 x potato pots <br/> 1 x large drink`,
  },
  { id: 167, title: `2 x XXL pizzas <br/> 2 x sides` },
  { id: 103, title: `1 x giant choc chip cookie (max 1 per order)` },
  { id: 40, title: `2 x large pizzas <br/> 2 x sides` },
  { id: 388, title: `2 x large pizzas <br/> 2 x sides` },
  { id: 618, title: `1 x Vegan Ben & Jerry's ice cream` },
  {
    id: 658,
    title: `2 x large pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)`,
  },
  { id: 640, title: `1 x papadia <br/> 1 x regular drink` },
  { id: 672, title: `3 x papadias` },
  {
    id: 674,
    title: `1 x medium pizza <br/> 1 x papadia <br/> 1 x potato tots`,
  },
  { id: 675, title: `1 x large pizza <br/> 1 x papadia  <br/> 2 x sides` },
];

export const dataObj = {
  39: '2 x large pizzas',
  40: '2 x large pizzas <br/> 2 x sides',
  46: '2 x XXL pizzas',
  51: '1 x large pizza',
  52: '1 x large cheese & tomato pizza with 2 free toppings',
  57: '1 x large pizza <br/> 1 x side <br/> 1 x large drink (Sugar tax may apply)',
  59: '1 x medium pizza <br/>1 x garlic pizza sticks <br/> 1 x potato pots <br/> 1 x large drink',
  62: '1 x small pizza <br/> 1 x side <br/> 1 x regular drink (sugar tax may apply)',
  63: '1 x any XXL pizza plus 2 free sides',
  67: 'Buy one pizza and get another up to the same size and value free (excluding small)',
  68: 'Buy one pizza and get another up to the same size and value free',
  69: "Buy one pizza and get another up to the same size and value free plus free 500ml Ben & Jerry's",
  78: '1 x large pizza',
  88: '3 x XXL pizzas (includes CYO with up to 4 toppings)',
  94: '1 x any size pizza ',
  102: '1 x small Cheese & Tomato pizza',
  103: '1 x giant choc chip cookie (max 1 per order)',
  118: '1 x ice cream',
  125: '1 x small pizza',
  129: '1 x large drink <br/> 1 x potato pots <br/> 1 x garlic pizza sticks',
  138: '1 x XXL Pizza',
  151: '1 x large pizza',
  152: '1 x large pizza',
  158: '1 x medium pizza',
  164: '2 x medium pizzas',
  167: '2 x XXL pizzas <br/> 2 x sides',
  168: '1 x any size pizza',
  169: 'Buy one pizza and get another up to the same size and value free',
  173: '1 x large cheese & tomato pizza with 2 free toppings',
  175: '1 x medium pizza',
  180: '1 x any size pizza',
  181: '2 x large pizzas <br/> 2 x side <br/> 1 x large drink (sugar tax may apply)',
  189: '2 x medium pizzas <br/> 2 x side <br/> 1 x large drink (sugar tax may apply) ',
  190: '1 x small pizza',
  211: 'Buy one pizza and get another up to the same size and value free',
  212: '1 x large pizza',
  214: '3 x XXL pizzas',
  218: '2 x large pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)',
  248: '1 x large pizza (Add £2 for XXL)',
  250: '3 x XXL pizza',
  252: '1 x medium pizza',
  256: '1 x any size pizza (collection only)',
  272: '1 x medium pizza',
  273: '1 x XXL pizza',
  295: '2 x medium pizzas <br/> 1 x garlic sticks <br/>1 x potato tots <br/> 1 x large drink (sugar tax may apply)',
  301: '1 x giant choc chip cookie (max 1 per order)',
  318: '1 x large pizza',
  354: '2 x medium pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)',
  372: '1 x large pizza <br/> 1 x garlic pizza sticks <br/> 1 x potato tots ',
  378: '1 x small cheese & tomato pizza with 2 free toppings',
  388: '2 x large pizzas <br/> 2 x sides',
  449: '1 x large pizza <br/> 1 x potato tots <br/> 1 x large drink <br/> (excludes create your own. Sugar tax may apply)',
  470: '1 x garlic pizza sticks or potato tots',
  525: '1 x small cheese & tomato pizza with 2 free toppings',
  528: '1 x large cheese & tomato pizza with 2 free toppings',
  541: '1 x small pizza <br/> 1 x regular drink',
  543: '1 x medium pizza',
  549: '1 x XXL pizza',
  555: '1 x small pizza with 2 free toppings',
  556: '1 x free large pizza with 3 toppings',
  560: '2 x large cheese and tomato pizzas with 2 free toppings',
  617: '1 x large meat-free pizza for £9.99 when you buy a side at full price (excludes CYO pizza)',
  618: "1 x Vegan Ben & Jerry's ice cream",
  619: '1 x large pizza <br/> 2 x classic side',
  620: '1 x large pizza <br/> 1 x classic side <br/> 1 x premium chicken side',
  623: 'Buy one pizza and get another up to the same size and value free <br/> (Tuesday only)',
  624: 'Buy one side and get another one free (Tuesday only)',
  626: '1 x medium pizza <br/> 1 x classic side <br/> 1 x regular drink',
  628: '1 x chocolate scrolls',
  637: '1 x XXL pizza',
  652: '1 x medium pizza (collection only)',
  653: '1 x large pizza (collection only)',
  654: '1 x large pizza (collection only)',
  655: '1 x XXL pizza (collection only)',
  656: '1 x XXL pizza (collection only)',
  658: '2 x large pizzas <br/> 2 x sides <br/> 1 x large drink (sugar tax may apply)',
  661: '1 x large pizza plus 1 free side ',
  667: '1 x potato tots <br/> 1 x chicken poppers or cauli wings <br/> (Mon – Fri, 11:00 – 15:00 only)',
  668: '1 x small pizza <br/> 1 x classic side <br/> 1 x regular drink (sugar tax may apply) <br/> (Mon – Fri, 11:00 – 15:00 only)',
  669: '1 x chicken poppers <br/> 1 x wings <br/> (Mon – Fri, 11:00 – 15:00 only)',
  640: `1 x papadia <br/> 1 x regular drink`,
  672: `3 x papadias`,
  674: `1 x medium pizza <br/> 1 x papadia <br/> 1 x potato tots`,
  675: `1 x large pizza <br/> 1 x papadia  <br/> 2 x sides`,
};
