var formHTML = [
    '<div class="AC005_number-form">',
    '<a href="#" class="AC005_form-close"><i class="fa fa-times" id="close-contact-slider-icon" style="position: absolute; top: 20px; right: 20px; cursor: pointer; font-size: 2em; color: rgb(136, 136, 136); padding: 12px;"></i></a>',
    '<div class="col-lg-12">',
    '<h2>Just a Moment...</h2>',
    '<div class="AC005_cookie-hide">',
    '<h3>To display the phone number,<br> please enter your company name</h3>',
    '<div class="horizontal-separator"></div>',
    '<br><br>',
    '<div class="row">',
    '<div class="col-lg-4">',
    '<div class="AC005_contact-form">',
    '<div class="AC005_error">The company name must not be empty.</div>',
    '<input type="text">',
    '<input type="submit" class="AC005_submit" value="SHOW NUMBER">',
    '</div>',
    '<span class="AC005_why-hover">Why? <span>Your company name helps us track referrals</span></span>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="AC005_number-blur">',
    '<h3>Phone Number</h3>',
    '<div class="AC005_number">01234 567890</div>',
    '</div>',
    '<br><br>',
    '<div class="col-lg-12">',
    '<div class="v2st-whyask-1">',
    '<h3>What happens next?</h3>',
    '<ul>',
    '<li>By entering your company name, we\'re able to track our referrals.</li>',
    '<li>You\'re free to connect directly with the agency for help with your recruitment needs.</li>',
    '<li>We\'ll never ask for your personal contact information</li>',
    '</ul>',
    '</div>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="AC005_website-form">',
    '<a href="#" class="AC005_form-close"><i class="fa fa-times" id="close-contact-slider-icon" style="position: absolute; top: 20px; right: 20px; cursor: pointer; font-size: 2em; color: rgb(136, 136, 136); padding: 12px;"></i></a>',
    '<div class="col-lg-12">',
    '<div class="AC005_cookie-hide">',
    '<h2>We are sending you to your recruitment agency</h2>',
    '<div class="AC005_cookie-hide">',
    '<h3>Before you go, please enter your company name</h3><p class="AC005_sub-title">This lets the Recruitment agency know where you found them</p>',
    '<div class="horizontal-separator"></div>',
    '<br><br>',
    '</div>',
    '<div class="row">',
    '<div class="col-lg-4">',
    '<div class="AC005_contact-form">',
    '<div class="AC005_error">The company name must not be empty.</div>',
    '<div class="AC005_cookie-hide">',
    '<input type="text" placeholder="Company Name">',
    '<input type="submit" class="AC005_submit" value="Visit Website">',
    '</div>',
    '</div>',
    '</div>',
    '</div>',
    '<br><br>',
    '<div class="col-lg-12">',
    '<div class="v2st-whyask-1">',
    '<h3>Why do we ask for your company name?</h3>',
    '<span>Entering your company name lets the recruiter know<br /> where you found their details.<br /><br /> We WILL NOT ask you to leave your own name or contact<br /> information.</span>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="AC005_cookie-show">',
    '<h2>Redirecting you now...</h2>',
    '<div class="AC005_redirect-now">',
        '<p>Click below if you haven\'t been redirected</p>',
        '<a href="#" target="_blank">Redirect Now</a>',
    '</div>',
    '</div>',
    '</div>',
    '</div>',
    '<div class="AC005_body-cover"></div>'
].join('');

export default formHTML;