export const config = {
  // "Christmas": "https://someimageurl.com/",
  "Clothing": "https://media.mamasandpapas.com/i/mamasandpapas/S11LTV7_HERO_FAIRILSE%20KNIT%20JMPR/Clothing/Baby+Boys+Clothes/New+Season+Boys/New+Season?w=325&fmt=jpg&qlt=75",
  // "View All": "https://media.mamasandpapas.com/i/mamasandpapas/S11LTV7_HERO_FAIRILSE%20KNIT%20JMPR/Clothing/Baby+Boys+Clothes/New+Season+Boys/New+Season?w=325&fmt=jpg&qlt=75",
  "Baby Boys Clothes": "https://media.mamasandpapas.com/i/mamasandpapas/S11LTH5_HERO_CREW%20NECK%20TOP%20WITH%20EMB/Clothing/Baby+Boys+Clothes/New+Season+Boys/New+Season?w=325&fmt=jpg&qlt=75",
  "Baby Girls Clothes": "https://media.mamasandpapas.com/i/mamasandpapas/S11LJP5_HERO_Dandelion-Frill-Top/Clothing/Baby+Girls+Clothes/Tops?w=325&fmt=jpg&qlt=75",
  "Unisex Baby Clothes": "https://media.mamasandpapas.com/i/mamasandpapas/S10AT71_1/Clothing/Clothing+Collections/All+Welcome+to+the+World?w=325&fmt=jpg&qlt=75",
  "Clothing Collections": "https://media.mamasandpapas.com/i/mamasandpapas/S74BHW6_HERO_6pc-Sand-Set/Clothing/Unisex+Baby+Clothes/Outfits+%26+Sets?w=325&fmt=jpg&qlt=75",
  "Newborn": "https://media.mamasandpapas.com/i/mamasandpapas/S536HX6_HERO_2pk-Elephant-Rompers/Clothing/Unisex+Baby+Clothes/Nightwear?w=325&fmt=jpg&qlt=75",
  "Furniture": "https://media.mamasandpapas.com/i/mamasandpapas/raatr0500_atlas_light_oak_3_piece/Nursery/Nursery+Furniture/Furniture+Collections/Atlas?w=325&fmt=jpg&qlt=75",
  "Nursery Furniture": "https://media.mamasandpapas.com/i/mamasandpapas/seox02720_oxford_white_2_piece/Nursery/Nursery+Furniture/Furniture+Collections/Oxford+White?w=325&fmt=jpg&qlt=75",
  "Furniture Collections": "https://media.mamasandpapas.com/i/mamasandpapas/raox02720_oxford_white_3_piece/Nursery/Nursery+Furniture/Furniture+Collections/Oxford+White?w=325&fmt=jpg&qlt=75",
  "Mattresses": "https://media.mamasandpapas.com/i/mamasandpapas/PRDNMCB01_Dual_Core/Nursery/Mattresses/All+Mattresses+%26+Covers/Cot+Bed+Mattresses?w=325&fmt=jpg&qlt=75",
  "Nursery": "https://i1.adis.ws/s/mamasandpapas/7343WW201",
  "Nursery Bedding": "https://i1.adis.ws/s/mamasandpapas/7343WW201",
  "Nursery Decor": "https://i1.adis.ws/s/mamasandpapas/7035WW201",
  "Bedding Collections": "https://i1.adis.ws/s/mamasandpapas/Z9093632",
  "Pushchairs": "https://i1.adis.ws/s/mamasandpapas/577701G00",
  "Pushchairs & Prams": "https://i1.adis.ws/i/mamasandpapas/577501J00_HERO_OCARRO_INKYTEAL_WORLDFACING",
  "Travel Accessories": "https://i1.adis.ws/i/mamasandpapas/599955200-Changing-Bag",
  "Car Seats": "https://media.mamasandpapas.com/i/mamasandpapas/5826LM200_Urban-black-aton-5/Travel/Car+Seats/Baby+Car+Seats?w=325&fmt=jpg&qlt=75",
  "Bathing": "https://i1.adis.ws/s/mamasandpapas/455136300",
  "Bathing & Changing": "https://i1.adis.ws/s/mamasandpapas/477502702",
  "Health & Wellbeing": "https://i1.adis.ws/s/mamasandpapas/415745300",
  "Feeding": "https://i1.adis.ws/s/mamasandpapas/4481AF700",
  "Highchairs & Booster Seats": "https://i1.adis.ws/i/mamasandpapas/412468001_09BUD_GREY_1",
  "Feeding Essentials": "https://media.mamasandpapas.com/i/mamasandpapas/1303GF000_6_OF_10/Brands/Tommee+Tippee%C2%AE+Shop/Tommee+Tippee+Perfect+Prep?w=325&fmt=jpg&qlt=75",
  "Toys & Gifts": "https://i1.adis.ws/s/mamasandpapas/74371PT01",
  "Gifting": "https://media.mamasandpapas.com/i/mamasandpapas/49111TR03_HERO_Imprint-Kit-Frame---Forever-Treasured/Toys+%26+Gifts/Gifting/Baby+Milestone+Gifts?w=325&fmt=jpg&qlt=75",
  "Playtime": "https://i1.adis.ws/i/mamasandpapas/7594WC100_N_1",
}