export default {
  0: {
    'badgeTitle': 'Perfect gift',
    'id': '6856289b26b1d244ad20617bb7',
    'dataItemId': 'christmas-h-box',
    'url': '/uk/christmas-h-box.html',
    'img': {
      'url': 'https://www.hotelchocolat.com/dw/image/v2/AAZP_PRD/on/demandware.static/-/Sites-hotelchocolat-master-catalog/default/dwb867b438/images/140464.jpg?sw=180&sh=180&sm=fit',
      'title': 'The Classic Christmas H-Box',
    },
    'prodName': 'The Classic Christmas H-Box',
    'prodName24': 'The Classic Christmas H-…',
    'prodName40': 'The Classic Christmas H-Box…',
    'price': '£13.50',
    'stars': '91%',
  },
  1: {
    'badgeTitle': 'Gift wrapped',
    'id': '6856289b26b1d244ad20617bb7',
    'url': '/uk/christmas-h-box.html',
    'img': {
      'url': 'https://www.hotelchocolat.com/dw/image/v2/AAZP_PRD/on/demandware.static/-/Sites-hotelchocolat-master-catalog/default/dwf45077cd/images/120399.jpg?sw=180&sh=180&sm=fit',
      'title': 'The Classic Christmas H-Box',
    },
    'prodName': 'The Classic Christmas H-Box',
    'prodName24': 'The Classic Christmas H-…',
    'prodName40': 'The Classic Christmas H-Box…',
    'price': '£13.50',
    'stars': '91%',
  },
  2: {
    'badgeTitle': 'Perfect gift',
    'id': '6856289b26b1d244ad20617bb7',
    'url': '/uk/christmas-h-box.html',
    'img': {
      'url': 'https://www.hotelchocolat.com/dw/image/v2/AAZP_PRD/on/demandware.static/-/Sites-hotelchocolat-master-catalog/default/dwb867b438/images/140464.jpg?sw=180&sh=180&sm=fit',
      'title': 'The Classic Christmas H-Box',
    },
    'prodName': 'The Classic Christmas H-Box',
    'prodName24': 'The Classic Christmas H-…',
    'prodName40': 'The Classic Christmas H-Box…',
    'price': '£13.50',
    'stars': '91%',
  },
  3: {
    'badgeTitle': 'Perfect gift',
    'id': '6856289b26b1d244ad20617bb7',
    'url': '/uk/christmas-h-box.html',
    'img': {
      'url': 'https://www.hotelchocolat.com/dw/image/v2/AAZP_PRD/on/demandware.static/-/Sites-hotelchocolat-master-catalog/default/dw37167074/images/310361.jpg?sw=180&sh=180&sm=fit',
      'title': 'The Classic Christmas H-Box',
    },
    'prodName': 'The Classic Christmas H-Box',
    'prodName24': 'The Classic Christmas H-…',
    'prodName40': 'The Classic Christmas H-Box…',
    'price': '£13.50',
    'stars': '91%',
  },
};