var optionsMarkup = [
			'<div class="WO021_free-delivery">You\'re only <span></span> away from FREE delivery</div>',
			'<div class="WO_ds_wrap">',
				'<div class="WO_delivery">',
				'<div class="WO_delivery_flex">',
					'<div class="WO_activity_dd">',
						'<a class="WO_dd_wrap" href="#">1. Select a delivery method</a>',

						'<h2 class="WO_ds_title">1. Select a delivery method <span>Award Winning Delivery partnered with Parcelforce</span></h2>',
						'<div class="WO_landing_slider">',
							'<div class="WO_slider-wrap">',
								'<div class="WO_slide">Receive a one hour delivery window and we\’ll let you know when Parcelforce are 30 minutes away</div>',
								'<div class="WO_slide">Not going to be in? We\'ll send you an automated text the night before to rearrange your delivery.</div>',
							'</div>',
						'</div>',
						'<div class="WO_activities WO_delivery_target">',
						'</div>',
					'</div>',
				'</div>',
			'</div>',
			'<div class="WO_delivery">',
			'<div class="WO_delivery_flex">',
				'<div class="WO_activity_dd">',
					'<a class="WO_dd_wrap" href="#">2. Do you want Surefit Protection?</a>',
					'<h2 class="WO_ds_title">2. Do you want Surefit Protection?</h2>',
					'<div class="WO_input_chk">',
						'<label>No thanks, I\’ve definitely measured correctly</label>',
						'<input type="checkbox" />',
					'</div>',
					'<div class="WO021_sub-title">',
						'<h3>65% of customers added Surefit Protection this year</h3>',
					'</div>',
					'<p class="WO_surefit_number">65% of customers added Surefit Protection this year</p>',
					'<div class="WO_surefit_desc">',
						'<p>Made to measure blinds must be unused and in their original packaging. We thoroughly recommend using Surefit Protection - a scheme that ensures that any honest mistake of mis-measuring your windows is protected. <a href="/pages/returns/" target="_blank">Returns policy</a></p>',
						'<p><a href="#" data-toggle="modal" data-target="#surefitModal">Read more on our popular Surefit guarantee</a></p>',
					'</div>',
					'<div class="WO_activities WO_surefit_target">',
					'</div>',
				'</div>',
			'</div>',
			'</div>',
			'</div>'
].join('');

export default optionsMarkup;
