export default [
  {name: "Beige", colour: "#F5F5DC"},
  {name: "Berry", colour: "#d41717"},
  {name: "Black", colour: "#000"},
  {name: "Blue", colour: "#171998"},
  {name: "Blush", colour: "#de5d83"},
  {name: "Brown", colour: "#a95c0d"},
  {name: "Burgundy", colour: "#8C001A"},
  {name: "Camel", colour: "#C19A6B"},
  {name: "Champagne", colour: "#F7E7CE"},
  {name: "Charcoal", colour: "#36454f"},
  {name: "Cobalt", colour: "#212169"},
  {name: "Coral", colour: "#ff7f50"},
  {name: "Cream", colour: "#fffdd0"},
  {name: "Deep Mauve", colour: "#C15E69"},
  {name: "Fuchsia", colour: "#c01a5c"},
  {name: "Gold", colour: "#ffd700"},
  {name: "Green", colour: "#005d00"},
  {name: "Grey", colour: "#808080"},
  {name: "Ivory", colour: "#F2ECE8"},
  {name: "Khaki", colour: "#888170"},
  {name: "Lemon", colour: "#f6ebb6"},
  {name: "Lilac", colour: "#C8A2C8"},
  {name: "Mauve", colour: "#E0B0FF"},
  {name: "Mink", colour: "#D9B3AC"},
  {name: "Mint", colour: "#3EB489"},
  {name: "Mocha", colour: "#654634"},
  {name: "Mustard", colour: "#FFDB58"},
  {name: "Navy", colour: "#000080"},
  {name: "Nude", colour: "#E4B295"},
  {name: "Orange", colour: "#FF7F00"},
  {name: "Peach", colour: "#FFE5B4"},
  {name: "Pink", colour: "#FFC0CB"},
  {name: "Plum", colour: "#8E4585"},
  {name: "Purple", colour: "#9F00C5"},
  {name: "Red", colour: "#D90000"},
  {name: "Rose", colour: "#FF033E"},
  {name: "Rose Gold", colour: "#EFD2C9"},
  {name: "Rose Pink", colour: "#e6a3aa"},
  {name: "Rust", colour: "#D0683F"},
  {name: "Silver", colour: "#F0F8FF"},
  {name: "Stone", colour: "#D7C4BC"},
  {name: "Tan", colour: "#D2B48C"},
  {name: "Taupe", colour: "#BD9787"},
  {name: "Teal", colour: "#008080"},
  {name: "Turquoise", colour: "#68C6D2"},
  {name: "White", colour: "#FFF"},
  {name: "White Gold", colour: "#FAF9FE"},
  {name: "Wine", colour: "#722F37"},
  {name: "Yellow", colour: "#FFFF00"},
  {name: "Aqua", colour: "#46edf8"},
  {name: "Snake Print", colour: "#E5D9CF"},
];
