export default {
  '/fragrance/perfume/all-perfume' : {
    '/fragrance/fragrance-offers/fragrance-offers-save-up-to-half-price' : 'Save up to 1/2 price',
    '/fragrance/luxury-fragrance': 'Luxury Fragrance',
    '/fragrance/fragrance-offers': 'Fragrance Offers',
    '/fragrance/fragrance-gift-sets/perfume-gift-sets': 'Perfume Gift Sets',
    '/fragrance/new-in-fragrance': 'New in Fragrance',
  },
  '/baby-child/mothercare-clothing/mothercare-baby-clothes-0-24-months' : {
    '/toys': 'Toys',
    '/baby-child/baby-child-offers': 'Baby & Child Offers',
    '/baby-child/mothercare-clothing': 'Mothercare Clothing',
    '/baby-child/mothercare-clothing': 'New In Clothing',
    '/baby-child/nursery-furniture/baby-bedding': 'Bedding',
  },
  '/beauty/luxury-beauty-skincare/luxury-beauty-makeup' : {
    '/beauty/luxury-beauty-skincare/all-luxury-skincare': 'All Luxury Skincare',
    '/beauty/all-beauty-and-skincare-brands': 'Beauty & Skincare Brands',
    '/beauty/makeup/face': 'Face',
    '/beauty/makeup/face/foundation': 'Foundation',
    '/beauty/hair/hair-dye/hair-dye-permanent': 'Permanent Hair Dye',
  },
  '/fragrance/aftershave/mens-aftershave' : {
    '/fragrance/perfume/all-perfume': 'All Perfume',
    '/fragrance/aftershave/aftershave-gift-sets': 'Aftershave Gift Sets',
    '/fragrance-offers/fragrance-offers-save-up-to-half-price': 'Save up to 1/2 price',
    '/fragrance/new-in-fragrance': 'New in Fragrance',
    '/all-christmas-gifts-for-him': 'Christmas Gifts for Him',
  },
  '/health-pharmacy/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient' : {
    '/wellness/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient/vitamin-D': 'Vitamin D',
    '/wellness/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient/vitamin-B-complex': 'Vitamin B',
    '/wellness/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient/iron': 'Iron',
    '/wellness/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient/cod-liver-oils': 'Cod Liver Oil',
    '/wellness/vitaminsandsupplements/vitamins-supplements-shop-by-ingredient/vitamin-B12': 'Vitamin B12',
  },
  '/beauty/beauty-skincare-offers' : {
    '/beauty/beauty-value-packs-and-bundles': 'Beauty Value Pack & Bundles',
    '/beauty/new-in-beauty-skincare': 'New In Beauty',
    '/beauty/makeup/face': 'Face',
    '/bootsclearance/all-clearance': 'Clearance',
    '/beauty/skincare/skincare-all-skincare': 'All Skincare',
  },
  '/beauty/new-in-beauty-skincare' : {
    '/beauty/trending-products': 'Trending Products',
    '/beauty/skincare/facial-skincare': 'Facial Skincare',
    '/beauty/beauty-skincare-offers': 'Skincare Offers',
    '/beauty/makeup/face': 'Face',
    '/beauty/skincare/skincare-all-skincare': 'All Skincare',
  },
  '/beauty/makeup/face/foundation' : {
    '/beauty/makeup/face': 'Face',
    '/beauty/makeup': 'Makeup',
    '/beauty/makeup/face/concealer-correctors': 'Concealers & Correctors',
    '/beauty/beauty-skincare-offers': 'Beauty & Skincare Offers',
    '/beauty/luxury-beauty-skincare': 'Luxury Beauty & Skincare',
  },
  '/beauty/makeup/face' : {
    '/beauty/makeup/face/foundation': 'Foundation',
    '/beauty/makeup/face/concealer-correctors': 'Concealers & Correctors',
    '/beauty/makeup/face/powder': 'Powder',
    '/beauty/makeup/face/blusher': 'Blusher',
    '/beauty/makeup/face/primer': 'Primer',
  },
};