export const brandImgData = [
  {
    title: 'Drills',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/makita_drill.png',
        href: '/c/tools/drills/cat830704?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/dewalt_drill.png',
        href: '/c/tools/drills/cat830704?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'bosch',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/bosch_drill.png',
        href: '/c/tools/drills/cat830704?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/milwaukee_drill.png',
        href: '/c/tools/drills/cat830704?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'titan',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/titan_drill.png',
        href: '/c/tools/drills/cat830704?brand=titan',
        frame: 'titan_frame',
        border: 'titan_border',
        brandAlt: 'Titan',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://blcro.fra1.digitaloceanspaces.com/SCR020/erbauer_drills.png',
        href: '/c/tools/drills/cat830704?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },
    ],
  },
  {
    title: 'Power Tool Batteries & Chargers',
    brandProducts: [
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewallt_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
      },
      {
        title: 'titan',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/titan_battery.png',
        href: '/c/tools/power-tool-batteries-chargers/cat830696?brand=titan',
        frame: 'titan_frame',
        border: 'titan_border',
        brandAlt: 'Titan',
      },
    ],
  },
  {
    title: 'Bare Units',
    brandProducts: [
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_bare.png',
        href: '/c/tools/bare-units/cat7230005?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_bare.png',
        href: '/c/tools/bare-units/cat7230005?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_bare.png',
        href: '/c/tools/bare-units/cat7230005?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_bare.png',
        href: '/c/tools/bare-units/cat7230005?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_bare.png',
        href: '/c/tools/bare-units/cat7230005?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
    ],
  },
  {
    title: 'Angle Grinders',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_angle.png',
        href: '/c/tools/angle-grinders/cat830694?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_angle.png',
        href: '/c/tools/angle-grinders/cat830694?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_angle.png',
        href: '/c/tools/angle-grinders/cat830694?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },

      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_angle.png',
        href: '/c/tools/angle-grinders/cat830694?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_angle.png',
        href: '/c/tools/angle-grinders/cat830694?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },
    ],
  },
  {
    title: 'Multi Tools',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'dremel',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dremel_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=dremel',
        frame: 'dremel_frame',
        border: 'dremel_border',
        brandAlt: 'Dremel',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_multi.png',
        href: '/c/tools/multi-tools/cat830708?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
    ],
  },
  {
    title: 'Planers',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_planers.png',
        href: '/c/tools/planers/cat830902#category=cat830902&brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_planers.png',
        href: '/c/tools/planers/cat830902#category=cat830902&brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_planers.png',
        href: '/c/tools/planers/cat830902#category=cat830902&brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_planers.png',
        href: '/c/tools/planers/cat830902#category=cat830902&brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },

      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_planers.png',
        href: '/c/tools/planers/cat830902#category=cat830902&brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
    ],
  },
  {
    title: 'Electric Screwdrivers',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/maikta_es.png',
        href: '/c/tools/electric-screwdrivers/cat830720#category=cat830720&brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_es.png',
        href: '/c/tools/electric-screwdrivers/cat830720#category=cat830720&brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_ec.png',
        href: '/c/tools/electric-screwdrivers/cat830720#category=cat830720&brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_es.png',
        href: '/c/tools/electric-screwdrivers/cat830720#category=cat830720&brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },

      {
        title: 'senco',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/senco_es.png',
        href: '/c/tools/electric-screwdrivers/cat830720#category=cat830720&brand=senco',
        frame: 'senco_frame',
        border: 'senco_border',
        brandAlt: 'Senco',
      },
    ],
  },
  {
    title: 'Sanders',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_sanders.png',
        href: '/c/tools/sanders/cat830906?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'erbauer',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/erbauer_sanders.png',
        href: '/c/tools/sanders/cat830906?brand=erbauer',
        frame: 'erbauer_frame',
        border: 'erbauer_border',
        brandAlt: 'Erbauer',
      },

      {
        title: 'titan',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/titan_sander.png',
        href: '/c/tools/sanders/cat830906?brand=titan',
        frame: 'titan_frame',
        border: 'titan_border',
        brandAlt: 'Titan',
      },
      {
        title: 'triton',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/triton_sanders.png',
        href: '/c/tools/sanders/cat830906?brand=triton_power_tools',
        frame: 'triton_frame',
        border: 'triton_border',
        brandAlt: 'Triton_Power_Tools',
      },
    ],
  },
  {
    title: 'Polishers',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_polisher.png',
        href: '/c/tools/polishers/cat12980002?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_polisher.png',
        href: '/c/tools/polishers/cat12980002?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'bosch',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/bosch_polisher.png',
        href: '/c/tools/polishers/cat12980002?brand=bosch',
        frame: 'bosch_frame',
        border: 'bosch_border',
        brandAlt: 'Bosch',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_polisher.png',
        href: '/c/tools/polishers/cat12980002?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'titan',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/titan_polisher.png',
        href: '/c/tools/polishers/cat12980002?brand=titan',
        frame: 'titan_frame',
        border: 'titan_border',
        brandAlt: 'Titan',
      },
    ],
  },
  {
    title: 'Nail Guns',
    brandProducts: [
      {
        title: 'makita',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/makita_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=makita',
        frame: 'makita_frame',
        border: 'makita_border',
        brandAlt: 'Makita',
      },
      {
        title: 'deWalt',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/dewalt_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=dewalt',
        frame: 'dewalt_frame',
        border: 'dewalt_border',
        brandAlt: 'DeWalt',
      },
      {
        title: 'rapid',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/rapid_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=rapid',
        frame: 'rapid_frame',
        border: 'rapid_border',
        brandAlt: 'Rapid',
      },
      {
        title: 'senco',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/senco_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=senco',
        frame: 'senco_frame',
        border: 'senco_border',
        brandAlt: 'Senco',
      },
      {
        title: 'milwaukee',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/milwaukee_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=milwaukee',
        frame: 'milwaukee_frame',
        border: 'milwaukee_border',
        brandAlt: 'Milwaukee',
      },
      {
        title: 'paslode',
        imgSrc: 'https://ucds.ams3.digitaloceanspaces.com/Screwfix/paslode_nail.png',
        href: '/c/tools/nail-guns/cat830710?brand=paslode',
        frame: 'paslode_frame',
        border: 'paslode_border',
        brandAlt: 'Paslode',
      },
    ],
  },
];
