export const productData = {
    "9178066": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178066/Omega+Seamaster+Diver+300+M+210.30.42.20.01.001/",
        "modelNumber": "210.30.42.20.01.001",
        "introCopy": "To celebrate the Olympic Winter Games Beijing 2022, OMEGA presents this exclusive Special Edition timepiece from the Seamaster Diver 300M collection.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureOneContent": "A self-winding movement with Co-Axial escapement, and is certified as a Master Chronometer by METAS. This means that it is highly resistant to magnetic fields, making it the perfect choice for those who want a durable watch. The free sprung-balance with silicon balance spring ensures accuracy, while the automatic winding in both directions makes this watch easy to use. With a 55 hour power reserve, the Omega Seamaster is a watch that you can rely on.",
        "featureTwoTitle": "Superior Precision",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureTwoContent": "The Omega Seamaster has been tested and certified twice to ensure the utmost precision and accuracy. The first test is conducted by the Official Swiss Chronometer Control (COSC) with precision criteria of -4/+6 seconds per day. The second test, conducted by the Swiss Federal Institute of Metrology (METAS), sets stricter criteria of 0/+6 seconds per day. This certified timepiece is a testament to Omega's dedication to quality and excellence.",
        "featureThreeTitle": "Water- Resistance",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureThreeContent": "To ensure the integrity of Omega timepieces, not just some but all watches are fully immersed in water and pressure is applied up to point-where they're guaranteed resistant against it. By submerging each watch Omega have chosen, yet again, to exceed normal testing standards for a more rigorous examination process that will better protect your investment as well!",
        "featureFourTitle": "Anti-Magnetic",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/fc1d4c48-d5ce-11ec-ab26-42333164cbde",
        "featureFourContent": "Everyday items such as mobile phones, metal clasps on handbags and laptops can affect the performance of a watch for good. To prevent permanent deviations from happening up to several minutes per day we've created movements with antimagnetic materials like silicon balance springs that resist high fields: these allow us not only train more regularly but also ensure accuracy in any situation!",
        "detailsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/4f4f75b8-d515-11ec-9bcb-0ecebc03ad43",
        "detailsContent": "Introducing the Omega Seamaster, a special edition watch crafted to celebrate the Beijing Olympic Winter Games 2022. This timepiece is built for durability and precision, with a stainless steel construction and grade 5 titanium bezel ring. The sun-brushed blue ceramic dial is laser-engraved with waves and features rhodium-plated indexes and hands filled with Super-LumiNova. As a tribute to the upcoming Beijing Olympics, this watch also features five special minute-markers at 2H, 4H, 8H, 10H and 12H. Powered by OMEGA's Co-Axial Master Chronometer Calibre 8800 movement, this watch is accurate to within +2/-2 seconds per day and",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178066-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "1250523": {
        "url": "https://www.ernestjones.co.uk/webstore/d/1250523/Omega+Speedmaster+Moonwatch+Professional+2021+Men%27s+Watch/",
        "modelNumber": "31030425001001",
        "introCopy": "One of the world’s most iconic timepieces, embraced by watch enthusiasts for its dive-inspired design and incredible functionality.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/9258397c-bbf1-11ec-b506-aac29d4e9359",
        "featureOneContent": "The manual-winding movement with Co-Axial escapement is certified by METAS and resistant to magnetic fields, making it a durable and reliable watch. The free-spung balance with silicon balance spring ensures accuracy, while the rhodium-plated finish and bridges with straight Geneva waves give the watch an elegant look. With a power reserve of 50 hours, this watch is sure to keep you on time, no matter what you're doing.",
        "featureTwoTitle": "Superior Precision",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureTwoContent": "Looking for a timepiece that is not only precise, but also certified by the Official Swiss Chronometer Control? The Speedmaster Moonwatch watch is powered by Omega's Master Chronometer movement, which has been tested and certified twice for your peace of mind. With a precision of -4/+6 seconds per day, you can be sure that this watch will keep you on time. The complete watch and its movement have also undergone eight Master Chronometer tests set by the Swiss Federal Institute of Metrology, with criteria of 0/+5 seconds per day.",
        "featureThreeTitle": "Durability",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/f738844a-d5ce-11ec-980c-42333164cbde",
        "featureThreeContent": "The Omega Master Chronometer watches are tested and certified twice. Firstly the movement is checked by COSC with precision criteria of -4/+6 seconds per day; then it goes on eight more tests set up by METAS for accuracy to within 0/60th second anywhere throughout its lifetime!",
        "featureFourTitle": "Water Resistance",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureFourContent": "What makes the Speedmaster Moonwatch so special? First, it undergoes rigorous testing to ensure its water resistance. In fact, each watch is fully immersed in water and pressure-tested to ensure it can withstand depths of up to the guaranteed water resistance. Second, it features a sleek design that is sure to turn heads. And third, it comes with a full warranty, so you can be confident in your purchase.",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/1250523-alt1-1490.webp",
        "detailsContent": "The Speedmaster Moonwatch is an iconic timepiece that has been a part of all six moon missions. It's no surprise then, given its adventurous spirit and representation as one-of-akind for NASA’s 4th generation space suit worn on the mission to Earth' s natural satellite--the 1968 version was designed by Bill reaction when he reactivated his company after serving in World War II -that this model features hesalite glass before stainless steel bracelets were invented! The 42 mm size fits well with modern tastes while still distortion free thanks topful details like black step dials enhancedby dot over 90 aluminum bezel rings. A prestigious brand combining flair with timekeeping precision, Omega has created iconic watches over its 150 year history.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "y",
        "specsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/69422f88-bbf2-11ec-b723-7219699406b5",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/93601222-bbf1-11ec-939e-ba0d03883f41",
        "packageImg": "https://d34qiagx43sg99.cloudfront.net/1250523-alt2-1490.webp",
        "packageContent": "The Omega Speedmaster is a work of art, and that's reflected in its packaging. The watch comes in a sturdy, premium box that's lined with soft fabric to protect the watch. The presentation is impressive, with the watch nestled in a foam insert and surrounded by an informational booklet. Everything about the packaging conveys a feeling of quality, making it clear that the Omega Speedmaster is a high-end timepiece."
    },
    "4885023": {
        "url": "https://www.ernestjones.co.uk/webstore/d/4885023/Omega+Seamaster+James+Bond+007+Edition+Bracelet+Watch/",
        "modelNumber": "210.90.42.20.01.001",
        "introCopy": "Follow in the footsteps of 007, with the identical timepiece to the watch worn by James Bond in No Time To Die.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/11c3abb8-d50d-11ec-9576-2e450f8b8cbb",
        "featureOneContent": "A masterful piece of mechanics, the Calibre Omega 8806 is a certified chronometer watch which has been approved by METAS. This timepiece features an automatic movement with silicon balance spring and enables both directions for winding power in its self-winding system! It also comes equipped to resist against magnetic fields thanks their rhodium plated rotors as well Geneva waves arabesque design on bridges made from gold tone metal making them appear luxurious yet lightweight at heart.",
        "featureTwoTitle": "Superior Precision",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureTwoContent": "Master chronometer certification has twice the precision of an officially certified clock. First, the movement is tested by COSC with criteria that are -4/+6 seconds per day; then they go on to pass eight tests set up under Switzerland's Federal Institute for Metrology (METAS) which require 0/- 06s across all sections within your timepiece!",
        "featureThreeTitle": "Water- Resistance",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureThreeContent": "Omega is committed to creating timepieces that can withstand the elements, no matter how extreme. To ensure the integrity of their watches at depth, they immerse each one in water and apply pressure up to the point of its guaranteed water resistance. By submerging each watch in water Omega have chosen, yet again, to exceed normal testing standards, so you can be confident that your Omega will perform flawlessly, no matter what the conditions.",
        "featureFourTitle": "Shock Resistance",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/01d26f92-d5cf-11ec-839e-aa61e4fa425b",
        "featureFourContent": "Omega Speedmasters are put through a series of tests during the homologation process in order to ensure their reliability and precision. One of these tests is the shock examination, where the watch is dropped from a height of 1 metre onto a hard wooden floor. This test is conducted to confirm that the watch can withstand severe impacts and maintain its accuracy. All Omega timepieces are designed to withstand shocks corresponding to this 1-metre drop, ensuring that they can withstand everyday wear and tear.",
        "detailsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/352c422e-d515-11ec-b821-aa9d82b8500d",
        "detailsContent": "The Omega Seamaster Diver 300M 007 Edition is the perfect watch for Bond fans and watch enthusiasts alike. It's based on the same design as 007's watch in No Time To Die, but with a slimmer construction and innovative adjustable buckle. It's also powered by OMEGA's Co-Axial Master Chronometer 8806, which has achieved the industry’s highest standards of precision, chronometric performance - and of course - magnetic resistance.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "y",
        "specsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/a34cd508-d528-11ec-83ca-5ec7b4e4325b",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "9178074": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178074/Omega+Seamaster+Diver+Men%27s+Stainless+Steel+Bracelet+Watch+210.30.42.20.03.001/",
        "modelNumber": "210.30.42.20.03.001",
        "introCopy": "The Omega Seamaster is a classic dive watch that has been loved by many since 1993. The modern collection has taken everything that made the original so great and updated it with Omega's best innovation and design.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureOneContent": "Introducing the Omega Seamaster, a Master Chronometer certified by METAS and resistant to magnetic fields up to 15,000 gauss. This beautifully crafted timepiece features a self-winding movement with Co-Axial escapement, rhodium plated finish with Geneva waves in arabesque, and a free sprung-balance with silicon balance spring. Automatic winding in both directions makes this watch an excellent choice for those who appreciate the finer things in life.",
        "featureTwoTitle": "Less Servicing",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/e6ffcdb8-d5ce-11ec-9d07-d61988d8d708",
        "featureTwoContent": "The Omega Seamaster is a high-end watch that is known for its durability and accuracy. One of the features that makes it so durable and accurate is its Co-Axial escapement. This feature significantly reduces the need for lubrication, which in turn reduces the need for servicing. Omega watches with this feature can go longer between servicing than many other brands, making them a great choice for those who want a reliable watch that doesn't require frequent maintenance.",
        "featureThreeTitle": "Water- Resistance",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureThreeContent": "To ensure the integrity of Omega timepieces, not just some but all watches are fully immersed in water and pressure is applied up to point-where they're guaranteed resistant against it. By submerging each watch Omega have chosen, yet again, to exceed normal testing standards for a more rigorous examination process that will better protect your investment as well!",
        "featureFourTitle": "Anti-Magnetic",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/fc1d4c48-d5ce-11ec-ab26-42333164cbde",
        "featureFourContent": "The Omega Seamaster is the perfect watch for those who need accuracy and precision in their lives. With proprietary anti-magnetic materials, this watch is resistant to the everyday items that can cause permanent deviations in timekeeping. Whether you're at the office or out on the town, you can rest assured that your Omega Seamaster will keep you on schedule.",
        "detailsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/0b176e3a-d52b-11ec-99b4-daad233e5fa5",
        "detailsContent": "The Omega Seamaster is a stainless steel watch that welcomes inspiration from the ocean heritage. It has a navy enamel bezel and a coordinating dial with a blue wave lasered pattern. The hour markings are set out with white and silver-tone circular markings, and the seconds and hours hands are rhodium plated. The watch is completed with the stainless steel bracelet, boasts water resistance of up to 300 metres, and is professional in tone.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178074-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "1250558": {
        "url": "https://www.ernestjones.co.uk/webstore/d/1250558/Omega+Speedmaster+Moonwatch+Professional+2021+Men%27s+Watch/",
        "modelNumber": "310.30.42.50.01.002",
        "introCopy": "The Speedmaster Moonwatch is a icon of the world, having been present at six successful moon landings. This impressive timepiece shows that Omega’s adventurous and pioneering spirit never dies no matter where they are in history!",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/355302e0-d50d-11ec-b03b-d25a3ddee338",
        "featureOneContent": "This Omega Speedmaster Moonwatch Professional is a manual-winding chronograph movement with Co-Axial escapement. It's certified Master Chronometer, approved by METAS, and resistant to magnetic fields reaching 15,000 gauss. The finish is Rhodium-plated, and the bridges have straight Geneva waves. It has a power reserve of 50 hours.",
        "featureTwoTitle": "Superior Precision",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureTwoContent": "Certified twice for the highest precision, the Master Chronometer watches are the choice of professionals who demand the utmost in accuracy. With criteria of -4/+6 seconds per day for COSC certification and 0/+5 seconds per day for METAS certification, Omega watches are accurate to within fractions of a second.",
        "featureThreeTitle": "Anti - Magnetic",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/fc1d4c48-d5ce-11ec-ab26-42333164cbde",
        "featureThreeContent": "Introducing the Omega Speedmaster Moonwatch Professional, designed with antimagnetic materials to prevent performance deviations up to several minutes a day. With its innovative technology and sleek design, this watch is perfect for professionals who demand the best timekeeping performance possible.",
        "featureFourTitle": "Shock Resistance",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/01d26f92-d5cf-11ec-839e-aa61e4fa425b",
        "featureFourContent": "Omega Speedmasters are put through a series of tests during the homologation process in order to ensure their reliability and precision. One of these tests is the shock examination, where the watch is dropped from a height of 1 metre onto a hard wooden floor. This test is conducted to confirm that the watch can withstand severe impacts and maintain its accuracy. All Omega timepieces are designed to withstand shocks corresponding to this 1-metre drop, ensuring that they can withstand everyday wear and tear.",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/1250558-alt1-606.jpg",
        "detailsContent": "The Omega Speedmaster Professional is a classic timepiece that has been worn by astronauts on the moon. This watch features a polished-brushed five-arched-links-per-row bracelet, sapphire crystal glass on the front and caseback, and an asymmetrical case. The black step dial has an applied OMEGA logo, and the bezel ring has the famous dot over 90 on the anodised aluminium. The Omega Co-Axial Master Chronometer Calibre 3861 powers the small seconds sub-dial, 30-minute recorder and 12-hour recorder, along with the central chronograph function.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/1250558-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "2467488": {
        "url": "https://www.ernestjones.co.uk/webstore/d/2467488/Omega+Seamaster+Diver+Men%E2%80%99s+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "210.30.42.20.04.001",
        "introCopy": "The Seamaster Professional Diver 300M is one of the most sought after watches in history. It’s been updated to include all new innovations and designs from OMEGA, making it better than ever before!",
        "featureOneTitle": "Water-Resistance",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureOneContent": "To ensure the integrity of Omega timepieces, not just some but all watches are fully immersed in water and pressure is applied up to point-where they're guaranteed resistant against it. By submerging each watch Omega have chosen, yet again, to exceed normal testing standards for a more rigorous examination process that will better protect your investment as well!",
        "featureTwoTitle": "Movement",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureTwoContent": "Introducing the Omega Seamaster, a Master Chronometer certified by METAS and resistant to magnetic fields up to 15,000 gauss. This beautifully crafted timepiece features a self-winding movement with Co-Axial escapement, rhodium plated finish with Geneva waves in arabesque, and a free sprung-balance with silicon balance spring. Automatic winding in both directions makes this watch an excellent choice for those who appreciate the finer things in life.",
        "featureThreeTitle": "Durability",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/f738844a-d5ce-11ec-980c-42333164cbde",
        "featureThreeContent": "Omega watches are the pinnacle of precision engineering. Their watches are put through 8 rigorous tests to ensure that each one is a certified Master Chronometer. With a 5-year warranty, you know your Omega watch will last for years to come.",
        "featureFourTitle": "Supieror-Precision",
        "featureFourImg": "",
        "featureFourContent": "The Omega Master Chronometer watches are tested and certified twice. Firstly the movement is checked by COSC with precision criteria of -4/+6 seconds per day; then it goes on eight more tests set up by METAS for accuracy to within 0/60th second anywhere throughout its lifetime!",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/2467488-alt1-606.jpg",
        "detailsContent": "The Omega Seamaster is a classic watch that has been updated with modern features. The 42 mm stainless steel case is sleek and polished, and the black ceramic bezel with white enamel diving scale adds a touch of sophistication. The dial is polished white ceramic and features laser-engraved waves and Seamaster highlighted in red. The polished, blackened skeleton hour and minute hands are filled with white Super-LumiNova. The seconds hand features a varnished red tip. The watch is presented on a polished-brushed stainless steel bracelet and is driven by the OMEGA Master Chronometer Calibre 8800, which can be seen through the sapphire-crystal on the wave-edged caseback.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/2467488-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "4981545": {
        "url": "https://www.ernestjones.co.uk/webstore/d/4981545/Omega+Speedmaster+Moonwatch+Men%27s+Steel+Bracelet+Watch/",
        "modelNumber": "304.30.44.52.01.001",
        "introCopy": "The Speedmaster Moonwatch is a icon of the world, having been present at six successful moon landings. This impressive timepiece shows that Omega’s adventurous and pioneering spirit never dies no matter where they are in history!",
        "featureOneTitle": "Moonphase Complication",
        "featureOneImg": "https://d34qiagx43sg99.cloudfront.net/4981545-606.jpg",
        "featureOneContent": "The Omega Speedmaster Moonphase is a watch that accurately indicates the phase of the moon. The watch has a metallic crystal disc that is microstructured to obtain a high resolution image of the moon. The watch is powered by a Swiss movement and has a stainless steel case. The Omega Speedmaster Moonphase is a beautiful watch that is perfect for those who want to keep track of the moon's cycle.",
        "featureTwoTitle": "Movement",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/a4fc8f4c-d514-11ec-8122-baf75e2b199e",
        "featureTwoContent": "Calibre Omega 9904 is a self-winding chronograph with column wheel and Co-Axial escapement. Certified Master Chronometer, approved by METAS, resistant to magnetic fields reaching 15,000 gauss. Silicon balance-spring, 2 barrels mounted in series. Central hour, minute and chronograph seconds hands, small seconds hand, date indication by hand, 12-hour and 60-minute recorders and moonphase indication. Rhodium plated finish with Geneva waves in arabesque. 60 HOURS POWER RESERVE.",
        "featureThreeTitle": "Superior Precision",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureThreeContent": "Certified twice for the highest precision, the Omega Master Chronometer watches are the choice of professionals who demand the utmost in accuracy. With criteria of -4/+6 seconds per day for COSC certification and 0/+5 seconds per day for METAS certification, Omega watches are accurate to within fractions of a second.",
        "featureFourTitle": "Shock Resistance",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/01d26f92-d5cf-11ec-839e-aa61e4fa425b",
        "featureFourContent": "Omega Speedmasters are put through a series of tests during the homologation process in order to ensure their reliability and precision. One of these tests is the shock examination, where the watch is dropped from a height of 1 metre onto a hard wooden floor. This test is conducted to confirm that the watch can withstand severe impacts and maintain its accuracy. All Omega timepieces are designed to withstand shocks corresponding to this 1-metre drop, ensuring that they can withstand everyday wear and tear.",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/4981545-alt3-606.webp",
        "detailsContent": "Omega Speedmaster Moonphase: A Timeless Classic. This 44.25 mm model is the perfect timepiece for those who appreciate classic elegance. The black sun-brushed dial features rhodium-plated indexes and hands, while the accurate Moonphase indication at 6 o'clock is sure to impress. The stainless steel case is complemented by a black ceramic bezel ring with Liquidmetal™ tachymeter scale, and presented on a stainless steel bracelet with polished-brushed foldover clasp. This watch also boasts 60 hours power reserve, making it an ideal choice for busy professionals who need a reliable timepiece they can count on.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/4981545-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "9178597": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178597/Omega+Speedmaster+Men%27s+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "32430385001001",
        "introCopy": "The Omega Speedmaster 38 mm is a simple, yet iconic timepiece that draws inspiration from the company’s most famous chronograph.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/52dfd144-d50d-11ec-bb69-0ecebc03ad43",
        "featureOneContent": "The Calibre Omega 3330 is a self-winding chronograph with a column-wheel mechanism and Co-Axial escapement. It has a free sprung-balance equipped with Si14 silicon balance spring, making it incredibly accurate. The chronometer has also been certified for accuracy, making it the perfect choice for professionals.",
        "featureTwoTitle": "Tachymeter",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/f05379be-d5ce-11ec-b9b6-d61988d8d708",
        "featureTwoContent": "Whether you're a professional driver or just like to track your speed, this Speedmaster watch is the perfect tool for the job. With a tachymeter and chronograph, it's perfect for measuring speed over time. So whether you're on the racetrack or the open road, this watch will make sure you're always keeping pace.",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "When it comes to timekeeping, Omega is all about the details. That's why they use synthetic sapphire crystal for their watches. Sapphire crystal is extremely scratch-resistant and has an anti-reflective treatment, so you can always see the time clearly. So whether you're at work or at play, you can be sure that your Omega watch will keep telling time flawlessly.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/9178597-alt3-606.webp",
        "detailsContent": "This Omega Speedmaster watch is perfect for professionals who need a reliable timepiece. The stainless steel case and bezel provide durability, while the black dial ensures easy reading. The three subdials help you keep track of elapsed time, and the date window ensures you always know what day it is. Plus, the OMEGA Co-Axial Calibre 3330 ensures accurate timekeeping.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178597-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "6940110": {
        "url": "https://www.ernestjones.co.uk/webstore/d/6940110/Omega+Speedmaster+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "324.30.38.50.06.001",
        "introCopy": "The Omega Speedmaster 38 mm is a simple, yet iconic timepiece that draws inspiration from the company’s most famous chronograph.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/52dfd144-d50d-11ec-bb69-0ecebc03ad43",
        "featureOneContent": "The Calibre Omega 3330 is a self-winding chronograph with a column-wheel mechanism and Co-Axial escapement. It has a free sprung-balance equipped with Si14 silicon balance spring, making it incredibly accurate. The chronometer has also been certified for accuracy, making it the perfect choice for professionals.",
        "featureTwoTitle": "Tachymeter",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/f05379be-d5ce-11ec-b9b6-d61988d8d708",
        "featureTwoContent": "Whether you're a professional driver or just like to track your speed, this Speedmaster watch is the perfect tool for the job. With a tachymeter and chronograph, it's perfect for measuring speed over time. So whether you're on the racetrack or the open road, this watch will make sure you're always keeping pace.",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "When it comes to timekeeping, Omega is all about the details. That's why they use synthetic sapphire crystal for their watches. Sapphire crystal is extremely scratch-resistant and has an anti-reflective treatment, so you can always see the time clearly. So whether you're at work or at play, you can be sure that your Omega watch will keep telling time flawlessly.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/9178597-alt3-606.webp",
        "detailsContent": "This Omega Speedmaster watch is perfect for professionals who need a reliable timepiece. The stainless steel case and bezel provide durability, while the sun-brushed grey dial ensures easy reading. The three subdials help you keep track of elapsed time, and the date window ensures you always know what day it is. Plus, the OMEGA Co-Axial Calibre 3330 ensures accurate timekeeping.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/6940110-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "6939856": {
        "url": "https://www.ernestjones.co.uk/webstore/d/6939856/Omega+Seamaster+Aqua+Terra+Men%27s+Steel+Bracelet+Watch/",
        "modelNumber": "220.10.41.21.03.001",
        "introCopy": "The Seamaster Aqua Terra is a beautiful reminder of the rich maritime history that Omega has been cultivating for generations.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/6320b122-d50d-11ec-8da9-b2962f1a38ee",
        "featureOneContent": "The Calibre Omega 8900 is an exquisite timepiece that boasts a self-winding movement with a Co-Axial escapement and a Master Chronometer certification. It's resistant to magnetic fields reaching 15,000 gauss and features a free sprung-balance with silicon balance spring. This premium watch also has a time zone function and a special luxury finish with rhodium-plated rotor and bridges with Geneva waves in arabesque. Plus, it offers up to 60 hours of power reserve.",
        "featureTwoTitle": "Water-Resistance",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureTwoContent": "Omega is committed to creating timepieces that can withstand the elements, no matter how extreme. To ensure the integrity of Omega watches at depth, they immerse each one in water and apply pressure up to the point of its guaranteed water resistance. By submerging each watch in water they have chosen - yet again - to exceed normal testing standards, so you can be confident that your Omega will perform flawlessly, no matter what the conditions.",
        "featureThreeTitle": "Less Servicing",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/e6ffcdb8-d5ce-11ec-9d07-d61988d8d708",
        "featureThreeContent": "The Omega Seamaster Aqua Terra is a high-end watch that is known for its durability and accuracy. One of the features that makes it so durable and accurate is its Co-Axial escapement. This feature significantly reduces the need for lubrication, which in turn reduces the need for servicing. Omega watches with this feature can go longer between servicing than many other brands, making them a great choice for those who want a reliable watch that doesn't require frequent maintenance.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/6939856-alt3-504.webp",
        "detailsContent": "Inspired by the spirit of oceanic adventures, whilst also earning a position in the prestigious chronometer category, this Swiss-made watch has been rigorously tested for its higher levels of magnetic resistance, with five-second increments around the dial for precise tracking and a horizontally textured dial for a powerful and stylish flair. The indices and hands are larger for enhanced readability and the date window is located at the 6 o'clock mark. With a bold nautical theme, this watch is perfect for those who cannot stay away from the sea and demand adventures.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/6939856-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "9178058": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178058/Omega+Seamaster+Diver+Men%27s+Black+Rubber+Strap+Watch/",
        "modelNumber": "21022422001002",
        "introCopy": "The Seamaster Professional Diver 300M is one of the most sought after watches in history. It’s been updated to include all new innovations and designs from OMEGA, making it better than ever before!",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureOneContent": "The Calibre Omega 8800 is a self-winding movement with Co-Axial escapement, certified Master Chronometer approved by METAS and resistant to magnetic fields reaching 15000 gauss; it also features silicon balance spring which makes this watch automatic in both directions as well rhodium plating finish done up delicately through Geneva waves of ornate arabesque design on its 55 hour power reserve indicator ̶ all for your convenience!",
        "featureTwoTitle": "Water-Resistance",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureTwoContent": "Omega is committed to creating timepieces that can withstand the elements, no matter how extreme. To ensure the integrity of Omega watches at depth, they immerse each one in water and apply pressure up to the point of its guaranteed water resistance. By submerging each watch in water they have chosen - yet again - to exceed normal testing standards, so you can be confident that your Omega will perform flawlessly, no matter what the conditions.",
        "featureThreeTitle": "Less Servicing",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/e6ffcdb8-d5ce-11ec-9d07-d61988d8d708",
        "featureThreeContent": "The Omega Seamaster is a high-end watch that is known for its durability and accuracy. One of the features that makes it so durable and accurate is its Co-Axial escapement. This feature significantly reduces the need for lubrication, which in turn reduces the need for servicing. Omega watches with this feature can go longer between servicing than many other brands, making them a great choice for those who want a reliable watch that doesn't require frequent maintenance.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/9178058-alt3-606.jpg",
        "detailsContent": "The Seamaster Diver 300M is one of the most iconic diving timepieces in modern watchmaking. This versatile and durable watch features an elegant 42 mm stainless steel case, paired with a durable black ceramic bezel that lets you accurately track your dive time. The dial of this timepiece is also carefully crafted from black ceramic, while the hands and indices are set with luxurious 18K Sedna gold and filled with sturdy white Super-LumiNova for easy visibility underwater. Additionally, this watch comes equipped with OMEGA's Calibre 8800 movement for precise and reliable timekeeping, as well as a helium escape valve for added safety during deep dives. Whether you're a scuba devotee or simply love a functional, stylish dive watch, the Seamaster Diver 300M is a must-have in any modern collection.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178058-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "6940048": {
        "url": "https://www.ernestjones.co.uk/webstore/d/6940048/Omega+Seamaster+300+Men%27s+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "234.10.39.20.01.001",
        "introCopy": "This Seamaster 300 is the ultimate in classic timepieces, with a limited edition of 3557 pieces.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/11c3abb8-d50d-11ec-9576-2e450f8b8cbb",
        "featureOneContent": "A masterful piece of mechanics, the Calibre Omega 8806 is a certified chronometer watch which has been approved by METAS. This timepiece features an automatic movement with silicon balance spring and enables both directions for winding power in its self-winding system! It also comes equipped to resist against magnetic fields reaching 15000 gauss thanks their rhodium plated rotors as well Geneva waves arabesque design on bridges made from gold tone metal making them appear luxurious yet lightweight at heart",
        "featureTwoTitle": "Water-Resistance",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureTwoContent": "Omega is committed to creating timepieces that can withstand the elements, no matter how extreme. To ensure the integrity of Omega watches at depth, they immerse each one in water and apply pressure up to the point of its guaranteed water resistance. By submerging each watch in water they have chosen - yet again - to exceed normal testing standards, so you can be confident that your Omega will perform flawlessly, no matter what the conditions.",
        "featureThreeTitle": "Less Servicing",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/e6ffcdb8-d5ce-11ec-9d07-d61988d8d708",
        "featureThreeContent": "The Omega Seamaster is a high-end watch that is known for its durability and accuracy. One of the features that makes it so durable and accurate is its Co-Axial escapement. This feature significantly reduces the need for lubrication, which in turn reduces the need for servicing. Omega watches with this feature can go longer between servicing than many other brands, making them a great choice for those who want a reliable watch that doesn't require frequent maintenance.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/6940048-alt1-606.jpg",
        "detailsContent": "The Omega Seamaster 300M Co-Axial Mater Chronometer 39 MM is a modern update of a classic watch. Based on the CK2913, it retains the Naïad sign on the crown and the 1957 Seahorse on the caseback, which areboth symbols of the watch's exceptional water resistance. The watch is cased in brushed and polished stainless steel and features a black 'tropical' dial with vintage indexes that have been slightly deepened to allow filling with Super-LumiNova. The stainless steel bracelet has been updated for strength and features a retro-style OMEGA logo on the clasp. The watch is powered by the Master Chronometer 8806.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/6940048-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "9178589": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178589/Omega+Speedmaster+Moonwatch+Men%27s+Black+Leather+Strap+Watch/",
        "modelNumber": "311.92.44.30.01.001",
        "introCopy": "The Speedmaster Moonwatch is a icon of the world, having been present at six successful moon landings. This impressive timepiece shows that Omega’s adventurous and pioneering spirit never dies no matter where they are in history!",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/7c7e6222-d50d-11ec-8029-2e450f8b8cbb",
        "featureOneContent": "The Calibre Omega 1869 is a manual-winding chronograph movement that is both stylish and functional. The blackened version of the 1861 calibre gives this watch a unique look, while the moon-relief textured dial adds an element of interest. The 48-hour power reserve ensures that you can keep this watch running for longer, making it the perfect choice for those with an active lifestyle.",
        "featureTwoTitle": "Sapphire Crystal",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureTwoContent": "The Omega Speedmaster ",
        "featureThreeTitle": "Tachymeter",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/f05379be-d5ce-11ec-b9b6-d61988d8d708",
        "featureThreeContent": "Whether you're a professional driver or just like to track your speed, this Speedmaster watch is the perfect tool for the job. With a tachymeter and chronograph, it's perfect for measuring speed over time. So whether you're on the racetrack or the open road, this watch will make sure you're always keeping pace.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/9178589-alt3-606.jpg",
        "detailsContent": "Inspired by the 50 year celebration of Apollo 8's first man on the moon mission, Omega presents the Speedmaster Moonwatch chronograph model. Boasting a skeletonised dial, this smart black ceramic build features yellow varnished chronograph hands, co-ordinating with the yellow detailing upon the black leather strap. The dial presents a grey design representing the craters seen on the moon, a charming design to celebrate.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Speedmaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178589-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "4981413": {
        "url": "https://www.ernestjones.co.uk/webstore/d/4981413/Omega+Seamaster+Planet+Ocean+Men%27s+Black+Rubber+Strap+Watch/",
        "modelNumber": "215.32.44.21.01.001",
        "introCopy": "In 2005, Omega launched its new line of watches to commemorate the company’s maritime legacy.",
        "featureOneTitle": "Water-Resistance",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureOneContent": "With its water resistance to 600 metres / 2000 feet / 60 bar, the OMEGA Seamaster Planet Ocean 600M Master Chronometer is the perfect watch for those who love to explore the deep. Featuring a helium-escape valve, this watch is designed to withstand the rigours of deep-sea diving, making it the perfect companion for your next underwater adventure.",
        "featureTwoTitle": "Movement",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/6320b122-d50d-11ec-8da9-b2962f1a38ee",
        "featureTwoContent": "The Calibre Omega 8900 is an exquisite timepiece that boasts a self-winding movement with a Co-Axial escapement and a Master Chronometer certification. It's resistant to magnetic fields reaching 15,000 gauss and features a free sprung-balance with silicon balance spring. This premium watch also has a time zone function and a special luxury finish with rhodium-plated rotor and bridges with Geneva waves in arabesque. Plus, it offers up to 60 hours of power reserve.",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "The Omega Seamaster Planet Ocean 600M Master Chronometer is the perfect watch for professional divers. With its domed scratch-resistant sapphire crystal and antireflective treatment, it's resistant to scratches and glare, making it ideal for underwater use.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/4981413-alt3-606.jpg",
        "detailsContent": "Introducing the OMEGA Seamaster Planet Ocean 600M Master Chronometer. This stylish timepiece pays homage to OMEGA’s dive watch heritage, and is fitted with a scratch-resistant sapphire crystal. The white ceramic dial features Arabic numerals and a date window at 3 o’clock, while the world's premiere black ceramic bezel with orange rubber is mounted on the 43.5 mm stainless steel case. Other features include an alveol screw-in caseback and a black structured rubber strap with orange stitching and lining. It’s the perfect choice for professionals who need a reliable timepiece that can stand up to tough conditions.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/4981413-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "9178090": {
        "url": "https://www.ernestjones.co.uk/webstore/d/9178090/Omega+Seamaster+Diver+Men%27s+Black+Rubber+Strap+Watch/",
        "modelNumber": "210.32.42.20.01.001",
        "introCopy": "The Seamaster Professional Diver 300M is one of the most sought after watches in history. It’s been updated to include all new innovations and designs from OMEGA, making it better than ever before!",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureOneContent": "The Calibre Omega 8800 is a self-winding movement with Co-Axial escapement, certified Master Chronometer approved by METAS and resistant to magnetic fields reaching 15000 gauss; it also features silicon balance spring which makes this watch automatic in both directions as well rhodium plating finish done up delicately through Geneva waves of ornate arabesque design on its 55 hour power reserve indicator ̶ all for your convenience!",
        "featureTwoTitle": "Water-Resistance",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureTwoContent": "Omega is committed to creating timepieces that can withstand the elements, no matter how extreme. To ensure the integrity of Omega watches at depth, they immerse each one in water and apply pressure up to the point of its guaranteed water resistance. By submerging each watch in water they have chosen - yet again - to exceed normal testing standards, so you can be confident that your Omega will perform flawlessly, no matter what the conditions.",
        "featureThreeTitle": "Less Servicing",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/e6ffcdb8-d5ce-11ec-9d07-d61988d8d708",
        "featureThreeContent": "The Omega Seamaster Aqua Terra is a high-end watch that is known for its durability and accuracy. One of the features that makes it so durable and accurate is its Co-Axial escapement. This feature significantly reduces the need for lubrication, which in turn reduces the need for servicing. Omega watches with this feature can go longer between servicing than many other brands, making them a great choice for those who want a reliable watch that doesn't require frequent maintenance.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/9178090-alt3-606.jpg",
        "detailsContent": "The OMEGA Seamaster Diver 300m is a professional diving watch that has been updated with the latest innovation and design. The 42 mm model is crafted from stainless steel and includes a black ceramic bezel with a white enamel diving scale. The dial is also polished black ceramic and features laser-engraved waves and a date window at 6 o’clock. The skeleton hands and raised indexes are rhodium-plated and are filled with white Super-LumiNova, while the helium escape valve has been given a conical design. The watch is presented on a black rubber strap and is driven by the OMEGA Master Chronometer calibre 8800 automatic movement.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/9178090-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "4885058": {
        "url": "https://www.ernestjones.co.uk/webstore/d/4885058/Omega+Seamaster+James+Bond+007+Edition+Strap+Watch/",
        "modelNumber": "210.92.42.20.01.001",
        "introCopy": "Follow in the footsteps of 007, with the identical timepiece to the watch worn by James Bond in No Time To Die.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/11c3abb8-d50d-11ec-9576-2e450f8b8cbb",
        "featureOneContent": "A masterful piece of mechanics, the Calibre Omega 8806 is a certified chronometer watch which has been approved by METAS. This timepiece features an automatic movement with silicon balance spring and enables both directions for winding power in its self-winding system! It also comes equipped to resist against magnetic fields reaching 15000 gauss thanks their rhodium plated rotors as well Geneva waves arabesque design on bridges made from gold tone metal making them appear luxurious yet lightweight at heart",
        "featureTwoTitle": "Superior Precision",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/ddae59e6-d5ce-11ec-9ea4-42333164cbde",
        "featureTwoContent": "Master chronometer certification has twice the precision of an officially certified clock. First, the movement is tested by COSC with criteria that are -4/+6 seconds per day; then they go on to pass eight tests set up under Switzerland's Federal Institute for Metrology (METAS) which require 0/- 06s across all sections within your timepiece!",
        "featureThreeTitle": "Water- Resistance",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureThreeContent": "When it comes to timekeeping, Omega is all about the details. That's why they use synthetic sapphire crystal for their watches. Sapphire crystal is extremely scratch-resistant and has an anti-reflective treatment, so you can always see the time clearly. So whether you're at work or at play, you can be sure that your Omega watch will keep telling time flawlessly.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/4885058-alt2-606.webp",
        "detailsContent": "The Omega Seamaster Diver 300M 007 Edition is the perfect watch for Bond fans and watch enthusiasts alike. It's based on the same design as 007's watch in No Time To Die, but with a slimmer construction and innovative adjustable buckle. It's also powered by OMEGA's Co-Axial Master Chronometer 8806, which has achieved the industry’s highest standards of precision, chronometric performance - and of course - magnetic resistance.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/4885058-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/3362af96-d51a-11ec-a8dd-aa9d82b8500d",
        "packageContent": "Identical to the watch worn by James Bond in No Time To Die, the Seamaster 007 Edition is a work of art, and that's reflected in its packaging. The watch comes in an impressive presentation case. Everything about the packaging conveys a feeling of quality, making it clear that the Omega Seamaster is a high-end timepiece."
    },
    "2467860": {
        "url": "https://www.ernestjones.co.uk/webstore/d/2467860/Omega+Seamaster+Planet+Ocean+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "215.30.44.21.04.001",
        "introCopy": "In 2005, Omega launched its new line of watches to commemorate the company’s maritime legacy.",
        "featureOneTitle": "Water-Resistance",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureOneContent": "With its water resistance to 600 metres / 2000 feet / 60 bar, the OMEGA Seamaster Planet Ocean 600M Master Chronometer is the perfect watch for those who love to explore the deep. Featuring a helium-escape valve, this watch is designed to withstand the rigours of deep-sea diving, making it the perfect companion for your next underwater adventure.",
        "featureTwoTitle": "Movement",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/6320b122-d50d-11ec-8da9-b2962f1a38ee",
        "featureTwoContent": "The Calibre Omega 8900 is an exquisite timepiece that boasts a self-winding movement with a Co-Axial escapement and a Master Chronometer certification. It's resistant to magnetic fields reaching 15,000 gauss and features a free sprung-balance with silicon balance spring. This premium watch also has a time zone function and a special luxury finish with rhodium-plated rotor and bridges with Geneva waves in arabesque. Plus, it offers up to 60 hours of power reserve.",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "The Omega Seamaster Planet Ocean 600M Master Chronometer is the perfect watch for professional divers. With its domed scratch-resistant sapphire crystal and antireflective treatment, it's resistant to scratches and glare, making it ideal for underwater use.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/2467860-alt1-606.jpg",
        "detailsContent": "The OMEGA Seamaster Planet Ocean 600m is a top-of-the-line dive watch that is perfect for those who loves the outdoors and loves to explore. Featuring a 43.5mm stainless steel case, white ceramic dial with applied Arabic numerals, and an orange unidirectional ceramic bezel, this watch is not only stylish but also highly functional. With a water resistance of 600 metres / 2000 feet / 60 bar, this watch can handle even the most extreme conditions. The calibre 8900 at the heart of this timepiece is precision engineered and can be seen through the transparent caseback.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/2467860-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "1566210": {
        "url": "https://www.ernestjones.co.uk/webstore/d/1566210/Omega+Seamaster+300+Men%27s+Stainless+Steel+Bracelet+Watch/",
        "modelNumber": "234.30.41.21.01.001",
        "introCopy": "An iconic watch that has been around for more than 60 years. This new version was created to be even better suited towards adventuring into deeper waters with its enhanced form factor!",
        "featureOneTitle": "Movemenmt",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/cb66fb42-d50d-11ec-87c4-0ecebc03ad43",
        "featureOneContent": "A top-of-the-line self-winding watch movement with Co-Axial escapement. It is certified as a Master Chronometer by METAS and is resistant to magnetic fields up to 15,000 gauss. This makes the Calibre Omega 8912 one of the most accurate and durable watches on the market today. The free-sprung balance with silicon balance spring ensures accuracy, while the two barrels mounted in series provide a power reserve of up to 60 hours. The special luxury finish with Geneva waves in arabesque adds a touch of class to this already exquisite timepiece.",
        "featureTwoTitle": "Sapphire Crystal",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureTwoContent": "When it comes to timekeeping, Omega is all about the details. That's why they use synthetic sapphire crystal for their watches. Sapphire crystal is extremely scratch-resistant and has an anti-reflective treatment, so you can always see the time clearly. So whether you're at work or at play, you can be sure that your Omega watch will keep telling time flawlessly.",
        "featureThreeTitle": "Water- Resistance",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureThreeContent": "Omega are passionate about creating watches that can withstand even the most extreme conditions. That's why every Omega Seamaster is put through a series of rigorous tests to ensure its water resistance. They start by submerging the watch in water and apply pressure until it reaches the point of its guaranteed water resistance. By subjecting each watch to these stringent tests, Omega can be confident that their timepieces will perform at their best – no matter what the conditions.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/1566210-alt1-606.webp",
        "detailsContent": "The first Omega Seamaster 300 was crafted in 1957 , and was designed especially for divers and professionals who worked underwater. Over 60 years later, the watch has been completely upgraded with an enhanced form that is ready for a new generation of adventurers. This sleek 41mm stainless steel model includes a black dial and a black oxalic anodized aluminium bezel with its diving scale filled with vintage Super-LumiNova. The recessed hour markers and open numerals feature Super-LumiNova, which is also present on the rhodium-plated hands.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/1566210-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "8948291": {
        "url": "https://www.ernestjones.co.uk/webstore/d/8948291/Omega+De+Ville+Men%27s+18ct+Rose+Gold+Brown+Strap+Watch/",
        "modelNumber": "43153412152001",
        "introCopy": "The De Ville timepieces from OMEGA are characterised by an elegant and classic design.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/dd0de536-d50d-11ec-adc9-6253156726fb",
        "featureOneContent": "The Calibre Omega 8501 is a self-winding movement with Co-Axial escapement, providing exceptional accuracy and durability. The free sprung-balance ensures long-term stability, while the two barrels mounted in series offer an impressive 60 hours of power reserve. The oscillating mass and balance bridge are finished in luxurious red gold, with exclusive Geneva waves in arabesque. This timepiece is the perfect addition to any collection, and makes an excellent gift for any occasion.",
        "featureTwoTitle": "Red Gold",
        "featureTwoImg": "https://d34qiagx43sg99.cloudfront.net/8948291-504.jpg",
        "featureTwoContent": "The Omega De Ville is a luxurious and high-end watch that is perfect for those who appreciate quality craftsmanship. Made with 18K red gold, this watch is beautiful and also resistant to corrosion. The unique hue of the red gold is perfect for those with sensitive skin. With a focus on quality and attention to detail, the Omega De Ville is a truly luxurious timepiece.",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "Sapphire Crystal is the perfect way to keep your watch looking new. The domed scratch‑resistant sapphire crystal with anti‑reflective treatment on both sides ensures that your watch stays in pristine condition.",
        "featureFourTitle": "",
        "featureFourImg": "",
        "featureFourContent": "",
        "detailsImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/fe0f3988-d52b-11ec-afb3-e65d0d58410f",
        "detailsContent": "The Omega De Ville is a luxurious and sophisticated wristwatch that is perfect for those who appreciate the finer things in life. This model features an 18K red gold case, a two-zone silver dial with Roman numeral hour indexes, and a brown leather strap. The OMEGA Co-Axial calibre 8501 powers this exquisite wristwatch, and the transparent caseback allows you to see the inner workings of this timepiece. The scratch-resistant sapphire crystal protects the beautiful dial, which also features a date window at the 3 o'clock position. With its fine craftsmanship and attention to detail, the Omega De Ville is a truly stunning watch that anyone would be proud to wear.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega De Ville is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/8948291-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "",
        "packageContent": ""
    },
    "1279157": {
        "url": "https://www.ernestjones.co.uk/webstore/d/1279157/Omega+Seamaster+Diver+Beijing+2022+Stainless+Steel+Watch/",
        "modelNumber": "52230422003001",
        "introCopy": "To celebrate the Olympic Winter Games Beijing 2022, OMEGA presents this exclusive Special Edition timepiece from the Seamaster Diver 300M collection.",
        "featureOneTitle": "Movement",
        "featureOneImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/febe2ad4-d50c-11ec-b00e-8e9179792593",
        "featureOneContent": "The Calibre Omega 8800 is a self-winding movement with Co-Axial escapement, certified Master Chronometer approved by METAS and resistant to magnetic fields reaching 15000 gauss; it also features silicon balance spring which makes this watch automatic in both directions as well rhodium plating finish done up delicately through Geneva waves of ornate arabesque design on its 55 hour power reserve indicator ̶ all for your convenience!",
        "featureTwoTitle": "Water-Resistance",
        "featureTwoImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/d2c359dc-d5ce-11ec-9ce3-d61988d8d708",
        "featureTwoContent": "The Omega Seamaster Diver 300M ",
        "featureThreeTitle": "Sapphire Crystal",
        "featureThreeImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/bb13786c-d5ce-11ec-9e35-325ed8faa3cc",
        "featureThreeContent": "When it comes to timekeeping, Omega is all about the details. That's why they use synthetic sapphire crystal for their watches. Sapphire crystal is extremely scratch-resistant and has an anti-reflective treatment, so you can always see the time clearly. So whether you're at work or at play, you can be sure that your Omega watch will keep telling time flawlessly.",
        "featureFourTitle": "Anti-Magnetic",
        "featureFourImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/fc1d4c48-d5ce-11ec-ab26-42333164cbde",
        "featureFourContent": "The Omega Seamaster is the perfect watch for those who need accuracy and precision in their lives. With proprietary anti-magnetic materials, this watch is resistant to the everyday items that can cause permanent deviations in timekeeping. Whether you're at the office or out on the town, you can rest assured that your Omega Seamaster will keep you on schedule.",
        "detailsImg": "https://d34qiagx43sg99.cloudfront.net/1279157-alt1-606.webp",
        "detailsContent": "As the official timekeeper of the Beijing 2022 Winter Olympics, Omega is proud to present the Seamaster Diver 300M. This special edition watch is crafted from stainless steel and includes a grade 5 titanium bezel ring with a diving scale in positive relief. The sun-brushed blue ceramic [ZrO2] dial features laser-engraved waves along with rhodium-plated indexes and hands filled with Super-LumiNova. As a special tribute to Beijing 2022, five special minute-markers are placed at 2H, 4H, 8H, 10H and 12H, each one created in the five colours of the iconic Olympic Rings. Finally, the polished and brushed caseback includes a stamped Olympic emblem, while OMEGA’s patented NAIAD LOCK system keeps all the engravings in perfect alignment.",
        "brandImg": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/92d966f0-bbf1-11ec-bb8f-aac29d4e9359",
        "brandContent": "Omega watches are known for their Premium quality, Heirloom styles, and impeccable taste. For over 100 years, the brand has been producing some of the finest timepieces in the world. Today, Omega is still one of the most respected brands in the industry, and its watches are highly sought after by discerning collectors. Ernest Jones is proud to offer a wide selection of Omega watches, each of which is a true work of art. From the iconic Moonwatch to the stylish Constellation, Omega offers something for everyone. Whether you're looking for a timeless classic or a modern statement piece, Omega has a watch that will suit your style.",
        "specsContent": "The Omega Seamaster is a premium watch that makes an excellent heirloom piece. Its quality construction and stylish design make it a timeless classic that can be passed down for generations. ",
        "isHorizontal": "n",
        "specsImg": "https://d34qiagx43sg99.cloudfront.net/1279157-504.webp",
        "fullWidthBanner": "https://storage.googleapis.com/exp-app-storage/63c9e2be-b0b2-11ea-b9e3-3af835c8f71c/media/original/1455eab0-d519-11ec-b72f-26524239433f",
        "packageImg": "https://d34qiagx43sg99.cloudfront.net/1279157-alt2-1490.webp",
        "packageContent": "To celebrate the Olympic Winter Games Beijing 2022, Omega presents this exclusive Special Edition timepiece from the Seamaster Diver 300M collection. Delivered inside this special presentation box."
    }
}